### PR TITLE
trinity test adds tainting kernel error checking and fix the space before debian

### PR DESCRIPTION
**Pull request by yiwei075**
trinity test adds tainting kernel error checking

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@yiwei075 please resolve pep8 issue

**Comment by harish-24** [comment]
@yiwei075 Any update here?

**Comment by PraveenPenguin** [comment]
@yiwei075 please wrap your commits in valid commit I feel here we can have two commits and please have to commit message like below it will make Travis happy, 
```
subject 

Description 

singed-of signature 
```

for more info please  brows this https://travis-ci.org/github/avocado-framework-tests/avocado-misc-tests/jobs/721891961

**Comment by harish-24** [comment]
@yiwei075 Any updates?

**Comment by harish-24** [comment]
@yiwei075 Please feel free to open a new one with comments incorporated.

**Pull request closed without merging**
