### PR TITLE
Enhanced softwareraid test_v4

### PR DESCRIPTION
**Pull request by vrbagalkote**
Signed-off-by: Venkat R B <vrbagal1@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@vrbagalkote need one help facing issue while running this test 
```
Running 'echo 'yes' | mdadm --create --verbose --assume-clean             /dev/md/mdsraid --level=0 --raid-devices=0              --force'
[stderr] mdadm: invalid number of raid devices: 0

Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado-39.0-py2.7.egg/avocado/core/test.py:448
Traceback (most recent call last):
  File "/root/softwareraid.py", line 66, in test_run
    self.basictest()
  File "/root/softwareraid.py", line 78, in basictest
    self.check_pass(cmd, "Failed to create a MD device")
  File "/root/softwareraid.py", line 124, in check_pass
    self.fail(errmsg)
  File "/usr/local/lib/python2.7/dist-packages/avocado-39.0-py2.7.egg/avocado/core/test.py", line 598, in fail
    raise exceptions.TestFail(message)
TestFail: Failed to create a MD device

Running 'mdadm --manage /dev/md/mdsraid --stop'
[stderr] mdadm: error opening /dev/md/mdsraid: No such file or directory

Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado-39.0-py2.7.egg/avocado/core/test.py:464
Traceback (most recent call last):
  File "/root/softwareraid.py", line 131, in tearDown
    self.check_pass(cmd, "Failed to stop/remove the MD device")
  File "/root/softwareraid.py", line 124, in check_pass
    self.fail(errmsg)
  File "/usr/local/lib/python2.7/dist-packages/avocado-39.0-py2.7.egg/avocado/core/test.py", line 598, in fail
    raise exceptions.TestFail(message)
TestFail: Failed to stop/remove the MD device

FAIL 1-softwareraid.py:SoftwareRaid.test_run -> TestFail: Failed to create a MD device

Test results available in /root/avocado/job-results/job-2016-08-31T12.02-7f11630
root@f24:~# 
```
one suggestion can we need to have a check in test  about device, if device not passed we can skip test ?

**Comment by vrbagalkote** [comment]
@PraveenPenguin May I know how many number of disk you passed in the yaml file? And I feel it is mandatory to  pass certain number of disks, as mentioned in the README file. As this script will not serve the purpose if no disks are given. 

Please let me know your thoughts. 

Thanks in advance.

**Comment by PraveenPenguin** [comment]
@vrbagalkote yes i pass five virtual  Devices from yaml file as i refer your old commit can you please commit README file as well  , my point is can we handle this case as well  if user did any mistake while passing no of device ?

Regards
Praveen

**Comment by PraveenPenguin** [comment]
closing this PR as #23 new version added by @vrbagalkote

**Pull request closed without merging**
