### PR TITLE
port_bounce.py test enhancement

### PR DESCRIPTION
**Pull request by Naresh-ibm**
enahnaced the port_bounce.py test by adding the multipath verification.
removed the port_number dependency of passing it through yaml.

Signed-off-by: Naresh Bannoth <nbannoth@in.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
Ref: https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1424

**Comment by narasimhan-v** [comment]
@Naresh-ibm Please confirm if all comments from previous version of this patch have been addressed

**Comment by Naresh-ibm** [comment]
> @Naresh-ibm Please confirm if all comments from previous version of this patch have been addressed

yes

**Comment by Naresh-ibm** [comment]
[root@ltczz401-lp4 nani]# avocado run new_port.py -m port_bounce.yaml 
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : dc84c5c6cb26040926b8fc2090c64b0da1d117fc
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2019-11-23T20.22-dc84c5c/job.log
 (1/1) new_port.py:PortBounceTest.test;run-42dc: PASS (1708.81 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1709.13 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2019-11-23T20.22-dc84c5c/results.html
[root@ltczz401-lp4 nani]#

**Comment by Naresh-ibm** [comment]
[port_bounce_new_v4_job_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3886324/port_bounce_new_v4_job_log.txt)

**Comment by narasimhan-v** [comment]
> > @Naresh-ibm Please confirm if all comments from previous version of this patch have been addressed
> 
> yes

https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1424/files#r348351004
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1424/files#r348351270

**Comment by Naresh-ibm** [comment]
> > > @Naresh-ibm Please confirm if all comments from previous version of this patch have been addressed
> > 
> > 
> > yes
> 
> https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1424/files#r348351004
> https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1424/files#r348351270

hmmmm, ok. only timing or the explaination too?

**Comment by narasimhan-v** [comment]
@Naresh-ibm both

**Comment by Naresh-ibm** [comment]
closing this in favor of #1449

**Pull request closed without merging**
