### PR TITLE
Fixing usysfault testcase failure and usysattn wrong condition check

### PR DESCRIPTION
**Pull request by shirishaganta1**
Added a condition check to cancel the testcase if the system fault indicators are not supported on the system

### CODE REVIEW

**Comment by shirishaganta1** [comment]
Before
JOB ID : e408d6642ac95615723a3a443b9aed57c6ebb905
JOB LOG : /home/avocado-fvt-wrapper/results/job-2023-04-03T01.50-e408d66/job.log

(1/5) ras_ppcdiag.py:RASToolsPpcdiag.test_build_upstream: STARTED
(1/5) ras_ppcdiag.py:RASToolsPpcdiag.test_build_upstream: CANCEL: This test is supported with upstream as a target (0.73 s)
(2/5) ras_ppcdiag.py:RASToolsPpcdiag.test_nvsetenv: STARTED
(2/5) ras_ppcdiag.py:RASToolsPpcdiag.test_nvsetenv: PASS (0.83 s)
(3/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysattn: STARTED
(3/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysattn: CANCEL: The identify indicators are not supported on this system (1.13 s)
(4/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysfault: STARTED
(4/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysfault: FAIL: ['usysfault -P ', 'usysfault -l The -s normal -t'] command(s) failed to execute (1.00 s)
(5/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysident: STARTED
(5/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysident: CANCEL: The identify indicators are not supported on this system (1.13 s)
RESULTS : PASS 1 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 3
JOB HTML : /home/avocado-fvt-wrapper/results/job-2023-04-03T01.50-e408d66/results.html
JOB TIME : 10.33 s

After
Fetching asset from ras_ppcdiag.py:RASToolsPpcdiag.test_build_upstream
JOB ID     : 6574006041e70069c703677abaecf4bb37038300
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-04-05T23.56-6574006/job.log

 (1/5) ras_ppcdiag.py:RASToolsPpcdiag.test_build_upstream: STARTED
 (1/5) ras_ppcdiag.py:RASToolsPpcdiag.test_build_upstream: CANCEL: This test is supported with upstream as a target (0.75 s)
 (2/5) ras_ppcdiag.py:RASToolsPpcdiag.test_nvsetenv: STARTED
 (2/5) ras_ppcdiag.py:RASToolsPpcdiag.test_nvsetenv: PASS (0.84 s)
 (3/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysattn: STARTED
 (3/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysattn: CANCEL: The identify indicators are not supported on this system (0.98 s)
 (4/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysfault: STARTED
 (4/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysfault: CANCEL: The identify indicators are not supported on this system (0.97 s)
 (5/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysident: STARTED
 (5/5) ras_ppcdiag.py:RASToolsPpcdiag.test_usysident: CANCEL: The identify indicators are not supported on this system (1.17 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 4
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2023-04-05T23.56-6574006/results.html
JOB TIME   : 10.50 s

**Review by Naresh-ibm — CHANGES_REQUESTED** [review]
@shirishaganta1 On which system it is not supported.
I have checked on P10 machine and I could see the output.

can you please also attach the debug.log file for more clarity

**Comment by shirishaganta1** [comment]
> @shirishaganta1 On which system it is not supported. I have checked on P10 machine and I could see the output.
> 
on PowerNV system, it is failing...
> can you please also attach the debug.log file for more clarity

sure

**Comment by shirishaganta1** [comment]
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/11175385/job.log)

**Review by PraveenPenguin — APPROVED** [review]
LGTM

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Pull request merged**
