### PR TITLE
Added support in smt workload to validate dmesg logs.

### PR DESCRIPTION
**Pull request by SamirMulani**
Added support in the SMT workload to validate dmesg logs and copy the SMT logs from the /tmp/ directory to the current job run directory at intervals equal to the runtime duration specified in the .yaml configuration.

### CODE REVIEW

**Comment by SamirMulani** [comment]
`avocado run smt.py:smt.test_check -m smt.py.data/smt.yaml
JOB ID     : 0ad9375389173c4ed0271b72a1a6f2892f81344f
JOB LOG    : /root/Work/fvt/avocado-fvt-wrapper-1/results/job-2024-09-09T11.35-0ad9375/job.log
 (1/1) smt.py:smt.test_check;run-b36f: STARTED
 (1/1) smt.py:smt.test_check;run-b36f: PASS (242.53 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/Work/fvt/avocado-fvt-wrapper-1/results/job-2024-09-09T11.35-0ad9375/results.html
JOB TIME   : 347.66 s`

**Comment by Naresh-ibm** [comment]
@SamirMulani why are we copying the logs from /tmp to current run logs. this will unnecessarily fills the current working dir.

**Comment by SamirMulani** [comment]
> @SamirMulani why are we copying the logs from /tmp to current run logs. this will unnecessarily fills the current working dir.
@Naresh-ibm We need to include those logs as part of the current workload analysis to investigate any potential issues related to SMT state regression. so that's why I am copying those logs as a part of job directory itself.

**Review by Naresh-ibm — APPROVED** [review]
LGTM

**Pull request merged**
