### PR TITLE
shiner parameters for driver_parameter.py test

### PR DESCRIPTION
**Pull request by vaishnavibhat**
yaml file for Shiner bnx2x driver.

Signed-off-by: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by vaishnavibhat** [comment]
localhost:~ #avocado run driver_param.py -m shiner.yaml 
/usr/lib/python3.6/site-packages/avocado_framework-75.1-py3.6.egg/avocado/plugins/run.py:214: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast, keep-tmp and ignore-missing-references.
  FutureWarning)
JOB ID     : 144322699574d0a1d22a26e8a0d12879160da73b
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-02-20T13.02-1443226/job.log
 (01/11) driver_param.py:Moduleparameter.test;num_que_1-ab55: PASS (82.00 s)
 (02/11) driver_param.py:Moduleparameter.test;dis_tpa_1-4bf9: PASS (76.10 s)
 (03/11) driver_param.py:Moduleparameter.test;dis_tpa_0-86b9: PASS (76.41 s)
 (04/11) driver_param.py:Moduleparameter.test;int_1-5c15: PASS (76.35 s)
[bnx2x_param.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4229563/bnx2x_param.log)

 (05/11) driver_param.py:Moduleparameter.test;int_2-b59f: PASS (86.07 s)
 (06/11) driver_param.py:Moduleparameter.test;mrrs_0-56cc: PASS (76.35 s)
 (07/11) driver_param.py:Moduleparameter.test;mrrs_1-fb5a: PASS (76.70 s)
 (08/11) driver_param.py:Moduleparameter.test;mrrs_2-3659: PASS (76.72 s)
 (09/11) driver_param.py:Moduleparameter.test;mrrs_3-b2bc: PASS (75.77 s)
 (10/11) driver_param.py:Moduleparameter.test;debug_0-056e: PASS (75.41 s)
 (11/11) driver_param.py:Moduleparameter.test;debug_1-f5af: PASS (75.65 s)
RESULTS    : PASS 11 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 856.54 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-02-20T13.02-1443226/results.html

**Comment by manvanthar** [comment]
@vaishnavibhat 

Available parameter for the card.

2020-02-20 13:03:25,497 process          L0436 DEBUG| [stdout] parm:           num_queues: Set number of queues (default is as a number of CPUs) (int)
2020-02-20 13:03:25,497 process          L0436 DEBUG| [stdout] parm:           disable_tpa: Disable the TPA (LRO) feature (int)
2020-02-20 13:03:25,497 process          L0436 DEBUG| [stdout] parm:           int_mode: Force interrupt mode other than MSI-X (1 INT#x; 2 MSI) (int)
2020-02-20 13:03:25,498 process          L0436 DEBUG| [stdout] parm:           dropless_fc: Pause on exhausted host ring (int)
2020-02-20 13:03:25,498 process          L0436 DEBUG| [stdout] parm:           mrrs: Force Max Read Req Size (0..3) (for debug) (int)
2020-02-20 13:03:25,498 process          L0436 DEBUG| [stdout] parm:           debug: Default debug msglevel (int)

1. dropless_fc is missing in yaml.     dropless_fc=1   should be covered.  Attached file
[bnx2x-README.TXT](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4230527/bnx2x-README.TXT)



2. and num_queues should be tested for more than value 1.     "Cat /proc/interrupts | grep driver-name" should give the queues and  even ethtool .    So we should cover that many num of queues.

**Comment by narasimhan-v** [comment]
@manvanthar review please.

**Comment by manvanthar** [comment]
@vaishnavibhat @narasimhan-v   only point 1 is addressed.   point 2 still need to be fixed.

Also would be better if we have job.log please.   without that my review will be incomplete.

**Comment by narasimhan-v** [comment]
@vaishnavibhat Is this still being pursued ?

**Comment by narasimhan-v** [comment]
@vaishnavibhat updates please

**Comment by vaishnavibhat** [comment]
Resending the yaml file including module_param_value 0,1,8,64 and 1024. 

avocado run driver_parameter.py -m driver_parameter.py.data/driver_parameter_bnx2x.yaml
/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/plugins/run.py:281: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  FutureWarning)
JOB ID     : 13a8d5ca9fab5bbd253bb8d2a3c3580c17e74e50
JOB LOG    : /root/abdul/avocado-fvt-wrapper/results/job-2020-08-14T12.32-13a8d5c/job.log
 (01/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_0-6a61: PASS (39.43 s)
 (02/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_1-d761: PASS (36.42 s)
 (03/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_8-10de: PASS (36.03 s)
 (04/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_64-503b: PASS (49.81 s)                                        
 (05/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_1024-e141: PASS (36.85 s)
 (06/16) driver_parameter.py:Moduleparameter.test;run-Test-disable_tpa-value-dis_tpa_1-80fd: PASS (40.49 s)
 (07/16) driver_parameter.py:Moduleparameter.test;run-Test-disable_tpa-value-dis_tpa_0-0822: PASS (40.21 s)
 (08/16) driver_parameter.py:Moduleparameter.test;run-Test-int_mode-value-int_1-a1a7: PASS (36.40 s)
 (09/16) driver_parameter.py:Moduleparameter.test;run-Test-int_mode-value-int_2-c947: PASS (38.90 s)
 (10/16) driver_parameter.py:Moduleparameter.test;run-Test-mrrs-value-mrrs_0-1ec5: PASS (36.44 s)
 (11/16) driver_parameter.py:Moduleparameter.test;run-Test-mrrs-value-mrrs_1-7d4c: PASS (39.87 s)
 (12/16) driver_parameter.py:Moduleparameter.test;run-Test-mrrs-value-mrrs_2-2418: PASS (36.32 s)
 (13/16) driver_parameter.py:Moduleparameter.test;run-Test-mrrs-value-mrrs_3-bcd8: PASS (36.28 s)
 (14/16) driver_parameter.py:Moduleparameter.test;run-Test-debug-value-debug_0-a492: PASS (36.25 s)
 (15/16) driver_parameter.py:Moduleparameter.test;run-Test-debug-value-debug_1-4272: PASS (36.20 s)
 (16/16) driver_parameter.py:Moduleparameter.test;run-Test-dropless_fc-value-dropless_fc_1-3e07: PASS (36.00 s)
RESULTS    : PASS 16 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/abdul/avocado-fvt-wrapper/results/job-2020-08-14T12.32-13a8d5c/results.html
JOB TIME   : 612.28 s

[shiner.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5073211/shiner.log)

**Comment by manvanthar** [comment]
Thank you. Looks fine to me!!

**Pull request merged**
