### PR TITLE
generic/rcutorture: Reuse cpu functions for offline and online

### PR DESCRIPTION
**Pull request by abdhaleegit**
CPU off-on commands from process.system() function never got
executed, replace with cpu off on functions in utils.py
Also added tags to be a kernel tests and replace skip with cancel

Signed-off-by: Abdul Haleem <abdhalee@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by abdhaleegit** [comment]
implemented comments from #539

**Comment by PraveenPenguin** [comment]
@abdhaleegit job log please

**Comment by abdhaleegit** [comment]
[rcutoturelogs.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/1091210/rcutoturelogs.txt)

**Comment by PraveenPenguin** [comment]
@abdhaleegit i think we can wait for this 

https://github.com/avocado-framework/avocado/pull/2084

**Pull request merged**
