### PR TITLE
[Backport]packages.py:Changed few lines of code

### PR DESCRIPTION
**Pull request by shirishaganta**
Based on issue #1385 modified the script to run correctly

Signed-off-by: Shirisha Ganta <shiganta@in.ibm.com>

### CODE REVIEW

**Comment by shirishaganta** [comment]
On Baremetal:
JOB ID     : 553d24a0d38e8d9c6d35090608e1e91ca8ed6e02
JOB LOG    : /home/siri/avocado-fvt-wrapper-py2/results/job-2019-11-21T04.23-553d24a/job.log
 (1/1) packages_test.py:Package_check.test: PASS (9.19 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 9.88 s
JOB HTML   : /home/siri/avocado-fvt-wrapper-py2/results/job-2019-11-21T04.23-553d24a/results.html

**Comment by shirishaganta** [comment]
@Pavithra1602  Please review this once

**Comment by Pavithra1602** [comment]
looks good

**Comment by shirishaganta** [comment]
I lost this branch on my TP. will discuss with pavithra and send a new patch for this if necessary because I have seen this testcase has passed without any changes . So closing it now

**Pull request closed without merging**
