### PR TITLE
Modified the way infiniband rdma tests run

### PR DESCRIPTION
**Pull request by narasimhan-v**
1. Infiniband RDMA tests had some code duplications. Removed them.
2. Those Infiniband RDMA tests had some processing in the test
script, which is best left to yaml file. This improves readability
of summary and results.

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
```
# avocado run rdma_tests.py -m rdma_tests.py.data/ib_write_bw_basic.yaml 
JOB ID     : 60bf153e52c8264a7837e819d5668462d19cd23c
JOB LOG    : /var/lib/libvirt/images/avocado-fvt-wrapper/results/job-2018-03-28T13.01-60bf153/job.log
 (1/6) rdma_tests.py:RDMA.test;ib_write_bw_basic--F-5cde: PASS (4.48 s)
 (2/6) rdma_tests.py:RDMA.test;ib_write_bw_basic--m_1024-dabe: PASS (4.32 s)
 (3/6) rdma_tests.py:RDMA.test;ib_write_bw_basic--n_10000-c4bf: PASS (4.51 s)
 (4/6) rdma_tests.py:RDMA.test;ib_write_bw_basic--S_2-455f: PASS (4.31 s)
 (5/6) rdma_tests.py:RDMA.test;ib_write_bw_basic--t_1024-7931: PASS (4.40 s)
 (6/6) rdma_tests.py:RDMA.test;ib_write_bw_basic--p_18200-4872: PASS (4.30 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 28.98 s
JOB HTML   : /var/lib/libvirt/images/avocado-fvt-wrapper/results/job-2018-03-28T13.01-60bf153/results.html
```
```
# avocado run rdma_tests.py -m rdma_tests.py.data/ib_write_bw_extended.yaml 
JOB ID     : 1f075569f860906a5c8aec251f9f136831b722c2
JOB LOG    : /var/lib/libvirt/images/avocado-fvt-wrapper/results/job-2018-03-28T13.24-1f07556/job.log
 (01/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--b-ef2d: PASS (4.45 s)
 (02/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--N-9209: PASS (4.36 s)
 (03/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--c_UC-0447: PASS (4.37 s)
 (04/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--c_RC-6ac7: PASS (4.37 s)
 (05/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--D_10s-f79f: PASS (14.29 s)
 (06/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--l_4-6053: PASS (4.34 s)
 (07/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--Q_5-791f: PASS (4.34 s)
 (08/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--w_100M-86a5: PASS (4.29 s)
 (09/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--x_1-7394: PASS (4.34 s)
 (10/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--y_10G-4145: PASS (4.31 s)
 (11/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--z-d61a: PASS (4.32 s)
 (12/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_--reversed-5f4c: FAIL (3.08 s)
 (13/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R-b7f8: PASS (4.39 s)
 (14/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-a-9864: PASS (25.14 s)
 (15/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-b-7caa: PASS (4.41 s)
 (16/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-c_RC-0f55: PASS (4.36 s)
 (17/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-D_30s-cab9: PASS (34.33 s)
 (18/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-f_5s-038c: FAIL (3.09 s)
 (19/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-l_2-343f: PASS (4.36 s)
 (20/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-m_2048-e104: PASS (4.38 s)
 (21/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-n_100000-3fd8: PASS (5.30 s)
 (22/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-N-de64: PASS (4.34 s)
 (23/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-p_18600-87a1: PASS (4.38 s)
 (24/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-q_1-3417: PASS (4.39 s)
 (25/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-Q_10-0240: PASS (4.36 s)
 (26/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-s_9000-5fd2: PASS (4.31 s)
 (27/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-S_1-b6ab: PASS (4.41 s)
 (28/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-t_2048-6958: PASS (4.42 s)
 (29/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-T_128-5baf: PASS (4.40 s)
 (30/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-w_10M-7fbc: PASS (4.36 s)
 (31/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-x_1-d8de: PASS (4.41 s)
 (32/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-y_4G-8782: PASS (4.38 s)
 (33/33) rdma_tests.py:RDMA.test;ib_write_bw_extended--R_-z-c335: PASS (4.36 s)
RESULTS    : PASS 31 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 215.16 s
JOB HTML   : /var/lib/libvirt/images/avocado-fvt-wrapper/results/job-2018-03-28T13.24-1f07556/results.html
```

**Comment by Naresh-ibm** [comment]
verified on ROCE adapter too. looks fine for me.

**Comment by PraveenPenguin** [comment]
@narasimhan-v can you please make these changes in two commits 
1- one to remove duplicate 
2- yaml processing 
other wise looks good

**Comment by narasimhan-v** [comment]
@PraveenPenguin They are dependent. To remove the duplicates, we need to change the yaml, and vice versa.

**Comment by PraveenPenguin** [comment]
@narasimhan-v ah ok , thanks for help , than will merge

**Pull request merged**
