### PR TITLE
ssh package fix for SuSE

### PR DESCRIPTION
**Pull request by hathyaga**
patch fixes ssh package check for SuSE distro

Signed-off-by: Harsha Thyagaraja <harshkid@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
job log please

**Comment by hathyaga** [comment]
@PraveenPenguin  Job log attached 
[scp_ssh_PASS.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/933758/scp_ssh_PASS.txt)

**Comment by hathyaga** [comment]
@PraveenPenguin @narasimhan-v  Please let me know if this fix is ok. If yes, I will send fixes for other scripts under io/net path as well. 
Thanks.

**Comment by PraveenPenguin** [comment]
@hathyaga yup looks good , can you include all change in this commit , if you are ok with that will wait ?

**Comment by hathyaga** [comment]
@PraveenPenguin Sure. I'll add the changes required for all the scripts and send a PR.

**Comment by PraveenPenguin** [comment]
@hathyaga thanks

**Comment by hathyaga** [comment]
Closing this PR.
Sent a new PR applying this fix to all scripts that needs this fix.

https://github.com/avocado-framework-tests/avocado-misc-tests/pull/451

**Pull request closed without merging**
