### PR TITLE
changes for multiple vnic with different adapter id

### PR DESCRIPTION
**Pull request by smruti77**
script will create mutiple vnic with different adapter id and different port.
because we can't create bond interfcae with same adapter vnic interface.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
[vnic.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5474024/vnic.log)

**Comment by smruti77** [comment]
```
04:19:18 INFO    : Check for environment
04:19:18 INFO    : Creating temporary mux dir
04:19:28 INFO    : 
04:19:28 INFO    : Running Host Tests Suite io_vnic_bond_htx_network_virtualization_NetworkVirtualization_test_add_network_virtualization
04:19:28 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_add$ -m /tmp/mux/io_vnic_bond_htx_network_virtualization_NetworkVirtualization_test_add_network_virtualization.yaml --force-job-id 46d8e8b5353c1578934aae933e7ab0f5f1c55830  --job-results-dir /root/avocado-fvt-wrapper/results
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : 46d8e8b5353c1578934aae933e7ab0f5f1c55830
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.19-46d8e8b/job.log
 (1/1) avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_add;run-f409: PASS (41.83 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.19-46d8e8b/results.html
JOB TIME   : 43.43 s
04:20:36 INFO    : 
04:20:37 INFO    : 
04:20:37 INFO    : Running Host Tests Suite io_vnic_bond_htx_bonding_Bonding_test_setup_bonding_single
04:20:37 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/bonding.py:Bonding.test_setup$ -m /tmp/mux/io_vnic_bond_htx_bonding_Bonding_test_setup_bonding_single.yaml --force-job-id b247da6b98419d8f004777d2791ba69704ad1806  --job-results-dir /root/avocado-fvt-wrapper/results
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : b247da6b98419d8f004777d2791ba69704ad1806
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.20-b247da6/job.log
 (1/1) avocado-misc-tests/io/net/bonding.py:Bonding.test_setup;run-d6c1: PASS (21.39 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.20-b247da6/results.html
JOB TIME   : 22.53 s
04:21:19 INFO    : 
04:21:19 INFO    : 
04:21:19 INFO    : Running Host Tests Suite io_vnic_bond_htx_htx_nic_devices_HtxNicTest_test_start_htx_nic_devices
04:21:19 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_start$ -m /tmp/mux/io_vnic_bond_htx_htx_nic_devices_HtxNicTest_test_start_htx_nic_devices.yaml --force-job-id 03d333dca640229264b4050cdcf0398b1bf55cb6  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 03d333dca640229264b4050cdcf0398b1bf55cb6
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.21-03d333d/job.log
 (1/1) avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_start;run-7798: PASS (253.49 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.21-03d333d/results.html
JOB TIME   : 254.83 s
04:25:53 INFO    : 
04:25:53 INFO    : 
04:25:53 INFO    : Running Host Tests Suite io_vnic_bond_htx_bonding_Bonding_test_run_bonding_single
04:25:53 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/bonding.py:Bonding.test_run$ -m /tmp/mux/io_vnic_bond_htx_bonding_Bonding_test_run_bonding_single.yaml --force-job-id db4d0c5ceecb8c281db3195c59a5756e77b7d902  --job-results-dir /root/avocado-fvt-wrapper/results
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : db4d0c5ceecb8c281db3195c59a5756e77b7d902
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.25-db4d0c5/job.log
 (1/1) avocado-misc-tests/io/net/bonding.py:Bonding.test_run;run-d6c1: FAIL: Tests failed. Details:\nPing fail in Mode 1 when interface env6 down\nPing fail in Mode 1 when interface env7 down (135.63 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.25-db4d0c5/results.html
JOB TIME   : 136.92 s
04:28:32 INFO    : 
04:28:32 INFO    : 
04:28:32 INFO    : Running Host Tests Suite io_vnic_bond_htx_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices
04:28:32 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check$ -m /tmp/mux/io_vnic_bond_htx_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.yaml --force-job-id 0a06ea5e06df44273061c5f01db534439897b1cd  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 0a06ea5e06df44273061c5f01db534439897b1cd
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.28-0a06ea5/job.log
 (1/1) avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-7798: FAIL: Their are errors while htx run in peer (123.33 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.28-0a06ea5/results.html
JOB TIME   : 124.68 s
04:30:59 INFO    : 
04:30:59 INFO    : 
04:30:59 INFO    : Running Host Tests Suite io_vnic_bond_htx_htx_nic_devices_HtxNicTest_test_stop_htx_nic_devices
04:30:59 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_stop$ -m /tmp/mux/io_vnic_bond_htx_htx_nic_devices_HtxNicTest_test_stop_htx_nic_devices.yaml --force-job-id b2a1cf6456505c3d36929d1a55427c4bb6ad3c4a  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : b2a1cf6456505c3d36929d1a55427c4bb6ad3c4a
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.31-b2a1cf6/job.log
 (1/1) avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_stop;run-7798: ERROR: Command 'ifup enP32778p1s0f0 ' exited with 10.\nOutput:\n["Error: unknown connection '/etc/sysconfig/network-scripts/ifcfg-enP32778p1s0f0'."] (146.52 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.31-b2a1cf6/results.html
JOB TIME   : 147.77 s
04:33:48 INFO    : 
04:33:48 INFO    : 
04:33:48 INFO    : Running Host Tests Suite io_vnic_bond_htx_bonding_Bonding_test_cleanup_bonding_single
04:33:48 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/bonding.py:Bonding.test_cleanup$ -m /tmp/mux/io_vnic_bond_htx_bonding_Bonding_test_cleanup_bonding_single.yaml --force-job-id d6e8950c936dbd5696048caa40db52d2274086de  --job-results-dir /root/avocado-fvt-wrapper/results
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : d6e8950c936dbd5696048caa40db52d2274086de
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.33-d6e8950/job.log
 (1/1) avocado-misc-tests/io/net/bonding.py:Bonding.test_cleanup;run-d6c1: PASS (8.64 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.33-d6e8950/results.html
JOB TIME   : 9.82 s
04:34:17 INFO    : 
04:34:17 INFO    : 
04:34:17 INFO    : Running Host Tests Suite io_vnic_bond_htx_network_virtualization_NetworkVirtualization_test_remove_network_virtualization
04:34:17 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_remove$ -m /tmp/mux/io_vnic_bond_htx_network_virtualization_NetworkVirtualization_test_remove_network_virtualization.yaml --force-job-id 8b00e8d75dabf951e53ce55e4221e435afaff3d1  --job-results-dir /root/avocado-fvt-wrapper/results
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : 8b00e8d75dabf951e53ce55e4221e435afaff3d1
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.34-8b00e8d/job.log
 (1/1) avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_remove;run-f409: PASS (37.47 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.34-8b00e8d/results.html
JOB TIME   : 38.61 s
04:35:15 INFO    : 
04:35:15 INFO    : Summary of test results can be found below:
TestSuite                                                                                                  TestRun    Summary
 
host_io_vnic_bond_htx_network_virtualization_NetworkVirtualization_test_add_network_virtualization         Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.19-46d8e8b/job.log
| PASS 1 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_bond_htx_bonding_Bonding_test_setup_bonding_single                                            Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.20-b247da6/job.log
| PASS 1 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_bond_htx_htx_nic_devices_HtxNicTest_test_start_htx_nic_devices                                Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.21-03d333d/job.log
| PASS 1 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_bond_htx_bonding_Bonding_test_run_bonding_single                                              Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.25-db4d0c5/job.log
| PASS 0 || CANCEL 0 || ERRORS 0 || FAILURES 1 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_bond_htx_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices                                Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.28-0a06ea5/job.log
| PASS 0 || CANCEL 0 || ERRORS 0 || FAILURES 1 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_bond_htx_htx_nic_devices_HtxNicTest_test_stop_htx_nic_devices                                 Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.31-b2a1cf6/job.log
| PASS 0 || CANCEL 0 || ERRORS 1 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_bond_htx_bonding_Bonding_test_cleanup_bonding_single                                          Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.33-d6e8950/job.log
| PASS 1 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_bond_htx_network_virtualization_NetworkVirtualization_test_remove_network_virtualization      Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.34-8b00e8d/job.log
| PASS 1 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
04:35:15 INFO    : Removing temporary mux dir
```
```
04:37:48 INFO    : Check for environment
04:37:48 INFO    : Creating temporary mux dir
04:37:52 INFO    : 
04:37:52 INFO    : Running Host Tests Suite io_vnic_mtu9000_bond1_network_virtualization_NetworkVirtualization_test_add_network_virtualization
04:37:52 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_add$ -m /tmp/mux/io_vnic_mtu9000_bond1_network_virtualization_NetworkVirtualization_test_add_network_virtualization.yaml --force-job-id 161bd9f13173b0f4a80d01ffca8f979fe939a593  --job-results-dir /root/avocado-fvt-wrapper/results
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : 161bd9f13173b0f4a80d01ffca8f979fe939a593
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.37-161bd9f/job.log
 (1/1) avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_add;run-f409: PASS (39.57 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.37-161bd9f/results.html
JOB TIME   : 40.75 s
04:38:52 INFO    : 
04:38:52 INFO    : 
04:38:52 INFO    : Running Host Tests Suite io_vnic_mtu9000_bond1_bonding_Bonding_test_setup_bonding_single
04:38:52 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/bonding.py:Bonding.test_setup$ -m /tmp/mux/io_vnic_mtu9000_bond1_bonding_Bonding_test_setup_bonding_single.yaml --force-job-id 90ce358df02c052b4d0eab96e363cd8055a92b33  --job-results-dir /root/avocado-fvt-wrapper/results
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : 90ce358df02c052b4d0eab96e363cd8055a92b33
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.38-90ce358/job.log
 (1/1) avocado-misc-tests/io/net/bonding.py:Bonding.test_setup;run-fa01: PASS (30.10 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.38-90ce358/results.html
JOB TIME   : 31.23 s
04:39:42 INFO    : 
04:39:42 INFO    : 
04:39:42 INFO    : Running Host Tests Suite io_vnic_mtu9000_bond1_bonding_Bonding_test_run_bonding_single
04:39:42 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/bonding.py:Bonding.test_run$ -m /tmp/mux/io_vnic_mtu9000_bond1_bonding_Bonding_test_run_bonding_single.yaml --force-job-id 5b6d98d97410c94dffe32623433894b92c1ab361  --job-results-dir /root/avocado-fvt-wrapper/results
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : 5b6d98d97410c94dffe32623433894b92c1ab361
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.39-5b6d98d/job.log
 (1/1) avocado-misc-tests/io/net/bonding.py:Bonding.test_run;run-fa01: FAIL: Tests failed. Details:\nPing fail in Mode 1 when interface env6 down\nPing fail in Mode 1 when interface env7 down (135.50 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.39-5b6d98d/results.html
JOB TIME   : 136.71 s
04:42:18 INFO    : 
04:42:18 INFO    : 
04:42:18 INFO    : Running Host Tests Suite io_vnic_mtu9000_bond1_bonding_Bonding_test_cleanup_bonding_single
04:42:18 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/bonding.py:Bonding.test_cleanup$ -m /tmp/mux/io_vnic_mtu9000_bond1_bonding_Bonding_test_cleanup_bonding_single.yaml --force-job-id f973bcff5ddd55a1e9bcea570b83607782bcd562  --job-results-dir /root/avocado-fvt-wrapper/results
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : f973bcff5ddd55a1e9bcea570b83607782bcd562
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.42-f973bcf/job.log
 (1/1) avocado-misc-tests/io/net/bonding.py:Bonding.test_cleanup;run-fa01: PASS (73.97 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.42-f973bcf/results.html
JOB TIME   : 75.14 s
04:43:53 INFO    : 
04:43:53 INFO    : 
04:43:53 INFO    : Running Host Tests Suite io_vnic_mtu9000_bond1_network_virtualization_NetworkVirtualization_test_remove_network_virtualization
04:43:53 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_remove$ -m /tmp/mux/io_vnic_mtu9000_bond1_network_virtualization_NetworkVirtualization_test_remove_network_virtualization.yaml --force-job-id 7f59b7381c5f5c8ac8ae16a59e3932f72737ea97  --job-results-dir /root/avocado-fvt-wrapper/results
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : 7f59b7381c5f5c8ac8ae16a59e3932f72737ea97
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.43-7f59b73/job.log
 (1/1) avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_remove;run-f409: PASS (37.79 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-10-16T04.43-7f59b73/results.html
JOB TIME   : 38.93 s
04:44:51 INFO    : 
04:44:51 INFO    : Summary of test results can be found below:
TestSuite                                                                                                       TestRun    Summary
 
host_io_vnic_mtu9000_bond1_network_virtualization_NetworkVirtualization_test_add_network_virtualization         Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.37-161bd9f/job.log
| PASS 1 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_mtu9000_bond1_bonding_Bonding_test_setup_bonding_single                                            Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.38-90ce358/job.log
| PASS 1 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_mtu9000_bond1_bonding_Bonding_test_run_bonding_single                                              Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.39-5b6d98d/job.log
| PASS 0 || CANCEL 0 || ERRORS 0 || FAILURES 1 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_mtu9000_bond1_bonding_Bonding_test_cleanup_bonding_single                                          Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.42-f973bcf/job.log
| PASS 1 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
 
host_io_vnic_mtu9000_bond1_network_virtualization_NetworkVirtualization_test_remove_network_virtualization      Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2020-10-16T04.43-7f59b73/job.log
| PASS 1 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
04:44:51 INFO    : Removing temporary mux dir
```

**Comment by smruti77** [comment]
single vnic device 
```
JOB ID     : 0bfb35039fe147d7cbc5ea8be92ba904fbf38024
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2020-11-03T02.19-0bfb350/job.log
 (1/9) network_virtualization.py:NetworkVirtualization.test_add;run-bfd9: PASS (25.09 s)
 (2/9) network_virtualization.py:NetworkVirtualization.test_backingdevadd;run-bfd9: PASS (29.21 s)
 (3/9) network_virtualization.py:NetworkVirtualization.test_hmcfailover;run-bfd9: ERROR: Failed to ping: Command 'ping -I env6 147.1.1.246 -c 5' failed.\nstdout: b'PING 147.1.1.246 (147.1.1.246) from 147.1.1.247 env6: 56(84) bytes of data.\n\n--- 147.1.1.246 ping statistics ---\n5 packets transmitted, 0 received, 100% packet loss, time 197ms\n... (52.56 s)
 (4/9) network_virtualization.py:NetworkVirtualization.test_clientfailover;run-bfd9: ERROR: Failed to ping: Command 'ping -I env6 147.1.1.246 -c 5' failed.\nstdout: b'PING 147.1.1.246 (147.1.1.246) from 147.1.1.247 env6: 56(84) bytes of data.\n\n--- 147.1.1.246 ping statistics ---\n5 packets transmitted, 0 received, 100% packet loss, time 146ms\n... (46.69 s)
 (5/9) network_virtualization.py:NetworkVirtualization.test_vnic_auto_failover;run-bfd9: PASS (60.08 s)
 (6/9) network_virtualization.py:NetworkVirtualization.test_rmdev_viosfailover;run-bfd9: PASS (59.41 s)
 (7/9) network_virtualization.py:NetworkVirtualization.test_vnic_dlpar;run-bfd9: PASS (54.11 s)
 (8/9) network_virtualization.py:NetworkVirtualization.test_backingdevremove;run-bfd9: PASS (19.09 s)
 (9/9) network_virtualization.py:NetworkVirtualization.test_remove;run-bfd9: FAIL: Network virtualization remove device operation                        failed (9.64 s)
RESULTS    : PASS 6 | ERROR 2 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2020-11-03T02.19-0bfb350/results.html
JOB TIME   : 357.56 s
```

**Comment by smruti77** [comment]
[single_vnic.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5493635/single_vnic.log)

**Review by abdhaleegit — CHANGES_REQUESTED** [review]
@smruti77 
Please push the sample yamls for below way of running vnic script

yaml for single vnic device (no backing device)  single_vnic_nobacking.yaml
yaml for single vnic with single backing device   single_vnic_single_backing.yaml
yaml for multiple vnic device with out backing device  multiple_vnic_nobacking.yaml
yaml for single vnic with multiple backing device      single_vnic_mulitple_backing.yaml

**Comment by smruti77** [comment]
> @smruti77
> Please push the sample yamls for below way of running vnic script
> 
> yaml for single vnic device (no backing device) single_vnic_nobacking.yaml
> yaml for single vnic with single backing device single_vnic_single_backing.yaml
> yaml for multiple vnic device with out backing device multiple_vnic_nobacking.yaml
> yaml for single vnic with multiple backing device single_vnic_mulitple_backing.yaml

@abdhaleegit  are you saying for separate yaml for all..? but yaml parameter is same, we are not changing anything.and i already mention the sample for single vnic and multiple vnic in readme file.
 
-- yaml for single vnic device (no backing device) single_vnic_nobacking.yaml
-- yaml for single vnic with multiple backing device single_vnic_mulitple_backing.yaml
these two are not handle  in the script. script will do for single vnic with backing and ,multiple vnic without backing.

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Review by narasimhan-v — APPROVED** [review]

**Pull request merged**
