### PR TITLE
yaml cleanup

### PR DESCRIPTION
**Pull request by narasimhan-v**
* Yaml empty parameters initialise with ""
* Reorganise to have static params before mux params
* Remove unnecessary indentations
* Remove some default params like interface and disk names

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@PraveenPenguin This is needed for https://github.com/open-power-host-os/tests/pull/228

**Comment by harish-24** [comment]
@narasimhan-v This change means, any value replaced with `""` will have the following impact.
Old yaml
```
$ cat memory/pmem_dm.py.data/pmem_dm.yaml
package:

in test:
PARAMS (key=package, path=*, default=distro) => 'distro'
```
With the proposed change
```
$ cat memory/pmem_dm.py.data/pmem_dm.yaml
package: ""

in test:
PARAMS (key=package, path=*, default=distro) => ''
```

Considering that, does this patch still hold good for all changed tests?

**Comment by narasimhan-v** [comment]
> @narasimhan-v This change means, any value replaced with `""` will have the following impact.
> Old yaml
> 
> ```
> $ cat memory/pmem_dm.py.data/pmem_dm.yaml
> package:
> 
> in test:
> PARAMS (key=package, path=*, default=distro) => 'distro'
> ```
> 
> With the proposed change
> 
> ```
> $ cat memory/pmem_dm.py.data/pmem_dm.yaml
> package: ""
> 
> in test:
> PARAMS (key=package, path=*, default=distro) => ''
> ```
> 
> Considering that, does this patch still hold good for all changed tests?

@harish-24 I am still working on that. Need to come up with a mechanism to make it work.

**Comment by PraveenPenguin** [comment]
> @PraveenPenguin This is needed for [open-power-host-os/tests#228](https://github.com/open-power-host-os/tests/pull/228)

sure, Not sure we need to change this here as based on the use case of user we should  not change the template

**Comment by harish-24** [comment]
@narasimhan-v Now that we are have conclusive evidence of `null` not being supported in Yaml file [here](https://github.com/avocado-framework/avocado/pull/4288/files) , how can we approach this next?

**Comment by harish-24** [comment]
@narasimhan-v WIth https://github.com/avocado-framework/avocado/pull/4329/ in place,we now have a unique way to defint `null` in yaml file. Can you please rebase this PR including this change?

**Comment by narasimhan-v** [comment]
@harish-24 Thanks for this.

Just for clarification, now `""` has to be replaced by `"null"`, right ?

**Comment by harish-24** [comment]
> @harish-24 Thanks for this.
> 
> Just for clarification, now `""` has to be replaced by `"null"`, right ?

Correct, "null" as a string.

**Comment by harish-24** [comment]
@narasimhan-v Any update on this?

**Comment by narasimhan-v** [comment]
> @narasimhan-v Any update on this?

I am planning to do this in a week's time, when couple of other yaml related patches are merged, to avoid conflicts.

**Comment by harish-24** [comment]
@narasimhan-v ping

**Comment by narasimhan-v** [comment]
Will get to it this week.

**Comment by narasimhan-v** [comment]
This is time consuming, I have completed around 40% of the files, will take a week more to get it done.

**Comment by PraveenPenguin** [comment]
@narasimhan-v can we work on this

**Comment by PraveenPenguin** [comment]
closing this as no activity quite long time

**Pull request closed without merging**
