### PR TITLE
Fixed nvme write command in nvmetest.py

### PR DESCRIPTION
**Pull request by narasimhan-v**
Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by apahim** [comment]
Hey @narasimhan-v, could you explain your commit in the commit message? Thank you.

**Comment by narasimhan-v** [comment]
@apahim Would you want me to edit commit message here ?

**Comment by apahim** [comment]
@narasimhan-v, in the commit itself. 
I don't care that much about the PR description. I mean, it helps, but the commit message should describe the issue and how you're solving it. I know we are not that picky about the commit messages so far, but I think we should start giving more attention to it.

**Comment by narasimhan-v** [comment]
@apahim Sure, I will

**Comment by narasimhan-v** [comment]
Created a new PR #32

**Pull request closed without merging**
