### PR TITLE
add dmesg utils module to lpm test

### PR DESCRIPTION
**Pull request by smruti77**
colletc dmesg error in the end of the test if any.

Signed-off-by: Bismruti Pattjoshi <bismruti@oc7660885027.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
JOB ID     : 817e2c5b818765916e67f139152f3375c9d99ce5
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2020-11-01T23.25-817e2c5/job.log
 (1/2) lpm.py:LPM.test_migrate;run-d785: PASS (342.70 s)
 (2/2) lpm.py:LPM.test_migrate_back;run-d785: PASS (340.40 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2020-11-01T23.25-817e2c5/results.html
JOB TIME   : 684.40 s

**Comment by narasimhan-v** [comment]
@smruti77 please upload job.log files

**Comment by smruti77** [comment]
[lpm.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5480513/lpm.log)

**Review by PraveenPenguin — APPROVED** [review]
LGTM

**Comment by smruti77** [comment]
JOB ID     : b59589faf2fac873cb5a001613e0102e5041c4f7
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-11-11T01.02-b59589f/job.log
 (1/2) lpm.py:LPM.test_migrate;run-d785: PASS (333.43 s)
 (2/2) lpm.py:LPM.test_migrate_back;run-d785: PASS (331.87 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-11-11T01.02-b59589f/results.html
JOB TIME   : 666.44 s

**Comment by smruti77** [comment]
[lpm_dmesg.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5522190/lpm_dmesg.log)

**Comment by smruti77** [comment]
fail log :-
JOB ID     : 346ec46439919434a11afbb79e03c16eed5348a5
JOB LOG    : /home/ioci/avocado-fvt-wrapper/results/job-2020-11-11T03.04-346ec46/job.log
 (1/2) lpm.py:LPM.test_migrate;run-e74c: FAIL: test failed,check dmesg log in debug log (517.91 s)
 (2/2) lpm.py:LPM.test_migrate_back;run-e74c: FAIL: test failed,check dmesg log in debug log (512.52 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/ioci/avocado-fvt-wrapper/results/job-2020-11-11T03.04-346ec46/results.html
JOB TIME   : 1039.40 s
[lpm.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5523110/lpm.log)

**Review by narasimhan-v — APPROVED** [review]

**Pull request merged**
