### PR TITLE
Script issue fixes for network.py

### PR DESCRIPTION
**Pull request by manvanthar**
Script issue fixes for network.py

Signed-off-by: Manvanthara Puttashankar <manvanth@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by manvanthar** [comment]
Superset fix in one patch compared to PR #1461 

1. In setup,  mtu was set before getting the value for mtu.  Fixed that!!
2. In setup, removed the redundency with ping check
3. In TearDown,  IP was cleared, followed by setting the MTU.  which used to fail the tests.
4. Fixed the yaml file to correctly reflect the root and password tags.
5. Fixed all the yaml to reflect similar parameters.

**Comment by manvanthar** [comment]
avocado run network_test.py:NetworkTest.test_ping -m network_test.py.data/network_test.yaml 
Failed to load plugin from module "avocado_runner_vm": DistributionNotFound(Requirement.parse('libvirt-python'), None) :
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-72.0-py3.6.egg/avocado/core/extension_manager.py", line 62, in __init__
    plugin = ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2317, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2340, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)

JOB ID     : dddc02c55c6bd8037ff5eeb7cebfe990b7b46237
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2019-11-27T21.33-dddc02c/job.log
 (1/9) network_test.py:NetworkTest.test_ping;1500-a9d2: PASS (7.84 s)
 (2/9) network_test.py:NetworkTest.test_ping;2000-1795: PASS (8.27 s)
 (3/9) network_test.py:NetworkTest.test_ping;3000-92ee: PASS (8.21 s)
 (4/9) network_test.py:NetworkTest.test_ping;4000-7d0d: PASS (8.13 s)
 (5/9) network_test.py:NetworkTest.test_ping;5000-f84a: PASS (8.23 s)
 (6/9) network_test.py:NetworkTest.test_ping;6000-9cb9: PASS (8.24 s)
 (7/9) network_test.py:NetworkTest.test_ping;7000-87c8: PASS (8.18 s)
 (8/9) network_test.py:NetworkTest.test_ping;8000-3eab: PASS (8.22 s)
 (9/9) network_test.py:NetworkTest.test_ping;9000-4f6b: PASS (8.28 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 73.98 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2019-11-27T21.33-dddc02c/results.html

**Comment by manvanthar** [comment]
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3897717/job.log)

**Comment by narasimhan-v** [comment]
@vaishnavibhat @smruti77 reviews please

**Comment by vaishnavibhat** [comment]
Updated the above changes in the PR https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1431

**Comment by manvanthar** [comment]
thanks .. CLosing this PR as it now tracked via PR #1431

**Pull request closed without merging**
