### PR TITLE
MOFED ISO download from https path

### PR DESCRIPTION
**Pull request by PavamanSubramaniyam**
Downloading the MOFED ISO matching the distro release installed

### CODE REVIEW

**Comment by PavamanSubramaniyam** [comment]
# avocado run --max-parallel-tasks=1 mofed_install_test.py -m mofed_install_test.py.data/mofed_install_test.yaml
Fetching asset from mofed_install_test.py:MOFEDInstallTest.test
JOB ID     : 707e41d3d1d0f8ac2b98826be486ae5afb171609
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-03-25T04.48-707e41d/job.log
 (01/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-all-Parameters-d655: STARTED
 (01/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-all-Parameters-d655: CANCEL: option --all --post-start-delay 15 --pre-install-opensm "echo testpre" --post-install-mstflint "echo testpost" not supported with this MOFED (2.07 s)
 (02/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-32-bit-Parameters-a9b9: STARTED
 (02/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-32-bit-Parameters-a9b9: PASS (798.54 s)
 (03/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-without_32-bit-Parameters-1cf9: STARTED
 (03/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-without_32-bit-Parameters-1cf9: PASS (706.17 s)
 (04/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-skip-distro-check-Parameters-2144: STARTED
 (04/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-skip-distro-check-Parameters-2144: PASS (722.96 s)
 (05/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-skip-kmp-verify-Parameters-71c8: STARTED
 (05/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-skip-kmp-verify-Parameters-71c8: PASS (724.16 s)
 (06/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-force-fw-update-Parameters-76bf: STARTED
 (06/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-force-fw-update-Parameters-76bf: PASS (702.26 s)
 (07/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-disable-kmp_skip-distro-check-Parameters-ad34: STARTED
 (07/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-disable-kmp_skip-distro-check-Parameters-ad34: PASS (723.43 s)
 (08/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-dpdk-Parameters-e310: STARTED
 (08/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-dpdk-Parameters-e310: PASS (672.33 s)
 (09/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-opensm-Parameters-368a: STARTED
 (09/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-opensm-Parameters-368a: PASS (724.17 s)
 (10/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-hpc-Parameters-755e: STARTED
 (10/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-hpc-Parameters-755e: PASS (702.94 s)
 (11/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-basic-Parameters-8995: STARTED
 (11/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-basic-Parameters-8995: PASS (689.44 s)
 (12/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-mlnxlibs-Parameters-dcf1: STARTED
 (12/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-mlnxlibs-Parameters-dcf1: CANCEL: option --mlnx-libs not supported with this MOFED (2.07 s)
 (13/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-msm-Parameters-11c1: STARTED
 (13/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-msm-Parameters-11c1: CANCEL: option --msm not supported with this MOFED (2.05 s)
 (14/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-p-Parameters-65d9: STARTED
 (14/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-p-Parameters-65d9: PASS (6.12 s)
 (15/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-kernel-Parameters-cf1b: STARTED
 (15/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-kernel-Parameters-cf1b: CANCEL: option s /lib/modules/`uname -r`/build -k `uname -r`  umad-dev-na  -enable-affinity not supported with this MOFED (2.05 s)
 (16/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-umad-dev-rw-Parameters-ad2c: STARTED
 (16/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-umad-dev-rw-Parameters-ad2c: PASS (723.75 s)
 (17/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-umad-dev-na-Parameters-b157: STARTED
 (17/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-umad-dev-na-Parameters-b157: PASS (725.74 s)
 (18/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-distro-Parameters-5d38: STARTED
 (18/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-distro-Parameters-5d38: CANCEL: option -U --distro `cat distro` --with-vma not supported with this MOFED (2.03 s)
 (19/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-fw-update-only-Parameters-d029: STARTED
 (19/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-fw-update-only-Parameters-d029: PASS (558.36 s)
 (20/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-check-deps-only-Parameters-d1f3: STARTED
 (20/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-check-deps-only-Parameters-d1f3: PASS (5.51 s)
 (21/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-bluefield-Parameters-8b10: STARTED
 (21/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-bluefield-Parameters-8b10: PASS (722.17 s)
 (22/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-libdisni-Parameters-2b69: STARTED
 (22/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-libdisni-Parameters-2b69: CANCEL: option --with-libdisni not supported with this MOFED (2.05 s)
 (23/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-guest-Parameters-1da1: STARTED
 (23/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-guest-Parameters-1da1: PASS (680.40 s)
 (24/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-hypervisor-Parameters-4697: STARTED
 (24/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-hypervisor-Parameters-4697: PASS (701.78 s)
 (25/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-kernel-only_without-fw-update-Parameters-c3d2: STARTED
 (25/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-kernel-only_without-fw-update-Parameters-c3d2: PASS (675.59 s)
 (26/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-ofed-conf-Parameters-694f: STARTED
 (26/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-ofed-conf-Parameters-694f: PASS (674.19 s)
 (27/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-with-kmp-Parameters-c658: STARTED
 (27/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-with-kmp-Parameters-c658: PASS (1752.57 s)
 (28/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-with-nvmf-Parameters-e1e6: STARTED
 (28/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-with-nvmf-Parameters-e1e6: PASS (734.28 s)
 (29/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-with-nfsrdma-Parameters-77a6: STARTED
 (29/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-with-nfsrdma-Parameters-77a6: PASS (723.71 s)
 (30/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-without-nfsrdma-Parameters-53c0: STARTED
 (30/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-without-nfsrdma-Parameters-53c0: PASS (724.86 s)
 (31/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-add-kernel-support-Parameters-e70e: STARTED
 (31/31) mofed_install_test.py:MOFEDInstallTest.test;run-Options-add-kernel-support-Parameters-e70e: PASS (679.14 s)
RESULTS    : PASS 25 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 6
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-03-25T04.48-707e41d/results.html
JOB TIME   : 17341.17 s

**Comment by PavamanSubramaniyam** [comment]
I have attached the complete result debug logs tar ball to the Jira task for both RHEL and SLES distro's.

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Comment by abdhaleegit** [comment]
@PavamanSubramaniyam make sure the full iso link still works the legacy way

**Pull request merged**
