### PR TITLE
Added network statistics, bigping, lro, gro and network interface

### PR DESCRIPTION
**Pull request by prudmiry**
test the network statastics by sending data packets through interface,
test interface with different mtu sizes, test lro, test gro,
test network interface

Signed-off-by: prudhvi <mprudhvi@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@prudmiry can you please attach job log in PR

Regards
Praveen

**Comment by prudmiry** [comment]
[net_data_job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/468977/net_data_job.txt)
[net_iface_job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/468978/net_iface_job.txt)

**Comment by PraveenPenguin** [comment]
@prudmiry please raise two different PR as you included two test 

Regards
praveen

**Comment by PraveenPenguin** [comment]
next version  PR #36 raised

**Pull request closed without merging**
