### PR TITLE
[Back-port] Removing btrfs specific tests from py2-lts branch

### PR DESCRIPTION
**Pull request by manvanthar**
Commenting out old btrfs specific tests from py2-lts branch to reduce the number of invalid tests.

Signed-off-by: Manvanthara B Puttashankar <manvanth@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@PraveenPenguin Your thoughts please

**Comment by manvanthar** [comment]
ok @narasimhan-v ,  would this logic do?

                if fstype == 'btrfs':
                    if distro.detect().name == 'rhel':
                        self.skip("btrfs is not supported for this Linux Distro")

**Comment by PraveenPenguin** [comment]
> @PraveenPenguin Your thoughts please

yes, we should cancel test on that case even @manvanthar also commented with the solution as well :)

**Comment by narasimhan-v** [comment]
@manvanthar @PraveenPenguin In cases like these where it is not supported, we do a `self.cancel()`. Need your thoughts on which is more preferred and why please.

**Comment by narasimhan-v** [comment]
@manvanthar Sorry, got confused on older and newer proposed approach.

Newer approach of version and release looks fine with me too.

**Comment by narasimhan-v** [comment]
@manvanthar 

```
>>> from avocado.utils import distro
>>> dir(distro)
['AmazonLinuxProbe', 'CentosProbe', 'DebianProbe', 'FedoraProbe', 'LinuxDistro', 'Probe', 'REGISTERED_PROBES', 'RedHatProbe', 'SUSEProbe', 'Spec', 'UNKNOWN_DISTRO', 'UNKNOWN_DISTRO_ARCH', 'UNKNOWN_DISTRO_NAME', 'UNKNOWN_DISTRO_RELEASE', 'UNKNOWN_DISTRO_VERSION', 'UbuntuProbe', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'detect', 'os', 're', 'register_probe']
>>> dir(distro.detect)
['__annotations__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
>>> distro.detect()
<LinuxDistro: name=rhel, version=8, release=1, arch=ppc64le>
>>> distro.detect().name
'rhel'
>>> distro.detect().version
'8'
>>> distro.detect().release
'1'
>>> distro.detect().arch
'ppc64le'
>>> 
```

**Comment by manvanthar** [comment]
new PR#1336

**Pull request closed without merging**
