### PR TITLE
fixed htx for ip restore in host and peer

### PR DESCRIPTION
**Pull request by smruti77**
add a function for ip config to original ip address
for host and peer after htx run.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>
Reported-by Abdul Haleem abdhalee@linux.vnet.ibm.com

### CODE REVIEW

**Comment by smruti77** [comment]
[htx_fix.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4655051/htx_fix.log)

**Comment by narasimhan-v** [comment]
@smruti77 please run a test before and a test after htx and upload those logs also

**Comment by smruti77** [comment]
> @smruti77 please run a test before and a test after htx and upload those logs also

@narasimhan-v before..? before the changes or what.?

**Comment by narasimhan-v** [comment]
with this fix, run:

test1
htx
test3

**Comment by smruti77** [comment]
ok

**Comment by smruti77** [comment]
[htx.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4661635/htx.log)
[htx_a_multicast.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4661636/htx_a_multicast.log)
[htx_b_ethtool.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4661637/htx_b_ethtool.log)

**Comment by narasimhan-v** [comment]
@smruti77 Just for my reference, this makes tests before and after htx run fine.

**Comment by narasimhan-v** [comment]
@vaishnavibhat any review comments ?

**Comment by smruti77** [comment]
[htx_nw.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4679963/htx_nw.log)

**Comment by narasimhan-v** [comment]
@smruti77 would need log of test before and after htx please, with latest code

**Comment by smruti77** [comment]
[a_htx_multicast.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4680264/a_htx_multicast.log)
[b_htx_ethtool.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4680267/b_htx_ethtool.log)
[htx_fx.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4680282/htx_fx.log)

**Pull request merged**
