### PR TITLE
This submission is mainly for bench_movePages.c file modification, ch…

### PR DESCRIPTION
**Pull request by deepin12**
…ange line 110 10 to 3, mainly for 64K adaptation

### CODE REVIEW

**Comment by deepin12** [comment]
@PraveenPenguin Because of the source code update, I could not use git commit --amend command to modify the commit information, so I resubmitted the patch. All the information is in English, please help to review it again, thank you very much

**Comment by deepin12** [comment]
The log is as follows:
If the system size is 64K, setting the value to 10 will inevitably cause the execution./ bench_movePages -n 100 to fail

root@uos-PC:/home/uos/avocado-misc-tests/memory/numa_test.py.data# cat bench_movepages.c |grep strtoul
nr_pages = strtoul(optarg, NULL, 10);
root@uos-PC:/home/uos/avocado-misc-tests/memory/numa_test.py.data# ./bench_movepages -n 100
src node = 0 and dest node = 1 pages -32768
Failed mmap

If the system size is 64 KB, set this parameter to 3./ bench_movePages -n 100 is feasible
root@uos-PC:/home/uos/avocado-misc-tests/memory/numa_test.py.data# cat bench_movepages.c |grep strtoul
nr_pages = strtoul(optarg, NULL, 3);
root@uos-PC:/home/uos/avocado-misc-tests/memory/numa_test.py.data# ./bench_movepages -n 100
src node = 0 and dest node = 1 pages 8192
THP migration time(seconds) (thp_pages 8192 non_thp_pages = 0) = 0.098245
Base migration time(seconds) (thp_pages 0 non_thp_pages = 8192) = 0.102195

**Comment by PraveenPenguin** [comment]
Geetika  can you please review this Patch

**Comment by kvaneesh** [comment]
I guess the confusion is w.r.t input page count. That is the number of hugepages -n <nr_hugepages> . So when you say -n 100, the request is to work with 100 hugepages.

**Comment by deepin12** [comment]
@kvaneesh Sorry, I don't quite understand what you mean. This 100 is a fixed value in NUMA_ test. In py file, when the memory page of the system is 64K, it will inevitably lead to failure. At present, many operating systems have adapted 64K

**Comment by PraveenPenguin** [comment]
> @kvaneesh Sorry, I don't quite understand what you mean. This 100 is a fixed value in NUMA_ test. In py file, when the memory page of the system is 64K, it will inevitably lead to failure. At present, many operating systems have adapted 64K

@deepin12 what @kvaneesh is saying you can always overwrite nr_pages from ymal file  `https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/memory/numa_test.py.data/numa_test.yaml`  , and for you change `strtoul`  should be base `10` , please give try with a number of pages which is relevant on your environment  i feel it shoule work , if still don't have any luck please update us

**Comment by deepin12** [comment]
@PraveenPenguin Thank you for answering my question. Do you mean it is caused by our system itself? I have tried on CentOS system, and there are the same problems. I have also tried to modify NR in yaml file_ Page, but the result is still fail

**Comment by PraveenPenguin** [comment]
> @PraveenPenguin Thank you for answering my question. Do you mean it is caused by our system itself? I have tried on CentOS system, and there are the same problems. I have also tried to modify NR in yaml file_ Page, but the result is still fail

i feel it need to do with nr pages , may be try with lower number and see it this work

**Comment by deepin12** [comment]
OK, I'll try again, thank you

**Comment by PraveenPenguin** [comment]
closing this, @deepin12 if still facing an issue feel free to reopen

**Pull request closed without merging**
