### PR TITLE
Defaulting disk and dir yaml parameters to null

### PR DESCRIPTION
**Pull request by AYUSHJAIN951**
Changing disk and dir parameters to be null rather than empty strings as it produces errors by not considering default dir parameter provided. Making /mnt as default dir parameter in following tests rather than none.
And fixing styling issues in following testcases.

Signed-off-by: Ayush Jain [ayush.jain3@amd.com](mailto:ayush.jain3@amd.com)

### CODE REVIEW

**Comment by AYUSHJAIN951** [comment]
@PraveenPenguin  @Naresh-ibm  Please review this PR this is on latest tree.

**Comment by PraveenPenguin** [comment]
PR looks good to me @narasimhan-v looking for help as one concern this patch impacts older eco systems as older use cases require a major change can you please check and provide your view so we can come on same ground

**Review by narasimhan-v — COMMENTED** [review]
@AYUSHJAIN951 code looks good to me, please provide run logs

**Comment by narasimhan-v** [comment]
@PraveenPenguin Sure, I think once we validate run logs, we are good to go

**Comment by AYUSHJAIN951** [comment]
[IO_Disk_dir.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/10836463/IO_Disk_dir.log)
Logs

**Comment by AYUSHJAIN951** [comment]
@PraveenPenguin can you validate logs and approve ahead

**Comment by PraveenPenguin** [comment]
@Naresh-ibm can you please ACK this PR

**Review by Naresh-ibm — APPROVED** [review]
@AYUSHJAIN951  Thanks for changes

**Comment by Naresh-ibm** [comment]
@PraveenPenguin @narasimhan-v if you don't have any more comments, I can merge this.

**Review by PraveenPenguin — APPROVED** [review]
LGTM

**Comment by Naresh-ibm** [comment]
@AYUSHJAIN951 I could see few test failures and few of them with Missing disk.
is this something in your environment or a script issue with the changes you have made?

Please attach the working logs after your changes.
The above doesn't logs doesn't convey that you have made some changes and they are working.

**Review by Naresh-ibm — CHANGES_REQUESTED** [review]
please attach the working logs after your changes

**Comment by AYUSHJAIN951** [comment]
[job_log_fio.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/10880789/job_log_fio.log)
Here is a snippet of the fio log using my patch 
@Naresh-ibm 
About the Missing Disk: That occurs when Disk is not provided by the user

**Comment by Naresh-ibm** [comment]
> [job_log_fio.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/10880817/job_log_fio.log)
> 
> Here is a snippet of the fio log using my patch @Naresh-ibm About the Missing Disk: That occurs when Disk is not provided by the user

@AYUSHJAIN951 In that case what are you trying to achieve here with your piece of code. 
if you don't give the disk here, then test will 100% gets cancelled with the "Disk Missing " Message.
And if you want to dir is not given then why are you including the disk check in your code.
you could do it in straight way like,

if self.dir is None:
    self.dir =  self.workdir

Please check your code.

#if self.dir is None using using self.workdir as self.dir
        if self.disk:
            if not self.dir:
                self.dir = self.workdir
        else:
            self.dir = self.workdir


Note : These test cases are mainly intended for a block devices and  may not be useful to run on only directory.

Please define the exact requirement that, what are you trying to achieve here.

**Comment by AYUSHJAIN951** [comment]
Closing this PR, will be opening another PR with a better approach to solve this issue.
Thanks for review @Naresh-ibm @PraveenPenguin  @narasimhan-v

**Pull request closed without merging**
