### PR TITLE
changed vnic test by importing hosts.py and interface.py

### PR DESCRIPTION
**Pull request by smruti77**
chnaged ping_check and add_ipaddr by importing module.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
[network_virtualization.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4413135/network_virtualization.log)
[Network_virtualization_driver_bind.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4413137/Network_virtualization_driver_bind.log)

**Comment by narasimhan-v** [comment]
@abdhaleegit review please

**Comment by abdhaleegit** [comment]
@smruti77 Can you run the new code for 
1. single vNIC device 
2. Multiple vNIC device 

and paste the logs

**Comment by smruti77** [comment]
JOB ID     : 687403d958cc0d0a53ebd95bf9fc97e99247914c
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-04-09T01.54-687403d/job.log
 (01/10) network_virtualization.py:NetworkVirtualization.test_add;run-0b22: PASS (58.78 s)
 (02/10) network_virtualization.py:NetworkVirtualization.test_backingdevadd;run-0b22: CANCEL: this test is not needed (41.65 s)
 (03/10) network_virtualization.py:NetworkVirtualization.test_hmcfailover;run-0b22: CANCEL: this test is not needed (41.46 s)
 (04/10) network_virtualization.py:NetworkVirtualization.test_unbindbind;run-0b22: PASS (139.33 s)
 (05/10) network_virtualization.py:NetworkVirtualization.test_clientfailover;run-0b22: CANCEL: this test is not needed (40.73 s)
 (06/10) network_virtualization.py:NetworkVirtualization.test_vnic_auto_failover;run-0b22: CANCEL: this test is not needed (41.59 s)
 (07/10) network_virtualization.py:NetworkVirtualization.test_rmdev_viosfailover;run-0b22: CANCEL: this test is not needed (41.55 s)
 (08/10) network_virtualization.py:NetworkVirtualization.test_vnic_dlpar;run-0b22: PASS (127.67 s)
 (09/10) network_virtualization.py:NetworkVirtualization.test_backingdevremove;run-0b22: CANCEL: this test is not needed (41.16 s)
 (10/10) network_virtualization.py:NetworkVirtualization.test_remove;run-0b22: PASS (56.48 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 6
JOB TIME   : 630.87 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-04-09T01.54-687403d/results.html

**Comment by smruti77** [comment]
@abdhaleegit for single vnic already i paste log.

**Comment by abdhaleegit** [comment]
@narasimhan-v  LGTM.. please merge

**Pull request merged**
