### PR TITLE
added ip configuration for both host and peer interface in htx

### PR DESCRIPTION
**Pull request by smruti77**
mnually set ip if pingum failed in htx test.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
[htx_ip.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4220027/htx_ip.log)

**Comment by smruti77** [comment]
[htx.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4220038/htx.log)

**Comment by narasimhan-v** [comment]
@manvanthar Review please

**Comment by manvanthar** [comment]
@smruti77   As discussed please handle the IP changes between yaml and HTX.   

Would like to see the successfull runs.

**Comment by smruti77** [comment]
> @smruti77 As discussed please handle the IP changes between yaml and HTX.
> 
> Would like to see the successfull runs.

ok

**Comment by smruti77** [comment]
[htxf.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4234349/htxf.log)

**Comment by smruti77** [comment]
@manvanthar now its working fine. review it.

**Comment by manvanthar** [comment]
Perfect thank you.  No further comments from my end on HTX

Over to Narasimhans review comments.

**Pull request merged**
