### PR TITLE
Fixing failed connecting to peer issue

### PR DESCRIPTION
**Pull request by PavamanSubramaniyam**
Making the remote peer connection once the host interfaces are up

Signed-off-by: Pavaman Subramaniyam <pavsubra@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by PavamanSubramaniyam** [comment]
Executed the tests with the above commit changes to the dapl.py script and pasting the results.

# avocado run --test-runner runner dapl.py -m dapl.py.data/dapl_roce.yaml
JOB ID     : 472f967fb74396202bf20977847093e06125fc25
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2022-10-17T03.58-472f967/job.log
 (01/45) dapl.py:dapl.test;run-Test-options-first-mtu-1500-parameters-a4e4: PASS (11.77 s)
 (02/45) dapl.py:dapl.test;run-Test-options-first-mtu-2000-parameters-4aec: PASS (12.75 s)
 (03/45) dapl.py:dapl.test;run-Test-options-first-mtu-3000-parameters-ea1a: PASS (12.76 s)
 (04/45) dapl.py:dapl.test;run-Test-options-first-mtu-4000-parameters-f960: PASS (12.79 s)
 (05/45) dapl.py:dapl.test;run-Test-options-first-mtu-5000-parameters-365a: PASS (12.79 s)
 (06/45) dapl.py:dapl.test;run-Test-options-first-mtu-6000-parameters-c0aa: PASS (12.72 s)
 (07/45) dapl.py:dapl.test;run-Test-options-first-mtu-7000-parameters-276d: PASS (12.82 s)
 (08/45) dapl.py:dapl.test;run-Test-options-first-mtu-8000-parameters-06f1: PASS (12.83 s)
 (09/45) dapl.py:dapl.test;run-Test-options-first-mtu-9000-parameters-aee3: PASS (12.71 s)
 (10/45) dapl.py:dapl.test;run-Test-options-second-mtu-1500-parameters-f0da: PASS (11.82 s)
 (11/45) dapl.py:dapl.test;run-Test-options-second-mtu-2000-parameters-0a60: PASS (12.71 s)
 (12/45) dapl.py:dapl.test;run-Test-options-second-mtu-3000-parameters-fb2c: PASS (12.83 s)
 (13/45) dapl.py:dapl.test;run-Test-options-second-mtu-4000-parameters-c104: PASS (12.78 s)
 (14/45) dapl.py:dapl.test;run-Test-options-second-mtu-5000-parameters-f5af: PASS (12.71 s)
 (15/45) dapl.py:dapl.test;run-Test-options-second-mtu-6000-parameters-775f: PASS (12.74 s)
 (16/45) dapl.py:dapl.test;run-Test-options-second-mtu-7000-parameters-cce4: PASS (12.71 s)
 (17/45) dapl.py:dapl.test;run-Test-options-second-mtu-8000-parameters-5dbe: PASS (12.88 s)
 (18/45) dapl.py:dapl.test;run-Test-options-second-mtu-9000-parameters-d771: PASS (12.73 s)
 (19/45) dapl.py:dapl.test;run-Test-options-third-mtu-1500-parameters-6cf9: PASS (11.76 s)
 (20/45) dapl.py:dapl.test;run-Test-options-third-mtu-2000-parameters-95a5: PASS (12.73 s)
 (21/45) dapl.py:dapl.test;run-Test-options-third-mtu-3000-parameters-6bdd: PASS (12.74 s)
 (22/45) dapl.py:dapl.test;run-Test-options-third-mtu-4000-parameters-f29b: PASS (12.71 s)
 (23/45) dapl.py:dapl.test;run-Test-options-third-mtu-5000-parameters-eb51: PASS (12.69 s)
 (24/45) dapl.py:dapl.test;run-Test-options-third-mtu-6000-parameters-7fca: PASS (12.75 s)
 (25/45) dapl.py:dapl.test;run-Test-options-third-mtu-7000-parameters-253d: PASS (12.73 s)
 (26/45) dapl.py:dapl.test;run-Test-options-third-mtu-8000-parameters-43a9: PASS (12.74 s)
 (27/45) dapl.py:dapl.test;run-Test-options-third-mtu-9000-parameters-f7da: PASS (12.80 s)
 (28/45) dapl.py:dapl.test;run-Test-options-fourth-mtu-1500-parameters-93fb: PASS (11.91 s)
 (29/45) dapl.py:dapl.test;run-Test-options-fourth-mtu-2000-parameters-a560: PASS (12.67 s)
 (30/45) dapl.py:dapl.test;run-Test-options-fourth-mtu-3000-parameters-347f: PASS (12.80 s)
 (31/45) dapl.py:dapl.test;run-Test-options-fourth-mtu-4000-parameters-aba4: PASS (12.73 s)
 (32/45) dapl.py:dapl.test;run-Test-options-fourth-mtu-5000-parameters-1418: PASS (12.82 s)
 (33/45) dapl.py:dapl.test;run-Test-options-fourth-mtu-6000-parameters-09c0: PASS (12.78 s)
 (34/45) dapl.py:dapl.test;run-Test-options-fourth-mtu-7000-parameters-312a: PASS (12.70 s)
 (35/45) dapl.py:dapl.test;run-Test-options-fourth-mtu-8000-parameters-7e49: PASS (12.82 s)
 (36/45) dapl.py:dapl.test;run-Test-options-fourth-mtu-9000-parameters-0fb9: PASS (12.81 s)
 (37/45) dapl.py:dapl.test;run-Test-options-fifth-mtu-1500-parameters-b005: PASS (6.76 s)
 (38/45) dapl.py:dapl.test;run-Test-options-fifth-mtu-2000-parameters-12a9: PASS (7.71 s)
 (39/45) dapl.py:dapl.test;run-Test-options-fifth-mtu-3000-parameters-ad16: PASS (7.71 s)
 (40/45) dapl.py:dapl.test;run-Test-options-fifth-mtu-4000-parameters-fc68: PASS (8.65 s)
 (41/45) dapl.py:dapl.test;run-Test-options-fifth-mtu-5000-parameters-109c: PASS (7.70 s)
 (42/45) dapl.py:dapl.test;run-Test-options-fifth-mtu-6000-parameters-3a24: PASS (7.75 s)
 (43/45) dapl.py:dapl.test;run-Test-options-fifth-mtu-7000-parameters-2137: PASS (7.77 s)
 (44/45) dapl.py:dapl.test;run-Test-options-fifth-mtu-8000-parameters-ff9d: PASS (7.77 s)
 (45/45) dapl.py:dapl.test;run-Test-options-fifth-mtu-9000-parameters-b3c7: PASS (7.73 s)
RESULTS    : PASS 45 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2022-10-17T03.58-472f967/results.html
JOB TIME   : 540.10 s

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Review by Naresh-ibm — APPROVED** [review]
LGTM

**Review by vaishnavibhat — CHANGES_REQUESTED** [review]
@PavamanSubramaniyam 
Can we have the wait() function incorporated in case there is a timing issue seen during ssh session ? 
if not wait.wait_for(self.session.connect, timeout=30):
            self.fail("Failed connecting to peer")

**Comment by PavamanSubramaniyam** [comment]
@vaishnavibhat 
In this case of dapl.py tests, in the setup the ssh connection to the peer interfaces are tried even before the interfaces of the adapters on the host side are not assigned the private ip address and the corresponding links are also not made up.
So, once the interfaces on the host side are configured and link made up, then we need to establish the connection to the peer interfaces.

**Pull request merged**
