### PR TITLE
smartctl: works on single disk and skip if logical disk

### PR DESCRIPTION
**Pull request by abdhaleegit**
smartctl do not support logical disks and also it requires only single input device to test. so this patch will cancel test if it is logical device and cleanup yaml

### CODE REVIEW

**Comment by abdhaleegit** [comment]
for disk /dev/mapper/mpathb
```
avocado run smartctl.py -m smartctl.py.data/smartctl.yaml --max-parallel-tasks=1
JOB ID     : 67c39f2a60e5a038dc2a1a2647ce3bb54373c628
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2023-03-08T07.39-67c39f2/job.log
 (01/29) smartctl.py:SmartctlTest.test;run-Options-self_test-7cd2: STARTED
 (01/29) smartctl.py:SmartctlTest.test;run-Options-self_test-7cd2: CANCEL: unsupported on logical device (0.53 s)
 (02/29) smartctl.py:SmartctlTest.test;run-Options-info-ad6f: STARTED
 (02/29) smartctl.py:SmartctlTest.test;run-Options-info-ad6f: CANCEL: unsupported on logical device (0.50 s)
 (03/29) smartctl.py:SmartctlTest.test;run-Options-device_setting-289b: STARTED
 (03/29) smartctl.py:SmartctlTest.test;run-Options-device_setting-289b: CANCEL: unsupported on logical device (0.50 s)
```
for disk /dev/sdc
```
 (01/29) smartctl.py:SmartctlTest.test;run-Options-self_test-de5f: STARTED
 (01/29) smartctl.py:SmartctlTest.test;run-Options-self_test-de5f: FAIL: Smartctl option --test=long FAILS (0.52 s)
 (02/29) smartctl.py:SmartctlTest.test;run-Options-info-f028: STARTED
 (02/29) smartctl.py:SmartctlTest.test;run-Options-info-f028: PASS (0.49 s)
 (03/29) smartctl.py:SmartctlTest.test;run-Options-device_setting-b751: STARTED
 (03/29) smartctl.py:SmartctlTest.test;run-Options-device_setting-b751: FAIL: Smartctl option -s on FAILS (0.52 s)
 (04/29) smartctl.py:SmartctlTest.test;run-Options-scan_drives-befa: STARTED
 (04/29) smartctl.py:SmartctlTest.test;run-Options-scan_drives-befa: PASS (0.50 s)
 (05/29) smartctl.py:SmartctlTest.test;run-Options-scan_drives_open-eddc: STARTED
 (05/29) smartctl.py:SmartctlTest.test;run-Options-scan_drives_open-eddc: PASS (0.50 s)
 (06/29) smartctl.py:SmartctlTest.test;run-Options-quietmode-576d: STARTED
 (06/29) smartctl.py:SmartctlTest.test;run-Options-quietmode-576d: PASS (0.52 s)
 (07/29) smartctl.py:SmartctlTest.test;run-Options-bad_checksum-a215: STARTED
 (07/29) smartctl.py:SmartctlTest.test;run-Options-bad_checksum-a215: PASS (0.50 s)
 (08/29) smartctl.py:SmartctlTest.test;run-Options-report_transaction-92fe: STARTED
 (08/29) smartctl.py:SmartctlTest.test;run-Options-report_transaction-92fe: PASS (0.50 s)
 (09/29) smartctl.py:SmartctlTest.test;run-Options-check_mode-5737: STARTED
 (09/29) smartctl.py:SmartctlTest.test;run-Options-check_mode-5737: PASS (0.51 s)
 (10/29) smartctl.py:SmartctlTest.test;run-Options-automatic_offline_off-cc7f: STARTED
 (10/29) smartctl.py:SmartctlTest.test;run-Options-automatic_offline_off-cc7f: PASS (0.50 s)
 (11/29) smartctl.py:SmartctlTest.test;run-Options-automatic_offline_on-a531: STARTED
 (11/29) smartctl.py:SmartctlTest.test;run-Options-automatic_offline_on-a531: PASS (0.50 s)
 (12/29) smartctl.py:SmartctlTest.test;run-Options-autosave_attribute_off-5146: STARTED
 (12/29) smartctl.py:SmartctlTest.test;run-Options-autosave_attribute_off-5146: FAIL: Smartctl option -S off FAILS (0.54 s)
 (13/29) smartctl.py:SmartctlTest.test;run-Options-autosave_attribute_on-a4d8: STARTED
 (13/29) smartctl.py:SmartctlTest.test;run-Options-autosave_attribute_on-a4d8: PASS (0.51 s)
 (14/29) smartctl.py:SmartctlTest.test;run-Options-tolerance_opt1-6ccc: STARTED
 (14/29) smartctl.py:SmartctlTest.test;run-Options-tolerance_opt1-6ccc: FAIL: Smartctl option --smart=off -T verypermissive FAILS (0.54 s)
 (15/29) smartctl.py:SmartctlTest.test;run-Options-tolerance_opt2-c8e8: STARTED
 (15/29) smartctl.py:SmartctlTest.test;run-Options-tolerance_opt2-c8e8: FAIL: Smartctl option --smart=on -T permissive FAILS (0.54 s)
 (16/29) smartctl.py:SmartctlTest.test;run-Options-tolerance_opt3-dc03: STARTED
 (16/29) smartctl.py:SmartctlTest.test;run-Options-tolerance_opt3-dc03: FAIL: Smartctl option --smart=on -T normal FAILS (0.54 s)
 (17/29) smartctl.py:SmartctlTest.test;run-Options-tolerance_opt4-1a75: STARTED
 (17/29) smartctl.py:SmartctlTest.test;run-Options-tolerance_opt4-1a75: FAIL: Smartctl option --smart=on -T conservative FAILS (0.53 s)
 (18/29) smartctl.py:SmartctlTest.test;run-Options-print_selftest_quietmode-8f3a: STARTED
 (18/29) smartctl.py:SmartctlTest.test;run-Options-print_selftest_quietmode-8f3a: FAIL: Smartctl option --attributes --log=selftest --quietmode=errorsonly FAILS (0.52 s)
 (19/29) smartctl.py:SmartctlTest.test;run-Options-captive_mode-0c32: STARTED
 (19/29) smartctl.py:SmartctlTest.test;run-Options-captive_mode-0c32: PASS (0.50 s)
 (20/29) smartctl.py:SmartctlTest.test;run-Options-offlineautotests-16ee: STARTED
 (20/29) smartctl.py:SmartctlTest.test;run-Options-offlineautotests-16ee: FAIL: Smartctl option --smart=on --offlineauto=on --saveauto=on FAILS (0.53 s)
 (21/29) smartctl.py:SmartctlTest.test;run-Options-format_opt1-e698: STARTED
 (21/29) smartctl.py:SmartctlTest.test;run-Options-format_opt1-e698: PASS (0.50 s)
 (22/29) smartctl.py:SmartctlTest.test;run-Options-print_format_opt1-649c: STARTED
 (22/29) smartctl.py:SmartctlTest.test;run-Options-print_format_opt1-649c: FAIL: Smartctl option --all FAILS (0.53 s)
 (23/29) smartctl.py:SmartctlTest.test;run-Options-format_opt2-e767: STARTED
 (23/29) smartctl.py:SmartctlTest.test;run-Options-format_opt2-e767: PASS (0.50 s)
 (24/29) smartctl.py:SmartctlTest.test;run-Options-print_format_opt2-ee9b: STARTED
 (24/29) smartctl.py:SmartctlTest.test;run-Options-print_format_opt2-ee9b: FAIL: Smartctl option -x FAILS (0.53 s)
 (25/29) smartctl.py:SmartctlTest.test;run-Options-Health-38fd: STARTED
 (25/29) smartctl.py:SmartctlTest.test;run-Options-Health-38fd: PASS (0.50 s)
 (26/29) smartctl.py:SmartctlTest.test;run-Options-capabilities-c53a: STARTED
 (26/29) smartctl.py:SmartctlTest.test;run-Options-capabilities-c53a: PASS (0.50 s)
 (27/29) smartctl.py:SmartctlTest.test;run-Options-device_log-8302: STARTED
 (27/29) smartctl.py:SmartctlTest.test;run-Options-device_log-8302: PASS (0.51 s)
 (28/29) smartctl.py:SmartctlTest.test;run-Options-presets-af4d: STARTED
 (28/29) smartctl.py:SmartctlTest.test;run-Options-presets-af4d: PASS (0.51 s)
 (29/29) smartctl.py:SmartctlTest.test;run-Options-print_alldata-8f4a: STARTED
 (29/29) smartctl.py:SmartctlTest.test;run-Options-print_alldata-8f4a: PASS (0.50 s)
RESULTS    : PASS 18 | ERROR 0 | FAIL 11 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2023-03-08T08.07-8045771/results.html
JOB TIME   : 46.03 s
```

**Review by PraveenPenguin — APPROVED** [review]

**Comment by Naresh-ibm** [comment]
@abdhaleegit I could see there are still some failures in above mentioned logs.
are they real failures or something to do with the script changes?

**Comment by abdhaleegit** [comment]
> @abdhaleegit I could see there are still some failures in above mentioned logs. are they real failures or something to do with the script changes?

Those should be taken care in script, I have a separate jira for same

**Comment by Naresh-ibm** [comment]
> > @abdhaleegit I could see there are still some failures in above mentioned logs. are they real failures or something to do with the script changes?
> 
> Those should be taken care in script, I have a separate jira for same

ok

**Review by Naresh-ibm — APPROVED** [review]
LGTM

**Pull request merged**
