### PR TITLE
vTPM-tests.py: change to dynamic dmesg search string

### PR DESCRIPTION
**Pull request by nasastry**
Change the dmesg search string to the device found on the system.

Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>

### CODE REVIEW

**Comment by nasastry** [comment]
```
localhost:/home/avocado-fvt-wrapper/tests/avocado-misc-tests/security # avocado run vTPM-tests.py
JOB ID     : 50ebdc4edbf1f108ce635d4fba65993784d63bd2
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-16T13.47-50ebdc4/job.log
 (2/5) vTPM-tests.py:vTPM.test_TPM_config: STARTED
 (4/5) vTPM-tests.py:vTPM.test_tpm_measurement: STARTED
 (1/5) vTPM-tests.py:vTPM.test_TPM_register: STARTED
 (3/5) vTPM-tests.py:vTPM.test_devices: STARTED
 (5/5) vTPM-tests.py:vTPM.test_proc_devices: STARTED
 (3/5) vTPM-tests.py:vTPM.test_devices: PASS (0.54 s)
 (5/5) vTPM-tests.py:vTPM.test_proc_devices: PASS (0.54 s)
 (2/5) vTPM-tests.py:vTPM.test_TPM_config: PASS (0.57 s)
 (4/5) vTPM-tests.py:vTPM.test_tpm_measurement: PASS (0.58 s)
 (1/5) vTPM-tests.py:vTPM.test_TPM_register: PASS (0.58 s)
RESULTS    : PASS 5 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-16T13.47-50ebdc4/results.html
JOB TIME   : 97.19 s
```

**Review by Naresh-ibm — APPROVED** [review]
LGTM

**Review by abdhaleegit — APPROVED** [review]
LGTN

**Comment by abdhaleegit** [comment]
@PraveenPenguin any concerns

**Review by PraveenPenguin — APPROVED** [review]

**Pull request merged**
