### PR TITLE
updated script

### PR DESCRIPTION
**Pull request by preetithakur**
added latest url and 1 package libtool

Signed-off-by: preeti thakur <preeti.thakur@in.ibm.com>

### CODE REVIEW

**Comment by preetithakur** [comment]
[root@ltcrain41-lp11 toolchain]# avocado run --test-runner runner ltrace.py
JOB ID     : 630190ad92dfa9e85de241475e8aafb3b54bee79
JOB LOG    : /root/preeti4/avocado-fvt-wrapper/results/job-2022-02-21T09.44-630190a/job.log
 (1/1) ltrace.py:Ltrace.test: FAIL: 70 test(s) failed, check the log for details. (185.00 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/preeti4/avocado-fvt-wrapper/results/job-2022-02-21T09.44-630190a/results.html
JOB TIME   : 188.41 s

**Comment by Naresh-ibm** [comment]
@preetithakur in above script run, test exited with failure.
please attach the job.log for more details.

It is always suggestible that, add the Test PASS logs after you fix something instead of FAILED logs. if something is breaking the test other than your fixes then call it explicitly that current PR is for only particular fixes and other issue will be fixed in subsequent PR.  hope you got the point

**Comment by preetithakur** [comment]
tests will not pass, there are failures seen.
so to get to desired results above things to be fixed else result will come as error.
Praveen is already aware about this

for the failures below defect is raised

https://bugzilla.linux.ibm.com/show_bug.cgi?id=196496

**Comment by preetithakur** [comment]
another upstream defect was raised but the above fix is  to update url which is replaced with the old one and a mandatory package addition

**Comment by Naresh-ibm** [comment]
> tests will not pass, there are failures seen. so to get to desired results above things to be fixed else result will come as error. Praveen is already aware about this
> 
> for the failures below defect is raised
> 
> https://bugzilla.linux.ibm.com/show_bug.cgi?id=196496

Ok preeti. as said please call out here in such case so that the reviewers will be aware of it and can confidently approve the PR.

**Comment by PraveenPenguin** [comment]
@preetithakur as we have URL change set already part of Upstream , can you rebase you tree and have you patch for package issue , @preetithakur one suggestion please  try to avoid pasting Bugzilla link in upstream repo ,

**Comment by PraveenPenguin** [comment]
@Naresh-ibm thanks for looking into this

**Comment by preetithakur** [comment]
@PraveenPenguin sure ,
raised another PR for package addition. closing this now since url is already updated in another PR

**Pull request closed without merging**
