### PR TITLE
perf/perf_hv_gpci: Handle non root user addition

### PR DESCRIPTION
**Pull request by sacsant**
This script allows a non root user to execute perf commands and
has checks in place to add such a non root user if it does not exist.

If addition of non root user fails, the script logs a warning message.
Extend this logic to run_cmd() function as well to avoid runtime
error if user does not exist.

Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>

### CODE REVIEW

**Comment by sacsant** [comment]
Before fix:

 (1/1) avocado-misc-tests/perf/perf_hv_gpci.py:perf_hv_gpci.test_gpci_events: STARTED
 (1/1) avocado-misc-tests/perf/perf_hv_gpci.py:perf_hv_gpci.test_gpci_events: ERROR: Command 'id test' failed.\nstdout: b''\nstderr: b'id: \xe2\x80\x98test\xe2\x80\x99: no such user\n'\nadditional_info: None (21.04 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

Addition of user can fail with:
[stdlog] 2023-06-24 21:40:36,246 avocado.utils.process INFO | Running 'useradd test'
[stdlog] 2023-06-24 21:40:36,252 avocado.utils.process DEBUG| [stderr] useradd: existing lock file /etc/subgid.lock without a PID
[stdlog] 2023-06-24 21:40:36,252 avocado.utils.process DEBUG| [stderr] useradd: cannot lock /etc/subgid; try again later.
[stdlog] 2023-06-24 21:40:36,252 avocado.utils.process INFO | Command 'useradd test' finished with 18 after 0.004868985s
[stdlog] 2023-06-24 21:40:36,253 avocado.test WARNI| test useradd failed

After fix:

 (1/1) avocado-misc-tests/perf/perf_hv_gpci.py:perf_hv_gpci.test_gpci_events: STARTED
 (1/1) avocado-misc-tests/perf/perf_hv_gpci.py:perf_hv_gpci.test_gpci_events: WARN: Test passed but there were warnings during execution. Check the log for details. (44.10 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 1 | INTERRUPT 0 | CANCEL 0

**Review by Naresh-ibm — APPROVED** [review]
LGTM

**Review by Naresh-ibm — APPROVED** [review]
LGTM

**Review by disgoel — APPROVED** [review]
Looks good.

**Pull request merged**
