### PR TITLE
memory/ndctl: Correct iniparser header dependency

### PR DESCRIPTION
**Pull request by sacsant**
Commit 26b9f92(enable support for meson build) unconditionally fails
    the tests when using upstream as a target. Remove this restriction
    for releases that ship iniparser package.
    
    Additionally the code in autotools_build_system unconditionally
    copies iniparser headers to required directory. This copy operation
    fails on releases that ship these headers. Add a check for such releases
    and skip the copy operation to avoid test failures.
    
    Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>

### CODE REVIEW

**Comment by sacsant** [comment]
With upstream v72 ndctl version on RHEL 8.x host using following YAML input file
```
region: 'region0'
ndctl_project_version: '72'
preserve_change: True
fio_job:
version: !mux
    upstream:
        package : 'upstream'
mode_types: !mux
    fsdax:
        modes: 'fsdax'

```
test fails with following error:
`(01/30) memory/ndctl.py:NdctlTest.test_bus_ids;run-fio_job-mode_types-fsdax-version-upstream-8ba9: ERROR: '/usr/include/iniparser.h' and '/usr/include/iniparser/iniparser.h' are the same file (2.48 s)
`
after fix:
avocado run --test-runner runner memory/ndctl.py -m memory/ndctl.py.data/v72.yaml 
JOB ID     : 1507f9091b6b888a6ee36e844868af9c862e93e9
JOB LOG    : /home/upstreamci/avocado-fvt-wrapper/results/job-2022-05-29T08.29-1507f90/job.log
 (01/30) memory/ndctl.py:NdctlTest.test_bus_ids;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (13.67 s)
 (02/30) memory/ndctl.py:NdctlTest.test_dimms;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.33 s)
 (03/30) memory/ndctl.py:NdctlTest.test_dimm_health;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.30 s)
 (04/30) memory/ndctl.py:NdctlTest.test_regions;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.51 s)
 (05/30) memory/ndctl.py:NdctlTest.test_namespace;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.88 s)
 (06/30) memory/ndctl.py:NdctlTest.test_namespace_unaligned;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (13.23 s)
 (07/30) memory/ndctl.py:NdctlTest.test_disable_enable_ns;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (14.46 s)
 (08/30) memory/ndctl.py:NdctlTest.test_namespace_modes;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (14.35 s)
 (09/30) memory/ndctl.py:NdctlTest.test_namespace_devmap;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.46 s)
 (10/30) memory/ndctl.py:NdctlTest.test_multiple_namespaces_region;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (13.22 s)
 (11/30) memory/ndctl.py:NdctlTest.test_multiple_ns_multiple_region;run-fio_job-mode_types-fsdax-version-upstream-c83b: CANCEL: Cannot determine the mapping alignment size (15.91 s)
 (12/30) memory/ndctl.py:NdctlTest.test_multiple_ns_modes_region;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.59 s)
 (13/30) memory/ndctl.py:NdctlTest.test_nslot_namespace;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (13.75 s)
 (14/30) memory/ndctl.py:NdctlTest.test_namespace_reconfigure;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (16.58 s)
 (15/30) memory/ndctl.py:NdctlTest.test_check_namespace;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.91 s)
 (16/30) memory/ndctl.py:NdctlTest.test_check_numa;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.41 s)
 (17/30) memory/ndctl.py:NdctlTest.test_check_ns_numa;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.95 s)
 (18/30) memory/ndctl.py:NdctlTest.test_label_read_write;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (13.85 s)
 (19/30) memory/ndctl.py:NdctlTest.test_daxctl_list;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.67 s)
 (20/30) memory/ndctl.py:NdctlTest.test_region_capabilities;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (18.95 s)
 (21/30) memory/ndctl.py:NdctlTest.test_daxctl_memhotplug_unplug;run-fio_job-mode_types-fsdax-version-upstream-c83b: FAIL: PMemException('Failed to reconfigure device dax0.0',) (12.49 s)
 (22/30) memory/ndctl.py:NdctlTest.test_write_infoblock_supported_align;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.76 s)
 (23/30) memory/ndctl.py:NdctlTest.test_write_infoblock_unalign;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.80 s)
 (24/30) memory/ndctl.py:NdctlTest.test_write_infoblock_align_default;run-fio_job-mode_types-fsdax-version-upstream-c83b: FAIL: Alignment is not same as default alignment (12.58 s)
 (25/30) memory/ndctl.py:NdctlTest.test_write_infoblock_size;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.71 s)
 (26/30) memory/ndctl.py:NdctlTest.test_write_infoblock_size_unaligned;run-fio_job-mode_types-fsdax-version-upstream-c83b: PASS (12.80 s)
 (27/30) memory/ndctl.py:NdctlTest.test_sector_write;run-fio_job-mode_types-fsdax-version-upstream-c83b: ERROR: Partition(/dev/pmem0s): Mount failed: Command 'mount -t xfs /dev/pmem0s /pmemS' failed.\nstdout: b''\nstderr: b"mount: /pmemS: unknown filesystem type 'xfs'.\n"\nadditional_info: None (18.49 s)
 (28/30) memory/ndctl.py:NdctlTest.test_fsdax_write;run-fio_job-mode_types-fsdax-version-upstream-c83b: FAIL: PMemException('Namespace create command failed',) (12.40 s)
 (29/30) memory/ndctl.py:NdctlTest.test_map_sync;run-fio_job-mode_types-fsdax-version-upstream-c83b: FAIL: PMemException('Namespace create command failed',) (12.45 s)
 (30/30) memory/ndctl.py:NdctlTest.test_devdax_write;run-fio_job-mode_types-fsdax-version-upstream-c83b: FAIL: PMemException('Namespace create command failed',) (12.35 s)
RESULTS    : PASS 23 | ERROR 1 | FAIL 5 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /home/upstreamci/avocado-fvt-wrapper/results/job-2022-05-29T08.29-1507f90/results.html
JOB TIME   : 414.80 s

**Comment by sacsant** [comment]
Please wait for a day or so before providing any review comments. I have identified few more issues and working on fixing them. Will post the patches shortly.

**Review by Naresh-ibm — APPROVED** [review]

**Comment by Naresh-ibm** [comment]
LGTM

**Comment by Naresh-ibm** [comment]
ohhh, please ignore above approval if you are still working some other fixes in same PR

**Comment by sacsant** [comment]
On RHEL 9.0

With default parameters and without any YAML config as input:
Without the fix:
(01/30) memory/ndctl.py:NdctlTest.test_bus_ids: CANCEL: Cancelling the test due to non-availability ofdependent packages. (0.01 s)

With the fix:
 (01/30) memory/ndctl.py:NdctlTest.test_bus_ids: CANCEL: Test needs atleast one region (7.62 s)

The test was cancelled as pmem region was not configured. ndctl code was compiled successfully using meson
2022-05-31 10:31:01,410 process          L0739 INFO | Command 'meson setup build' finished with 0 after 1.232795316s
2022-05-31 10:31:01,411 process          L0658 INFO | Running 'meson install -C build'
2022-05-31 10:31:02,981 process          L0739 INFO | Command 'meson install -C build' finished with 0 after 1.569663327s

**Comment by sacsant** [comment]
On RHEL 8.6
With default parameters and without any YAML config as input:
Without the fix:
 (01/30) memory/ndctl.py:NdctlTest.test_bus_ids: CANCEL: Cancelling the test due to the non-availability ofdependent packages. (2.30 s)

With the fix:
 (01/30) memory/ndctl.py:NdctlTest.test_bus_ids: PASS (6.33 s)
 (02/30) memory/ndctl.py:NdctlTest.test_dimms: PASS (2.30 s)
 (03/30) memory/ndctl.py:NdctlTest.test_dimm_health: PASS (2.34 s)
 (04/30) memory/ndctl.py:NdctlTest.test_regions: PASS (2.41 s)
 (05/30) memory/ndctl.py:NdctlTest.test_namespace: PASS (3.19 s)
 (06/30) memory/ndctl.py:NdctlTest.test_namespace_unaligned: PASS (2.45 s)
 (07/30) memory/ndctl.py:NdctlTest.test_disable_enable_ns: PASS (5.09 s)
 (08/30) memory/ndctl.py:NdctlTest.test_namespace_modes: PASS (3.54 s)
 (09/30) memory/ndctl.py:NdctlTest.test_namespace_devmap: PASS (2.81 s)
 (10/30) memory/ndctl.py:NdctlTest.test_multiple_namespaces_region: PASS (6.45 s)
 (11/30) memory/ndctl.py:NdctlTest.test_multiple_ns_multiple_region: PASS (10.78 s)
 (12/30) memory/ndctl.py:NdctlTest.test_multiple_ns_modes_region: PASS (3.43 s)
 (13/30) memory/ndctl.py:NdctlTest.test_nslot_namespace: PASS (6.50 s)
 (14/30) memory/ndctl.py:NdctlTest.test_namespace_reconfigure: PASS (3.23 s)
 (15/30) memory/ndctl.py:NdctlTest.test_check_namespace: PASS (2.92 s)
 (16/30) memory/ndctl.py:NdctlTest.test_check_numa: PASS (2.59 s)
 (17/30) memory/ndctl.py:NdctlTest.test_check_ns_numa: PASS (4.40 s)
 (18/30) memory/ndctl.py:NdctlTest.test_label_read_write: PASS (3.16 s)
 (19/30) memory/ndctl.py:NdctlTest.test_daxctl_list: PASS (2.60 s)
 (20/30) memory/ndctl.py:NdctlTest.test_region_capabilities: PASS (8.10 s)
 (21/30) memory/ndctl.py:NdctlTest.test_daxctl_memhotplug_unplug: PASS (28.12 s)
 (22/30) memory/ndctl.py:NdctlTest.test_write_infoblock_supported_align: PASS (3.32 s)
 (23/30) memory/ndctl.py:NdctlTest.test_write_infoblock_unalign: PASS (3.11 s)
 (24/30) memory/ndctl.py:NdctlTest.test_write_infoblock_align_default: FAIL: Alignment is not same as default alignment (2.93 s)
 (25/30) memory/ndctl.py:NdctlTest.test_write_infoblock_size: PASS (3.54 s)
 (26/30) memory/ndctl.py:NdctlTest.test_write_infoblock_size_unaligned: PASS (2.87 s)
 (27/30) memory/ndctl.py:NdctlTest.test_sector_write: PASS (150.28 s)
 (28/30) memory/ndctl.py:NdctlTest.test_fsdax_write: PASS (71.91 s)
 (29/30) memory/ndctl.py:NdctlTest.test_map_sync: PASS (3.34 s)
 (30/30) memory/ndctl.py:NdctlTest.test_devdax_write: PASS (206.98 s)

With YAML config as input specifying  < v73 to be used:
Without the fix:
avocado run --test-runner runner memory/ndctl.py -m memory/ndctl.py.data/v72.yaml
 (01/30) memory/ndctl.py:NdctlTest.test_bus_ids;run-version-upstream-668b: ERROR: '/usr/include/iniparser.h' and '/usr/include/iniparser/iniparser.h' are the same file (2.36 s)
 (02/30) memory/ndctl.py:NdctlTest.test_dimms;run-version-upstream-668b: ERROR: '/usr/include/iniparser.h' and '/usr/include/iniparser/iniparser.h' are the same file (1.27 s)

With the fix:
avocado run --test-runner runner memory/ndctl.py -m memory/ndctl.py.data/v72.yaml
 (01/30) memory/ndctl.py:NdctlTest.test_bus_ids;run-version-upstream-668b: PASS (14.81 s)
 (02/30) memory/ndctl.py:NdctlTest.test_dimms;run-version-upstream-668b: PASS (13.62 s)
 (03/30) memory/ndctl.py:NdctlTest.test_dimm_health;run-version-upstream-668b: PASS (13.59 s)
 (04/30) memory/ndctl.py:NdctlTest.test_regions;run-version-upstream-668b: PASS (13.72 s)
 (05/30) memory/ndctl.py:NdctlTest.test_namespace;run-version-upstream-668b: PASS (14.00 s)
 (06/30) memory/ndctl.py:NdctlTest.test_namespace_unaligned;run-version-upstream-668b: PASS (14.39 s)
 (07/30) memory/ndctl.py:NdctlTest.test_disable_enable_ns;run-version-upstream-668b: PASS (15.67 s)
 (08/30) memory/ndctl.py:NdctlTest.test_namespace_modes;run-version-upstream-668b: PASS (16.00 s)
….
….

**Review by PraveenPenguin — APPROVED** [review]

**Pull request merged**
