### PR TITLE
Ib Latency Performance tests

### PR DESCRIPTION
**Pull request by prudmiry**
Ib Latency Performance tests

using four tools ib_send_lat,ib_write_lat,ib_read_lat,ib_atomic_lat

Signed-off-by: prudhvi <mprudhvi@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by prudmiry** [comment]
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/515745/job.txt)
log added

**Comment by narasimhan-v** [comment]
Looks good to me

**Comment by PraveenPenguin** [comment]
@prudmiry only issue with pylint about `import main` as getting 

`E:105, 4: Undefined variable 'main' (undefined-variable)` can you please add import main as well other wise looks good

**Comment by prudmiry** [comment]
closed PR, and open new PR #106

**Pull request closed without merging**
