### PR TITLE
Xfstest fixes with upstream as a target

### PR DESCRIPTION
**Pull request by sacsant**
With upstream as a target following failures are observed

 - inih header file dependency during xfsprogs code compilation
 - local.config file not found

This 2 patch series fixes these problem.

Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>

### CODE REVIEW

**Comment by sacsant** [comment]
inih-devel header dependency failure

 (1/1) fs/xfstests.py:Xfstests.test;run-disk_type-fs_type-fs_xfs_4k-run_type-upstream-8eea: STARTED
 (1/1) fs/xfstests.py:Xfstests.test;run-disk_type-fs_type-fs_xfs_4k-run_type-upstream-8eea: ERROR: Command 'make' failed.\nstdout: b"libtoolize -c -i -f\nlibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.\nlibtoolize: copying file './config.guess'\nlibtoolize: copying file './config.sub'\nlibtoolize: copying file './install-sh'\nlibtoolize: ... (5.46 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by sacsant** [comment]
local.config file not found error

(1/1) fs/xfstests.py:Xfstests.test;run-disk_type-fs_type-fs_xfs_4k-run_type-upstream-8eea: ERROR: stat: path should be string, bytes, os.PathLike or integer, not NoneType (23.60 s)

**Comment by sacsant** [comment]
@PraveenPenguin @abdhaleegit should I resubmit this after the Travis check issue is resolved?

**Comment by PraveenPenguin** [comment]
Yes @sacsant it is fixed , can you please resend  the request

**Comment by sacsant** [comment]
Test results after the fix:

w/64k page size + upstream
(1/1) /home/upstreamci/avocado-fvt-wrapper/tests/avocado-misc-tests/fs/xfstests.py:Xfstests.test;run-fs_type-fs_xfs_64k-loop_type-run_type-upstream-8427:  FAIL: One or more tests failed. Please check the logs. (1992.76 s)

w/4k page size + upstream
(1/1) /home/upstreamci/avocado-fvt-wrapper/tests/avocado-misc-tests/fs/xfstests.py:Xfstests.test;run-fs_type-fs_xfs_4k-loop_type-run_type-upstream-7617:  FAIL: One or more tests failed. Please check the logs. (1704.97 s)

**Comment by PraveenPenguin** [comment]
@disgoel can you please review this PR

**Review by disgoel — COMMENTED** [review]
@sacsant does it not fail on suse for inih dependency

**Comment by sacsant** [comment]
> @sacsant does it not fail on suse for inih dependency

For SUSE libinih-devel is begin installed and is taken care.

**Review by disgoel — APPROVED** [review]
LGTM

**Comment by sacsant** [comment]
I have added couple of fixes to address issues found when package install fails

commit 144455c addresses following issue when a package installation fails

Before fix:
 (1/1) fs/xfstests.py:Xfstests.test;run-fs_type-fs_xfs_4k-loop_type-run_type-upstream-7617: STARTED
 (1/1) fs/xfstests.py:Xfstests.test;run-fs_type-fs_xfs_4k-loop_type-run_type-upstream-7617: ERROR: 'Xfstests' object has no attribute 'scratch_mnt' (15.37 s)

After fix:
 (1/1) fs/xfstests.py:Xfstests.test;run-fs_type-fs_xfs_4k-loop_type-run_type-upstream-7617: STARTED
 (1/1) fs/xfstests.py:Xfstests.test;run-fs_type-fs_xfs_4k-loop_type-run_type-upstream-7617: CANCEL: Fail to install openssl-devel required for this test. (0.49 s)

Fourth commit adjusts package dependency to suit naming convention of various distro releases.

**Review by PraveenPenguin — APPROVED** [review]

**Comment by sacsant** [comment]
@PraveenPenguin there is an issue with the last commit 3fc8e18. A comma is missing after 'userspace-rcu-devel'. Do you want me to send another fix or push this branch again to integrate updated code?

**Pull request merged**
