### PR TITLE
Support to run distribution specific gdb test

### PR DESCRIPTION
**Pull request by harish-24**
Added support to run tests from distrution gdb source

Signed-off-by: Harish <harish@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by harish-24** [comment]
Depends on https://github.com/avocado-framework/avocado/pull/2290.

**Comment by narasimhan-v** [comment]
I guess this can wait to be merged until https://github.com/avocado-framework/avocado/pull/2290

**Comment by harish-24** [comment]
@PraveenPenguin @narasimhan-v Can you have a look now as https://github.com/avocado-framework/avocado/pull/2338 is merged now. Thanks.

**Comment by PraveenPenguin** [comment]
@narasimhan-v thanks for review

**Pull request merged**
