### PR TITLE
EEH Block device test for all devices

### PR DESCRIPTION
**Pull request by maramsmurthy**
EEH failures are addressed with this change

### CODE REVIEW

**Comment by maramsmurthy** [comment]
[job1.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/11220686/job1.log)
[job2.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/11220687/job2.log)
[job3.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/11220688/job3.log)

**Comment by Naresh-ibm** [comment]
@maramsmurthy can you check if htx and EEH are in same PR is intentianal?

**Comment by maramsmurthy** [comment]
Attached log for reference
[job_EEH.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/11294978/job_EEH.log)

**Comment by maramsmurthy** [comment]
Removed HTX related changes in this PR. This PR is only for EEH

**Review by Naresh-ibm — APPROVED** [review]
@maramsmurthy Thanks for the Changes
@PraveenPenguin @abdhaleegit Thanks for reviews.
LGTM

**Pull request merged**
