### PR TITLE
Code to add the basic SRIOV VF ports

### PR DESCRIPTION
**Pull request by PavamanSubramaniyam**
Made changes to the script code inorder to add the basic SRIOV VF ports other than the veth and vnic backing devices

### CODE REVIEW

**Review by abdhaleegit — COMMENTED** [review]
What will be the yaml to use for basic logical sriov port creation and deletion

**Comment by abdhaleegit** [comment]
Logs please

**Comment by PavamanSubramaniyam** [comment]
I have pasted the result logs and the yaml used for the creation and deletion of the basic SRIOV VF ports.

cat sriov_device_test.py.data/sriov_device_test.yaml
hmc_username: "hscroot"
hmc_pwd: "abc123"
sriov_adapter: "U78D8.ND0.FGD0047-P0-C7-C0"
sriov_port: "1"
ipaddr: "18.1.1.187"
netmasks: "255.255.255.0"
peer_ip: "18.1.1.174"
mac_id: "ba:70:cb:de:3e:03"

avocado run --max-parallel-tasks=1 sriov_device_test.py:NetworkSriovDevice.test_add_logical_device -m sriov_device_test.py.data/sriov_device_test.yaml
JOB ID     : 8488dcd0243c13815550d3f0a8b9cbb0e1a5cc96
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-05-12T01.54-8488dcd/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) sriov_device_test.py:NetworkSriovDevice.test_add_logical_device;run-39ed: STARTED
 (1/1) sriov_device_test.py:NetworkSriovDevice.test_add_logical_device;run-39ed: PASS (11.94 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-05-12T01.54-8488dcd/results.html
JOB TIME   : 24.40 s

cat sriov_device_test.py.data/sriov_device_test.yaml
hmc_username: "hscroot"
hmc_pwd: "abc123"
sriov_adapter: "U78D8.ND0.FGD0047-P0-C7-C0"
sriov_port: "0"
ipaddr: "17.1.1.187"
netmasks: "255.255.255.0"
peer_ip: "17.1.1.174"
mac_id: "ba:70:cb:de:3e:04"

avocado run --max-parallel-tasks=1 sriov_device_test.py:NetworkSriovDevice.test_remove_logical_device -m sriov_device_test.py.data/sriov_device_test.yaml
JOB ID     : e156d5223ed823c39b69db8815f5e5a10fe95068
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-05-12T02.10-e156d52/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) sriov_device_test.py:NetworkSriovDevice.test_remove_logical_device;run-6e8a: STARTED
 (1/1) sriov_device_test.py:NetworkSriovDevice.test_remove_logical_device;run-6e8a: PASS (10.88 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-05-12T02.10-e156d52/results.html
JOB TIME   : 23.13 s

**Comment by abdhaleegit** [comment]
1. cfg test 
2. sles /rhel
3. sriov_test.py

**Comment by abdhaleegit** [comment]
@PavamanSubramaniyam logs please

**Comment by PavamanSubramaniyam** [comment]
Executed sriov_test.py fully and pasted the result logs here.

avocado run --max-parallel-tasks=1 sriov_device_test.py -m sriov_device_test.py.data/sriov_device_test.yaml
JOB ID     : d0c651b1d259e21bc8786c4455f0535fda4a1f5d
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-05-25T04.00-d0c651b/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/4) sriov_device_test.py:NetworkSriovDevice.test_add_logical_device;run-39ed: STARTED
 (1/4) sriov_device_test.py:NetworkSriovDevice.test_add_logical_device;run-39ed: PASS (10.38 s)
 (2/4) sriov_device_test.py:NetworkSriovDevice.test_add_migratable_sriov;run-39ed: STARTED
 (2/4) sriov_device_test.py:NetworkSriovDevice.test_add_migratable_sriov;run-39ed: CANCEL: Test unsupported (0.34 s)
 (3/4) sriov_device_test.py:NetworkSriovDevice.test_remove_migratable_sriov;run-39ed: STARTED
 (3/4) sriov_device_test.py:NetworkSriovDevice.test_remove_migratable_sriov;run-39ed: CANCEL: Test unsupported (0.34 s)
 (4/4) sriov_device_test.py:NetworkSriovDevice.test_remove_logical_device;run-39ed: STARTED
 (4/4) sriov_device_test.py:NetworkSriovDevice.test_remove_logical_device;run-39ed: PASS (10.45 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 2
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-05-25T04.00-d0c651b/results.html
JOB TIME   : 36.99 s

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Pull request merged**
