### PR TITLE
changing all network test according to configure_network module changed

### PR DESCRIPTION
**Pull request by smruti77**
changing network test according to module hosts.py and interfaces.py.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
[bonding.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4352897/bonding.log)
[bridge.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4352898/bridge.log)

**Comment by smruti77** [comment]
[htx.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4352901/htx.log)
[iperf.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4352902/iperf.log)
[multicast.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4352903/multicast.log)
[multiport.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4352904/multiport.log)
[netperf.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4352905/netperf.log)
[network_config.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4352906/network_config.log)

**Comment by smruti77** [comment]
[switch_test.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4352908/switch_test.log)
[uperf.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4352910/uperf.log)

**Comment by smruti77** [comment]
ethtool 
JOB ID     : 87f178c41e1302ef1fd2b7b5f1488fe42caff812
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-03-13T11.12-87f178c/job.log
 (01/16) ethtool_test.py:Ethtool.test_ethtool;PrivateFlag-13c6: PASS (87.70 s)
 (02/16) ethtool_test.py:Ethtool.test_ethtool;Driver-9945: PASS (15.15 s)
 (03/16) ethtool_test.py:Ethtool.test_ethtool;Autonegotiation-1ceb: PASS (25.74 s)
 (04/16) ethtool_test.py:Ethtool.test_ethtool;PauseParameter-b77e: PASS (16.29 s)
 (05/16) ethtool_test.py:Ethtool.test_ethtool;Coalescing-adf9: PASS (20.08 s)
 (06/16) ethtool_test.py:Ethtool.test_ethtool;RegisterDump-a813: PASS (45.07 s)
 (07/16) ethtool_test.py:Ethtool.test_ethtool;EEPROMDump-d991: PASS (93.51 s)
 (08/16) ethtool_test.py:Ethtool.test_ethtool;RingParameter-12e6: PASS (15.70 s)
 (09/16) ethtool_test.py:Ethtool.test_ethtool;ShowOffloadProtocolFeature-df35: PASS (17.53 s)
 (10/16) ethtool_test.py:Ethtool.test_ethtool;AdapterInitiate-180d: PASS (19.63 s)
 (11/16) ethtool_test.py:Ethtool.test_ethtool;Statistics-022d: PASS (6.88 s)
 (12/16) ethtool_test.py:Ethtool.test_ethtool;SelfTest-9507: PASS (33.43 s)
 (13/16) ethtool_test.py:Ethtool.test_ethtool;Show-permaddr-358a: PASS (7.47 s)
 (14/16) ethtool_test.py:Ethtool.test_ethtool;Get-dump-89d4: PASS (23.14 s)
 (15/16) ethtool_test.py:Ethtool.test_ethtool;Show-time-stamping-148e: PASS (15.10 s)
 (16/16) ethtool_test.py:Ethtool.test_ethtool;Get-phy-tunable-032c: FAIL: failed (12.38 s)
RESULTS    : PASS 15 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 455.25 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-03-13T11.12-87f178c/results.html

**Comment by PraveenPenguin** [comment]
@smruti77 please resolve pep8 issue

**Comment by smruti77** [comment]
> @smruti77 please resolve pep8 issue

ok

**Comment by smruti77** [comment]
@PraveenPenguin only getting "line too long" other's things is fine.then why its failing.

**Comment by narasimhan-v** [comment]
@manvanthar review please

**Pull request merged**
