### PR TITLE
Test to verify servicelog - v4

### PR DESCRIPTION
**Pull request by Pavithra1602**
The servicelog packages provides a library for logging service-related
events to the servicelog database, and a number of command-line
utilities for viewing the contents of the database.

Signed-off-by: pavrampu@linux.vnet.ibm.com <pavrampu@in.ibm.com>

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@narasimhan-v can support file test so many have you any idea how we can handle that , at placing in repo not looks good to me please help us on this

**Comment by narasimhan-v** [comment]
@PraveenPenguin Yes, that would make sense. Maintaining it here is surely going to be an overhead.

@Pavithra1602 Can you please check if this can be (or) is already hosted in some other place, from where we can refer ? Also, are these files static / dynamic ?

**Comment by Pavithra1602** [comment]
Raised new PR.

**Comment by Pavithra1602** [comment]
Reopening the PR as I could not find these files on any other links.

**Comment by PraveenPenguin** [comment]
@narasimhan-v @nasastry thanks

**Pull request merged**
