### PR TITLE
added restore_from_backup() to network tests

### PR DESCRIPTION
**Pull request by smruti77**
to remove backup config files and to restore the old config
back.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
JOB ID     : 870aed06439be08580432fe41fd764281d1afd10
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-05-06T00.19-870aed0/job.log
 (01/16) ethtool_test.py:Ethtool.test_ethtool;PrivateFlag-50ad: PASS (45.46 s)
 (02/16) ethtool_test.py:Ethtool.test_ethtool;Driver-ea23: PASS (5.65 s)
 (03/16) ethtool_test.py:Ethtool.test_ethtool;Autonegotiation-844c: FAIL: failed (5.33 s)
 (04/16) ethtool_test.py:Ethtool.test_ethtool;PauseParameter-4fdb: PASS (5.66 s)
 (05/16) ethtool_test.py:Ethtool.test_ethtool;Coalescing-66af: PASS (5.65 s)
 (06/16) ethtool_test.py:Ethtool.test_ethtool;RegisterDump-ffd4: FAIL: failed (5.32 s)
 (07/16) ethtool_test.py:Ethtool.test_ethtool;EEPROMDump-be89: FAIL: failed (5.33 s)
 (08/16) ethtool_test.py:Ethtool.test_ethtool;RingParameter-482c: PASS (5.66 s)
 (09/16) ethtool_test.py:Ethtool.test_ethtool;ShowOffloadProtocolFeature-2b80: PASS (5.67 s)
 (10/16) ethtool_test.py:Ethtool.test_ethtool;AdapterInitiate-0b1c: FAIL: failed (5.32 s)
 (11/16) ethtool_test.py:Ethtool.test_ethtool;Statistics-6654: PASS (5.68 s)
 (12/16) ethtool_test.py:Ethtool.test_ethtool;SelfTest-8985: FAIL: failed (5.37 s)
 (13/16) ethtool_test.py:Ethtool.test_ethtool;Show-permaddr-caa2: PASS (5.68 s)
 (14/16) ethtool_test.py:Ethtool.test_ethtool;Get-dump-8223: FAIL: failed (5.31 s)
 (15/16) ethtool_test.py:Ethtool.test_ethtool;Show-time-stamping-b20e: PASS (5.65 s)
 (16/16) ethtool_test.py:Ethtool.test_ethtool;Get-phy-tunable-44c6: FAIL: failed (5.33 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 7 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 128.59 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-05-06T00.19-870aed0/results.html


JOB ID     : 72abded336192268e1d5ab052ed82acc29658355
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-05-06T00.26-72abded/job.log
 (1/3) iperf_test.py:Iperf.test;1500-8653: PASS (134.34 s)
 (2/3) iperf_test.py:Iperf.test;2000-17ce: PASS (158.24 s)
 (3/3) iperf_test.py:Iperf.test;3000-73a9: PASS (182.89 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 475.59 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-05-06T00.26-72abded/results.html


JOB ID     : a5269692df6744718231e6161c251da8d4fffa73
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-05-06T00.37-a526969/job.log
 (1/1) multicast.py:ReceiveMulticastTest.test_multicast;Parameters-18e6: PASS (24.39 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 24.44 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-05-06T00.37-a526969/results.html



JOB ID     : 90d6d90c2ef857975395f0b0657ac82b08ee9248
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-05-06T00.51-90d6d90/job.log
 (1/4) multiport_stress.py:MultiportStress.test_multiport_ping;1500-1641: PASS (137.63 s)
 (2/4) multiport_stress.py:MultiportStress.test_multiport_ping;2000-e2d1: PASS (137.77 s)
 (3/4) multiport_stress.py:MultiportStress.test_multiport_floodping;1500-1641: PASS (127.66 s)
 (4/4) multiport_stress.py:MultiportStress.test_multiport_floodping;2000-e2d1: PASS (129.35 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 532.57 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-05-06T00.51-90d6d90/results.html


JOB ID     : 564141ecd5680bbd261c9704bbe6ad0b6d80a308
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-05-06T01.31-564141e/job.log
 (1/5) Network_config.py:NetworkconfigTest.test_driver_check;Parameters-b782: PASS (1.05 s)
 (2/5) Network_config.py:NetworkconfigTest.test_mtu_check;Parameters-b782: PASS (1.05 s)
 (3/5) Network_config.py:NetworkconfigTest.test_speed_check;Parameters-b782: PASS (1.06 s)
 (4/5) Network_config.py:NetworkconfigTest.test_mac_aadr_check;Parameters-b782: PASS (1.04 s)
 (5/5) Network_config.py:NetworkconfigTest.test_duplex_check;Parameters-b782: PASS (1.05 s)
RESULTS    : PASS 5 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 5.46 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-05-06T01.31-564141e/results.html


JOB ID     : 9451e1aeb825b21584c8990aa139c049468daafd
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-05-06T01.32-9451e1a/job.log
 (01/33) network_test.py:NetworkTest.test_gro;1500-119e: PASS (103.51 s)
 (02/33) network_test.py:NetworkTest.test_gro;2000-50dc: PASS (103.15 s)
 (03/33) network_test.py:NetworkTest.test_gro;3000-faae: PASS (105.28 s)


JOB ID     : dec516395b5b9b6bfa2652f43862dba739775fdc
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-05-06T01.40-dec5163/job.log
 (01/21) tcpdump.py:TcpdumpTest.test;1500-generic-d33d: PASS (91.34 s)
 (02/21) tcpdump.py:TcpdumpTest.test;2000-generic-5a5d: PASS (69.11 s)
 (03/21) tcpdump.py:TcpdumpTest.test;3000-generic-d468: PASS (70.21 s)
 (04/21) tcpdump.py:TcpdumpTest.test;1500-generic_host-35e2: PASS (69.68 s)
 (05/21) tcpdump.py:TcpdumpTest.test;2000-generic_host-8aba: PASS (70.03 s)

JOB ID     : b862e1f24c972d4d2d3673e7e5ec41c977434871
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-05-06T01.55-b862e1f/job.log
 (1/2) uperf_test.py:Uperf.test;1500-602b: PASS (233.13 s)
 (2/2) uperf_test.py:Uperf.test;2000-5a3b: PASS (161.34 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 394.64 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-05-06T01.55-b862e1f/results.html

**Comment by narasimhan-v** [comment]
@vaishnavibhat @abdhaleegit review please

**Comment by abdhaleegit** [comment]
@smruti77 please paste me the old ifcg-eth*  and after running the test give me ifcfg-eth*

I just wanted to check if HWADDR is being removed  ?

**Comment by smruti77** [comment]
> @smruti77 please paste me the old ifcg-eth* and after running the test give me ifcfg-eth*
> 
> I just wanted to check if HWADDR is being removed ?

@abdhaleegit its not going to remove now,in the end we are restoring the backup files.

**Comment by smruti77** [comment]
before test cfg file,
NAME="enP6p1s0f0"
DEVICE="enP6p1s0f0"
BOOTPROTO=none
IPADDR="111.11.11.40"
NETMASK="255.255.255.0"
TYPE=Ethernet
ONBOOT=yes
IPV6INIT=yes 
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes


after test cfg file,
NAME="enP6p1s0f0"
DEVICE="enP6p1s0f0"
BOOTPROTO=none
IPADDR="111.11.11.40"
NETMASK="255.255.255.0"
TYPE=Ethernet
ONBOOT=yes
IPV6INIT=yes 
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes

**Comment by abdhaleegit** [comment]
I do not see HWADDR param  @smruti77 please retest by adding mac addrr to interface cfg file

**Comment by smruti77** [comment]
> I do not see HWADDR param @smruti77 please retest by adding mac addrr to interface cfg file

@abdhaleegit i didn't provide HWADDR  param in my cfg file, so its not their.

**Pull request merged**
