### PR TITLE
Add test to verify MAP_SYNC flag for DAX devices

### PR DESCRIPTION
**Pull request by harish-24**
Add test to verify MAP_SYNC flag for DAX devices

Signed-off-by: Harish <harish@linux.ibm.com>

### CODE REVIEW

**Comment by harish-24** [comment]
```
 (1/1) memory/ndctl.py:NdctlTest.test_map_sync: PASS (18.05 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 18.14 s

 (1/1) memory/ndctl.py:NdctlTest.test_map_sync: FAIL: Write with MAP_SYNC flag failed (33.19 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 33.28 s
```

**Comment by harish-24** [comment]
```
JOB LOG    : /home/harish/avocado-fvt-wrapper/results/job-2020-01-30T12.17-319c6dc/job.log
 (01/19) memory/ndctl.py:NdctlTest.test_bus_ids: PASS (10.38 s)
 (02/19) memory/ndctl.py:NdctlTest.test_dimms: FAIL: Failed to fetch DIMMs (2.82 s)
 (03/19) memory/ndctl.py:NdctlTest.test_regions: PASS (6.68 s)
 (04/19) memory/ndctl.py:NdctlTest.test_namespace: PASS (10.86 s)
 (05/19) memory/ndctl.py:NdctlTest.test_disable_enable_ns: PASS (14.50 s)
 (06/19) memory/ndctl.py:NdctlTest.test_namespace_modes: FAIL: Namespace for ['raw'] mode failed! (18.51 s)
 (07/19) memory/ndctl.py:NdctlTest.test_multiple_namespaces_region: CANCEL: Legacy config skipping the test (5.68 s)
 (08/19) memory/ndctl.py:NdctlTest.test_multiple_ns_multiple_region: CANCEL: Test not applicable without multiple regions (5.65 s)
 (09/19) memory/ndctl.py:NdctlTest.test_multiple_ns_modes_region: CANCEL: Legacy config skipping the test (5.79 s)
 (10/19) memory/ndctl.py:NdctlTest.test_nslot_namespace: CANCEL: Legacy config skipping the test (5.64 s)
 (11/19) memory/ndctl.py:NdctlTest.test_namespace_reconfigure: PASS (14.56 s)
 (12/19) memory/ndctl.py:NdctlTest.test_check_namespace: PASS (7.19 s)
 (13/19) memory/ndctl.py:NdctlTest.test_check_numa: FAIL: Numa node entries not found! (3.19 s)
 (14/19) memory/ndctl.py:NdctlTest.test_label_read_write: CANCEL: Legacy config skipping the test (5.58 s)
 (15/19) memory/ndctl.py:NdctlTest.test_daxctl_list: PASS (10.58 s)
 (16/19) memory/ndctl.py:NdctlTest.test_sector_write: PASS (172.58 s)
 (17/19) memory/ndctl.py:NdctlTest.test_fsdax_write: PASS (74.97 s)
 (18/19) memory/ndctl.py:NdctlTest.test_map_sync: FAIL: Write with MAP_SYNC flag failed (11.77 s)
 (19/19) memory/ndctl.py:NdctlTest.test_devdax_write: PASS (111.39 s)
```

**Comment by PraveenPenguin** [comment]
@harish-24 are you ok do rebase or I will take care while merging?

**Comment by harish-24** [comment]
@PraveenPenguin WIll need a lot more of rebase. WIll provide results after rebase. Thanks.

**Comment by PraveenPenguin** [comment]
@harish-24 sure

**Comment by harish-24** [comment]
Rebased with the changes. 
```
 (01/19) memory/ndctl.py:NdctlTest.test_bus_ids: PASS (5.99 s)
 (02/19) memory/ndctl.py:NdctlTest.test_dimms: FAIL: Failed to fetch DIMMs (2.86 s)
 (03/19) memory/ndctl.py:NdctlTest.test_regions: PASS (6.83 s)
 (04/19) memory/ndctl.py:NdctlTest.test_namespace: PASS (10.75 s)
 (05/19) memory/ndctl.py:NdctlTest.test_disable_enable_ns: PASS (14.29 s)
 (06/19) memory/ndctl.py:NdctlTest.test_namespace_modes: FAIL: Namespace for ['raw'] mode failed! (18.37 s)
 (07/19) memory/ndctl.py:NdctlTest.test_multiple_namespaces_region: CANCEL: Legacy config skipping the test (5.75 s)
 (08/19) memory/ndctl.py:NdctlTest.test_multiple_ns_multiple_region: CANCEL: Test not applicable without multiple regions (5.45 s)
 (09/19) memory/ndctl.py:NdctlTest.test_multiple_ns_modes_region: CANCEL: Legacy config skipping the test (5.56 s)
 (10/19) memory/ndctl.py:NdctlTest.test_nslot_namespace: CANCEL: Legacy config skipping the test (5.50 s)
 (11/19) memory/ndctl.py:NdctlTest.test_namespace_reconfigure: PASS (14.65 s)
 (12/19) memory/ndctl.py:NdctlTest.test_check_namespace: PASS (7.21 s)
 (13/19) memory/ndctl.py:NdctlTest.test_check_numa: FAIL: Numa node entries not found! (3.24 s)
 (14/19) memory/ndctl.py:NdctlTest.test_label_read_write: CANCEL: Legacy config skipping the test (5.60 s)
 (15/19) memory/ndctl.py:NdctlTest.test_daxctl_list: PASS (10.63 s)
 (16/19) memory/ndctl.py:NdctlTest.test_sector_write: PASS (160.43 s)
 (17/19) memory/ndctl.py:NdctlTest.test_fsdax_write: PASS (75.13 s)
 (18/19) memory/ndctl.py:NdctlTest.test_map_sync: FAIL: Write with MAP_SYNC flag failed (12.64 s)
 (19/19) memory/ndctl.py:NdctlTest.test_devdax_write: PASS (119.45 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 4 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 5
JOB TIME   : 495.69 s
```

**Comment by harish-24** [comment]
@PraveenPenguin Rebased and good to go!

**Pull request merged**
