### PR TITLE
Making disk_info.py script platform independent

### PR DESCRIPTION
**Pull request by Naresh-ibm**
currently the script will run only on power server and gets cancel on other platform. Due to recent issue in python AI(platform) it is not returning the 'ppc64' when trying to retrive the processor type. And script can also be ran any linux machine irrespective of any platform so removed this dependency as this is a generic script.

### CODE REVIEW

**Comment by Naresh-ibm** [comment]
```
Before Fix
-------------

00:20:35 INFO    : Running Host Tests Suite io_nvme_fvt_disk_info_disk_info
00:20:35 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py -m /tmp/mux/io_nvme_fvt_disk_info_disk_info.yaml --force-job-id 14ede47e36fc50bf7a1a17a834e636e9a79b0fbb  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 14ede47e36fc50bf7a1a17a834e636e9a79b0fbb
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-09-10T00.20-14ede47/job.log
 (1/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test_commands;run-filesystem-ext4-5b26: STARTED
 (1/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test_commands;run-filesystem-ext4-5b26: CANCEL: Processor is not ppc64 (0.07 s)
 (2/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test_commands;run-filesystem-xfs-1398: STARTED
 (2/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test_commands;run-filesystem-xfs-1398: CANCEL: Processor is not ppc64 (0.01 s)
 (3/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test_commands;run-filesystem-btrfs-4afb: STARTED
 (3/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test_commands;run-filesystem-btrfs-4afb: CANCEL: Processor is not ppc64 (0.01 s)
 (4/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test;run-filesystem-ext4-5b26: STARTED
 (4/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test;run-filesystem-ext4-5b26: CANCEL: Processor is not ppc64 (0.01 s)
 (5/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test;run-filesystem-xfs-1398: STARTED
 (5/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test;run-filesystem-xfs-1398: CANCEL: Processor is not ppc64 (0.01 s)
 (6/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test;run-filesystem-btrfs-4afb: STARTED
 (6/6) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disk_info.py:DiskInfo.test;run-filesystem-btrfs-4afb: CANCEL: Processor is not ppc64 (0.01 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 6
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-09-10T00.20-14ede47/results.html
JOB TIME   : 21.10 s
00:20:59 INFO    : 


After Fix
------------

# avocado run --max-parallel-tasks=1 disk_info.py -m disk_info.py.data/disk_info.yaml
JOB ID     : 77616d02cc601f28f85074786cb5d769a4bf88b0
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-09-13T05.07-77616d0/job.log
 (1/6) disk_info.py:DiskInfo.test_commands;run-filesystem-ext4-a0d3: STARTED
 (1/6) disk_info.py:DiskInfo.test_commands;run-filesystem-ext4-a0d3: PASS (1.27 s)
 (2/6) disk_info.py:DiskInfo.test_commands;run-filesystem-xfs-5373: STARTED
 (2/6) disk_info.py:DiskInfo.test_commands;run-filesystem-xfs-5373: PASS (0.96 s)
 (3/6) disk_info.py:DiskInfo.test_commands;run-filesystem-btrfs-5433: STARTED
 (3/6) disk_info.py:DiskInfo.test_commands;run-filesystem-btrfs-5433: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (0.02 s)
 (4/6) disk_info.py:DiskInfo.test;run-filesystem-ext4-a0d3: STARTED
 (4/6) disk_info.py:DiskInfo.test;run-filesystem-ext4-a0d3: PASS (2.76 s)
 (5/6) disk_info.py:DiskInfo.test;run-filesystem-xfs-5373: STARTED
 (5/6) disk_info.py:DiskInfo.test;run-filesystem-xfs-5373: FAIL: Some tests failed. Details below:\nMismatch in sector sizes of lbs,pbs in lshw o/p w.r.t sysfs paths (3.38 s)
 (6/6) disk_info.py:DiskInfo.test;run-filesystem-btrfs-5433: STARTED
 (6/6) disk_info.py:DiskInfo.test;run-filesystem-btrfs-5433: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (0.02 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 2
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-09-13T05.07-77616d0/results.html
JOB TIME   : 36.62 s

Test summary:
5-disk_info.py:DiskInfo.test;run-filesystem-xfs-5373: FAIL
```

**Comment by Naresh-ibm** [comment]
[disk_info_debug_log.tar.gz](https://github.com/user-attachments/files/16996243/disk_info_debug_log.tar.gz)

**Comment by abdhaleegit** [comment]
@Naresh-ibm why add a new py file if disk_info.py already exists in io/disk/ ?

**Review by abdhaleegit — CHANGES_REQUESTED** [review]
looks like file is misplaced

**Comment by Naresh-ibm** [comment]
closing this with reference to #2898

**Comment by Naresh-ibm** [comment]
closing

**Pull request closed without merging**
