### PR TITLE
The Test fetches the ATLAS source, builds and execute sanity tests in…

### PR DESCRIPTION
**Pull request by santhosh93**
… it.

It builds the ATLAS libraries and runs the tests present in it.
Several other test options can be given from yaml file and resp
tests can be run

Signed-off-by: Santhosh G <santhog4@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by santhosh93** [comment]
@narasimhan-v  : Sure...Thanks..

**Comment by PraveenPenguin** [comment]
@santhosh93 any update here

**Comment by santhosh93** [comment]
@narasimhan-v  : Added new appropriate commit message..

**Comment by PraveenPenguin** [comment]
@santhosh93 can you please raise two different PR or commit message one for LTP fix other for ATLAS Test

**Comment by santhosh93** [comment]
@PraveenPenguin  : Sorry , by some mistake I have sent.Will send again without LTP.

**Pull request closed without merging**
