### PR TITLE
fixed issues in perf:perf_events_test test

### PR DESCRIPTION
**Pull request by PraveenPenguin**
1-Rectified make failed cancel string
2- rectified unnecessary check
3- Added privileged tag

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@nasastry review please

**Comment by nasastry** [comment]
@PraveenPenguin `privileged` tag is for the tests, who runs as a super user privileges? if the answer is `yes` then this patch looks good.

**Comment by PraveenPenguin** [comment]
@nasastry yes it meant for super user

**Comment by PraveenPenguin** [comment]
@nasastry thanks for ACK , merging

**Pull request merged**
