### PR TITLE
Resolving cleanup issue for fiotest.py

### PR DESCRIPTION
**Pull request by Naresh-ibm**
Similar to tiobench other tests under disk dir we have claenup
issue i,e the mounted dir and disk or fs created on disk or sraids
are not getting cleanup up properly after each varient ran.
so this code will resolve this issue

Signed-off-by: Naresh Bannoth <nbannoth@in.ibm.com>

### CODE REVIEW

**Comment by Naresh-ibm** [comment]
After fix
--------------

[root@ltcrain6yo-lp6 disk]# avocado run --test-runner runner fiotest.py -m fiotest.py.data/fio.yaml 
JOB ID     : d612b64f28e6b116c234adaede3dff7b0b809a28
JOB LOG    : /home/ioci/avocado-fvt-wrapper/results/job-2022-06-02T02.30-d612b64/job.log
 (01/16) fiotest.py:FioTest.test;run-fs-ext4-lv-lv-raid-raid-3852: PASS (79.39 s)
 (02/16) fiotest.py:FioTest.test;run-fs-ext4-lv-lv-raid-no_raid-fbd2: PASS (65.75 s)
 (03/16) fiotest.py:FioTest.test;run-fs-ext4-lv-no_lv-raid-raid-40f6: PASS (58.02 s)
 (04/16) fiotest.py:FioTest.test;run-fs-ext4-lv-no_lv-raid-no_raid-d5b6: PASS (60.98 s)
 (05/16) fiotest.py:FioTest.test;run-fs-xfs-lv-lv-raid-raid-a939: PASS (63.07 s)
 (06/16) fiotest.py:FioTest.test;run-fs-xfs-lv-lv-raid-no_raid-a2b7: PASS (65.57 s)
 (07/16) fiotest.py:FioTest.test;run-fs-xfs-lv-no_lv-raid-raid-24a5: PASS (58.07 s)
 (08/16) fiotest.py:FioTest.test;run-fs-xfs-lv-no_lv-raid-no_raid-34d5: PASS (56.53 s)
 (09/16) fiotest.py:FioTest.test;run-fs-btrfs-lv-lv-raid-raid-ccd8: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (0.83 s)
 (10/16) fiotest.py:FioTest.test;run-fs-btrfs-lv-lv-raid-no_raid-1f68: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (0.81 s)
 (11/16) fiotest.py:FioTest.test;run-fs-btrfs-lv-no_lv-raid-raid-0277: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (0.78 s)
 (12/16) fiotest.py:FioTest.test;run-fs-btrfs-lv-no_lv-raid-no_raid-1469: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (0.85 s)
 (13/16) fiotest.py:FioTest.test;run-fs-no_fs-lv-lv-raid-raid-6cf5: WARN: Test passed but there were warnings during execution. Check the log for details. (57.76 s)
 (14/16) fiotest.py:FioTest.test;run-fs-no_fs-lv-lv-raid-no_raid-99fe: WARN: Test passed but there were warnings during execution. Check the log for details. (58.76 s)
 (15/16) fiotest.py:FioTest.test;run-fs-no_fs-lv-no_lv-raid-raid-8057: WARN: Test passed but there were warnings during execution. Check the log for details. (53.17 s)
 (16/16) fiotest.py:FioTest.test;run-fs-no_fs-lv-no_lv-raid-no_raid-a69d: WARN: Test passed but there were warnings during execution. Check the log for details. (53.81 s)
RESULTS    : PASS 8 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 4 | INTERRUPT 0 | CANCEL 4
JOB HTML   : /home/ioci/avocado-fvt-wrapper/results/job-2022-06-02T02.30-d612b64/results.html
JOB TIME   : 735.39 s
[root@ltcrain6yo-lp6 disk]#

**Comment by Naresh-ibm** [comment]
[fio_cleanup_job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/8843799/fio_cleanup_job.log)

**Comment by PraveenPenguin** [comment]
@Naresh-ibm can you please push cleanup code and other changes like style fixes in another commit

**Review by abdhaleegit — CHANGES_REQUESTED** [review]
Please run once fc/vfc test bucket to see the cleanup is happening.. ?

**Comment by Naresh-ibm** [comment]
closing this in favour of #2355.

**Pull request closed without merging**
