### PR TITLE
[RFC] Convert non class member as static methods

### PR DESCRIPTION
**Pull request by kamalesh-babulal**
This series converts the non-class specific functions into staticmethod, mostly converts `run_cmd_out()` into staticmethod, expect for ` io/net/vlan_test.py` where another function `ping_check_host()` can also be converted into staticmethod. This series is inspired by review comments from pull request #1000

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@kamalesh-babulal does this need 7 different commits ?

**Comment by PraveenPenguin** [comment]
@narasimhan-v i think we need to wrap this in single commit

**Comment by kamalesh-babulal** [comment]
@narasimhan-v @PraveenPenguin thought behind was a single commit per testcase, if you suggest me to fold it into a single commit, I will re-do the pull request.

**Comment by narasimhan-v** [comment]
@kamalesh-babulal the files are different, yes. But same impact (ie, none), so single commit would do here.

**Comment by narasimhan-v** [comment]
@kamalesh-babulal thanks

**Pull request merged**
