### PR TITLE
Adding metadata support to softwareraid tests

### PR DESCRIPTION
**Pull request by narasimhan-v**
Adding metadata support to softwareraid tests.

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
```
 (01/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-0.90-raidlinear-46d7: PASS (1.39 s)
 (02/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.0-raidlinear-a1c1: PASS (1.62 s)
 (03/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.1-raidlinear-9405: PASS (1.60 s)
 (04/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.2-raidlinear-a208: PASS (1.77 s)
 (05/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-0.90-raid0-cd88: PASS (1.64 s)
 (06/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.0-raid0-64c1: PASS (1.57 s)
 (07/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.1-raid0-f6c3: PASS (1.62 s)
 (08/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.2-raid0-ee62: PASS (1.45 s)
 (09/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-0.90-raid1-89d4: FAIL (1.65 s)
 (10/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.0-raid1-58e3: FAIL (1.72 s)
 (11/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.1-raid1-f969: FAIL (1.75 s)
 (12/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.2-raid1-7552: FAIL (1.71 s)
 (13/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-0.90-raid5-5f9d: FAIL (1.02 s)
 (14/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.0-raid5-38d6: FAIL (1.14 s)
 (15/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.1-raid5-7dba: FAIL (1.08 s)
 (16/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.2-raid5-0bd9: FAIL (1.10 s)
 (17/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-0.90-raid10-aa0e: FAIL (1.07 s)
 (18/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.0-raid10-b451: FAIL (1.01 s)
 (19/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.1-raid10-a5a3: FAIL (1.01 s)
 (20/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.2-raid10-22ab: FAIL (0.99 s)
 (21/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-0.90-raid6-b552: FAIL (1.09 s)
 (22/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.0-raid6-345e: FAIL (0.98 s)
 (23/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.1-raid6-cb1a: FAIL (0.95 s)
 (24/24) softwareraid_new.py:SoftwareRaid.test_run;superblock-1.2-raid6-1cd1: FAIL (0.92 s)
```

**Comment by vrbagalkote** [comment]
@narasimhan-v cool...looks good to me.

**Comment by narasimhan-v** [comment]
@vrbagalkote Thanks.
@PraveenPenguin can you please take a look at this one ?

**Comment by PraveenPenguin** [comment]
@vrbagalkote thanks for review

**Pull request merged**
