### PR TITLE
Modified parameter direct=0 to 1 for fio job files as per the comments

### PR DESCRIPTION
**Pull request by Venutiwa**
added thread parameter to the job files
with reference to https://github.com/axboe/fio/issues/512#issuecomment-356552337

Signed-off-by: Venu <venutiwa@in.ibm.com>

### CODE REVIEW

**Comment by sitsofe** [comment]
Just for the record you don't have to use thread just because you are using direct=1 .

**Comment by Venutiwa** [comment]
@sitsofe yes I am aware, thread parameter is for our test requirement.

**Comment by narasimhan-v** [comment]
@Venutiwa can you add the fio comment link to commit message as well, so that it would be useful later

**Comment by PraveenPenguin** [comment]
@Venutiwa @narasimhan-v any update on this PR ,if this PR not pursue any more can we close this

**Comment by narasimhan-v** [comment]
@PraveenPenguin Sure, we can give it 2 more days.

**Comment by Venutiwa** [comment]
@narasimhan-v  @PraveenPenguin Sorry I missed this. Will add comment right away.

**Comment by Venutiwa** [comment]
@PraveenPenguin  Done

**Comment by narasimhan-v** [comment]
@Venutiwa thanks.

**Pull request merged**
