### PR TITLE
add LV, Software raid to disktest.py

### PR DESCRIPTION
**Pull request by smruti77**
Test creates LV,software raid and runs test on them, as an option.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
JOB ID     : 57fb17daf0cd9a1f65ec2feff9b580f42073cc40
JOB LOG    : /root/avocado/job-results/job-2020-07-30T04.23-57fb17d/job.log
 (01/16) disktest.py:Disktest.test;dir-ext4-lv-raid-e331: FAIL: The 20900 pid(s) failed, please check the logs and /root/avocado/job-results/job-2020-07-30T04.23-57fb17d/test-results/01-disktest.py_Disktest.test_dir-ext4-lv-raid-e331/data/log.txt for details. (22.05 s)
 (02/16) disktest.py:Disktest.test;dir-ext4-lv-no_raid-a54d: FAIL: The 21051 pid(s) failed, please check the logs and /root/avocado/job-results/job-2020-07-30T04.23-57fb17d/test-results/02-disktest.py_Disktest.test_dir-ext4-lv-no_raid-a54d/data/log.txt for details. (23.99 s)
 (03/16) disktest.py:Disktest.test;dir-ext4-no_lv-raid-e34f: PASS (22.33 s)
 (04/16) disktest.py:Disktest.test;dir-ext4-no_lv-no_raid-18cb: PASS (23.44 s)
 (05/16) disktest.py:Disktest.test;dir-xfs-lv-raid-3443: FAIL: The 21397 pid(s) failed, please check the logs and /root/avocado/job-results/job-2020-07-30T04.23-57fb17d/test-results/05-disktest.py_Disktest.test_dir-xfs-lv-raid-3443/data/log.txt for details. (22.39 s)
 (06/16) disktest.py:Disktest.test;dir-xfs-lv-no_raid-1a27: FAIL: The 21552 pid(s) failed, please check the logs and /root/avocado/job-results/job-2020-07-30T04.23-57fb17d/test-results/06-disktest.py_Disktest.test_dir-xfs-lv-no_raid-1a27/data/log.txt for details. (22.05 s)
 (07/16) disktest.py:Disktest.test;dir-xfs-no_lv-raid-1a12: PASS (21.66 s)
 (08/16) disktest.py:Disktest.test;dir-xfs-no_lv-no_raid-aaca: PASS (21.32 s)
 (09/16) disktest.py:Disktest.test;dir-btrfs-lv-raid-b07c: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (0.50 s)
 (10/16) disktest.py:Disktest.test;dir-btrfs-lv-no_raid-d2fe: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (0.49 s)
 (11/16) disktest.py:Disktest.test;dir-btrfs-no_lv-raid-1283: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (0.49 s)
 (12/16) disktest.py:Disktest.test;dir-btrfs-no_lv-no_raid-ce1c: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (0.49 s)
 (13/16) disktest.py:Disktest.test;dir-no_fs-lv-raid-53eb: FAIL: The 21908 pid(s) failed, please check the logs and /root/avocado/job-results/job-2020-07-30T04.23-57fb17d/test-results/13-disktest.py_Disktest.test_dir-no_fs-lv-raid-53eb/data/log.txt for details. (4.34 s)
 (14/16) disktest.py:Disktest.test;dir-no_fs-lv-no_raid-f3a0: FAIL: The 22024 pid(s) failed, please check the logs and /root/avocado/job-results/job-2020-07-30T04.23-57fb17d/test-results/14-disktest.py_Disktest.test_dir-no_fs-lv-no_raid-f3a0/data/log.txt for details. (4.98 s)
 (15/16) disktest.py:Disktest.test;dir-no_fs-no_lv-raid-baf0: PASS (20.79 s)
 (16/16) disktest.py:Disktest.test;dir-no_fs-no_lv-no_raid-803b: PASS (20.26 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 6 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 4
JOB HTML   : /root/avocado/job-results/job-2020-07-30T04.23-57fb17d/results.html
JOB TIME   : 231.88 s

**Comment by narasimhan-v** [comment]
@smruti77 Please upload job.log file

**Comment by narasimhan-v** [comment]
@smruti77 Please upload job.log file

**Comment by smruti77** [comment]
[disktest.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5067497/disktest.log)

**Comment by abdhaleegit** [comment]
Taken care here https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2343

**Pull request closed without merging**
