### PR TITLE
perf_bench.py: adding perf bench test cases

### PR DESCRIPTION
**Pull request by nasastry**
Adding perf bench tests with different arguments

Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by nasastry** [comment]
Job log: with yaml file

```
JOB ID     : ba67aaefcef451a8b4da0ace22602921ecc5a440
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2019-07-29T12.22-ba67aae/job.log
 (01/12) perf_bench.py:perf_bench.test_bench;sched_messaging-5248: PASS (0.96 s)
 (02/12) perf_bench.py:perf_bench.test_bench;sched_pipe-efdf: PASS (10.97 s)
 (03/12) perf_bench.py:perf_bench.test_bench;mem_memcpy-1f13: PASS (0.73 s)
 (04/12) perf_bench.py:perf_bench.test_bench;mem_memset-ad49: PASS (0.75 s)
 (05/12) perf_bench.py:perf_bench.test_bench;numa_mem-10ab: PASS (1208.93 s)
 (06/12) perf_bench.py:perf_bench.test_bench;numa_all-07fc: PASS (1194.01 s)
 (07/12) perf_bench.py:perf_bench.test_bench;futex_hash-00dc: PASS (10.78 s)
 (08/12) perf_bench.py:perf_bench.test_bench;futex_wake-5625: PASS (1.76 s)
 (09/12) perf_bench.py:perf_bench.test_bench;futex_wake_parallel-7451: PASS (1.78 s)
 (10/12) perf_bench.py:perf_bench.test_bench;futex_requeue-08d0: PASS (1.79 s)
 (11/12) perf_bench.py:perf_bench.test_bench;futex_lock_pi-0ddb: PASS (10.75 s)
 (12/12) perf_bench.py:perf_bench.test_bench;all-46d4: PASS (1281.27 s)
RESULTS    : PASS 12 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 3726.42 s
```

Job log: with out yaml file
```
JOB ID     : eac534de75ad041e53efe90816d4126eb6ffac29
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2019-07-29T13.15-eac534d/job.log
 (1/1) perf_bench.py:perf_bench.test_bench: PASS (3830.32s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Comment by PraveenPenguin** [comment]
@nasastry have you tried this on python 3 , as going forward new test cases only goes in master branch which is python3 compatible or able to run on avocado 70 (or upstream ) as Travis pass for all python 3 version but still i think can you try on avocado 70

**Comment by PraveenPenguin** [comment]
@nasastryany update on this PR

**Comment by nasastry** [comment]
I will test and update this PR. Please do not close. Just busy with other things.

**Comment by nasastry** [comment]
Tested the code with Python3 and this applies to `master` branch.

```
root@zz256-lp1 perf]# avocado run perf_bench.py -m perf_bench.py.data/bench_options.yaml
Fetching assets from perf_bench.py:perf_bench.test_bench
JOB ID     : 12aeefa8cc928adb8f6b8b471e224aa602b219f5
JOB LOG    : /home/tests/results/job-2019-11-14T17.54-12aeefa/job.log
(01/12) perf_bench.py:perf_bench.test_bench;sched_messaging-5248: PASS (0.74 s)
(02/12) perf_bench.py:perf_bench.test_bench;sched_pipe-efdf: PASS (6.48 s)
(03/12) perf_bench.py:perf_bench.test_bench;mem_memcpy-1f13: PASS (0.64 s)
(04/12) perf_bench.py:perf_bench.test_bench;mem_memset-ad49: PASS (0.63 s)
(05/12) perf_bench.py:perf_bench.test_bench;numa_mem-10ab: PASS (550.46 s)
(06/12) perf_bench.py:perf_bench.test_bench;numa_all-07fc: PASS (551.84 s)
(07/12) perf_bench.py:perf_bench.test_bench;futex_hash-00dc: PASS (10.66 s)
(08/12) perf_bench.py:perf_bench.test_bench;futex_wake-5625: PASS (1.64 s)
(09/12) perf_bench.py:perf_bench.test_bench;futex_wake_parallel-7451: PASS (1.70 s)
(10/12) perf_bench.py:perf_bench.test_bench;futex_requeue-08d0: PASS (1.66 s)
(11/12) perf_bench.py:perf_bench.test_bench;futex_lock_pi-0ddb: PASS (10.65 s)
(12/12) perf_bench.py:perf_bench.test_bench;all-46d4: PASS (599.91 s)
RESULTS    : PASS 12 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1738.27 s
JOB HTML   : /home/tests/results/job-2019-11-14T17.54-12aeefa/results.html
```

@PraveenPenguin Please review. Thanks in advance.

**Pull request merged**
