### PR TITLE
fixed network lro test.

### PR DESCRIPTION
**Pull request by smruti77**
fixed this error, ERROR: [Errno 2] No such file or directory:
'/sys/class/net/enP6p1s0f0/device/name'. by changing interface
directory.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
[network_test.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4597200/network_test.log)
[network_test_vnic.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4597204/network_test_vnic.log)

**Comment by narasimhan-v** [comment]
@abdhaleegit review

**Comment by abdhaleegit** [comment]
tested on my setup.. LGTM

**Comment by narasimhan-v** [comment]
Thanks for the ACK @abdhaleegit

**Pull request merged**
