### PR TITLE
driver_param: support for mac addr as input

### PR DESCRIPTION
**Pull request by abdhaleegit**
In a contineous test environement setups where device names are not persistent accross os install, having a unique key like mac addr as yaml input which does not change across reboots, dlpar or os install with different linux flavours, also the legacy interface name and disk names as input works as is.

### CODE REVIEW

**Comment by FarooqAbdulla02** [comment]
LGTM

**Review by vaishnavibhat — CHANGES_REQUESTED** [review]
Hi Abdul ,

Most of the tests are having ERROR status when wrong interface / mac address is given for interface parm in yaml file.
Can this be rectified to show the status with CANCEL with the right message ?

# avocado run driver_parameter_orig.py -m driver_parameter_ibmveth.yaml --max-parallel-tasks=1
JOB ID     : 028f5df79bd931dbce93079cc0e67fce9619ca86
JOB LOG    : /root/new/avocado-fvt-wrapper/results/job-2023-07-27T09.52-028f5df/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/local/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (01/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_128-0f72: STARTED
 (01/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_128-0f72: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.53 s)
 (02/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_256-f0c5: STARTED
 (02/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_256-f0c5: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.60 s)
 (03/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_512-109f: STARTED
 (03/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_512-109f: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.69 s)
 (04/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_1024-25ec: STARTED
 (04/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_1024-25ec: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.65 s)
 (05/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_2048-c6d8: STARTED
 (05/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_2048-c6d8: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.54 s)
 (06/14) driver_parameter_orig.py:Moduleparameter.test;run-value-old_large_send-value-old_large_send _Y-dd3d: STARTED
 (06/14) driver_parameter_orig.py:Moduleparameter.test;run-value-old_large_send-value-old_large_send _Y-dd3d: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.55 s)
 (07/14) driver_parameter_orig.py:Moduleparameter.test;run-value-old_large_send-value-old_large_send _N-d544: STARTED
 (07/14) driver_parameter_orig.py:Moduleparameter.test;run-value-old_large_send-value-old_large_send _N-d544: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.51 s)
 (08/14) driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_128-c73a: STARTED
 (08/14) driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_128-c73a: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.60 s)
 (09/14) driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_256-1c38: STARTED
 (09/14) driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_256-1c38: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.57 s)
 (10/14) driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_512-ac5c: STARTED
 (10/14) driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_512-ac5c: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.63 s)
 (11/14) driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_1024-9440: STARTED
 (11/14) driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_1024-9440: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.54 s)
 (12/14) driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_2048-b368: STARTED
 (12/14) driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_2048-b368: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.57 s)
 (13/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_flush-value-rx_flush_0-796b: STARTED
 (13/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_flush-value-rx_flush_0-796b: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.65 s)
 (14/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_flush-value-rx_flush_1-5805: STARTED
 (14/14) driver_parameter_orig.py:Moduleparameter.test;run-value-rx_flush-value-rx_flush_1-5805: ERROR: 'Moduleparameter' object has no attribute 'load_unload_sleep_time' (0.67 s)
RESULTS    : PASS 0 | ERROR 14 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/new/avocado-fvt-wrapper/results/job-2023-07-27T09.52-028f5df/results.html
JOB TIME   : 40.23 s

Test summary:
driver_parameter_orig.py:Moduleparameter.test;run-value-old_large_send-value-old_large_send _N-d544: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-old_large_send-value-old_large_send _Y-dd3d: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_1024-25ec: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_128-0f72: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_2048-c6d8: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_256-f0c5: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-rx_copybreak-value-rx_copybreak_512-109f: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-rx_flush-value-rx_flush_0-796b: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-rx_flush-value-rx_flush_1-5805: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_1024-9440: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_128-c73a: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_2048-b368: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_256-1c38: ERROR
driver_parameter_orig.py:Moduleparameter.test;run-value-tx_copybreak-value-tx_copybreak_512-ac5c: ERROR

**Comment by abdhaleegit** [comment]
@vaishnavibhat Fixed now, it will fail cleanly in teardown when wrong mac address is given

**Comment by abdhaleegit** [comment]
```
avocado run --max-parallel-tasks=1 driver_parameter.py -m driver_parameter.py.data/driver_parameter_bnx2x.yaml
JOB ID     : 73e94cae8a104fe69dce66d5b644c37877bf9872
JOB LOG    : /home/ioci/logs/io_network/results/job-2023-08-28T06.53-73e94ca/job.log
 (01/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_0-4922: STARTED
 (01/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_0-4922: CANCEL: 02:5d:c7:45:86:05 interface is not available (0.01 s)
 (02/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_1-399e: STARTED
 (02/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_1-399e: CANCEL: 02:5d:c7:45:86:05 interface is not available (0.01 s)
 (03/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_8-3cb9: STARTED
 (03/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_8-3cb9: CANCEL: 02:5d:c7:45:86:05 interface is not available (0.01 s)
 (04/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_64-92bb: STARTED
 (04/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_64-92bb: CANCEL: 02:5d:c7:45:86:05 interface is not available (0.01 s)
 (05/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_1024-3b00: STARTED
 (05/16) driver_parameter.py:Moduleparameter.test;run-Test-num_queue-value-num_que_1024-3b00: CANCEL: 02:5d:c7:45:86:05 interface is not available (0.01 s)
 (06/16) driver_parameter.py:Moduleparameter.test;run-Test-disable_tpa-value-dis_tpa_1-f13c: STARTED
 (06/16) driver_parameter.py:Moduleparameter.test;run-Test-disable_tpa-value-dis_tpa_1-f13c: CANCEL: 02:5d:c7:45:86:05 interface is not available (0.01 s)
^C
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 10 | WARN 0 | INTERRUPT 0 | CANCEL 6
JOB HTML   : /home/ioci/logs/io_network/results/job-2023-08-28T06.53-73e94ca/results.html
JOB TIME   : 12.37 s
```

**Comment by abdhaleegit** [comment]
waiting for utils to merge

**Review by vaishnavibhat — APPROVED** [review]
LGTM!

**Review by PraveenPenguin — APPROVED** [review]

**Pull request merged**
