### PR TITLE
cpu/em_cpufreq: Improve parsing logic

### PR DESCRIPTION
**Pull request by sacsant**
Recent versions of ppc64_cpu utility displays average cpu
frequency in a different way :
avg	:	3.059 GHz

This breaks the existing parsing logic to identify freq_read
value and results in a testcase failure:
ERROR: could not convert string to float:  (7.02 s)

Change the parsing logic to match the avg frequency o/p string

Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>

### CODE REVIEW

**Comment by sacsant** [comment]
Before the fix:
 (1/1) cpu/em_cpufreq.py:Cpufreq.test: STARTED
 (1/1) cpu/em_cpufreq.py:Cpufreq.test:  ERROR: could not convert string to float:  (7.02 s)

Snippet from the debug log:
[stdlog] 2023-02-04 23:41:28,778 avocado.utils.process DEBUG| [stdout] Setting cpu: 78
[stdlog] 2023-02-04 23:41:28,778 avocado.utils.process DEBUG| [stdout] Setting cpu: 79
[stdlog] 2023-02-04 23:41:28,778 avocado.utils.process INFO | Command 'cpupower frequency-set -f 3059000' finished with 0 after 0.017675171s
[stdlog] 2023-02-04 23:41:28,778 avocado.utils.process INFO | Running 'ppc64_cpu --frequency -t 5| grep 'avg:' | awk '{print $2}''

The above line returns empty since it can't find string avg:

[stdlog] 2023-02-04 23:41:34,791 avocado.utils.process INFO | Command 'ppc64_cpu --frequency -t 5| grep 'avg:' | awk '{print $2}'' finished with 0 after 6.011844422s
[stdlog] 2023-02-04 23:41:34,791 avocado.test ERROR|
[stdlog] 2023-02-04 23:41:34,792 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2023-02-04 23:41:34,792 avocado.test ERROR|   File "/home/upstreamci/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/em_cpufreq.py", line 69, in test
[stdlog] 2023-02-04 23:41:34,792 avocado.test ERROR|     freq_read = float(freq_read) * (10 ** 6)
[stdlog] 2023-02-04 23:41:34,792 avocado.test ERROR| ValueError: could not convert string to float:
[stdlog] 2023-02-04 23:41:34,792 avocado.test ERROR|

After the fix:
 (1/1) cpu/em_cpufreq.py:Cpufreq.test: STARTED
 (1/1) cpu/em_cpufreq.py:Cpufreq.test: PASS (55.50 s)

**Review by abdhaleegit — CHANGES_REQUESTED** [review]
@sacsant should it handle based on older and new version, I tried on RHEL8.7 version
ppc64_cpu --frequency -t 5 | grep 'avg' | awk '{print $3}'
GHz

**Comment by sacsant** [comment]
> @sacsant should it handle based on older and new version, I tried on RHEL8.7 version powerpc-utils-1.3.6-11.108 ppc64_cpu --frequency -t 5 | grep 'avg' | awk '{print $3}' GHz
> 
> ppc64_cpu --frequency -t 5 | grep 'avg' | awk '{print $2}' 2.290

Good point. Will respin to retain backward compatibility.

**Comment by sacsant** [comment]
Without fix:

 (1/1) cpu/em_cpufreq.py:Cpufreq.test: STARTED
 (1/1) cpu/em_cpufreq.py:Cpufreq.test: ERROR: could not convert string to float:  (9.47 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

With fix:

 (1/1) cpu/em_cpufreq.py:Cpufreq.test: STARTED
 (1/1) cpu/em_cpufreq.py:Cpufreq.test: PASS (55.67 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Pull request merged**
