### PR TITLE
Initiating remote session before performance tune

### PR DESCRIPTION
**Pull request by vaishnavibhat**
Patch initiates remote session for enabling
irqbalance , setting rxtx values on peer lpar

### CODE REVIEW

**Comment by Naresh-ibm** [comment]
@vaishnavibhat add the run logs.

**Comment by abdhaleegit** [comment]
@vaishnavibhat any update on this ?

**Comment by vaishnavibhat** [comment]
avocado run network_virtualization.py:NetworkVirtualization.test_add -m network_virtualization.py.data/network_virtualization.yaml --max-parallel-tasks=1 
JOB ID     : ded354d009e1c00ea3b94144c6037e80b7ecda7e
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-07-09T09.01-ded354d/job.log
 (1/1) network_virtualization.py:NetworkVirtualization.test_add;run-742f: STARTED
 (1/1) network_virtualization.py:NetworkVirtualization.test_add;run-742f: FAIL: test failed,check dmesg log in debug log (28.64 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-07-09T09.01-ded354d/results.html
JOB TIME   : 55.33 s

Test summary:
1-network_virtualization.py:NetworkVirtualization.test_add;run-742f: FAIL

 dmesg --level=err
[ 7781.460504] ibmvnic 30000008: CRQ-init failed, -11
[ 7781.876580] ibmvnic 30000008: CRQ-init failed, -11
[ 7785.130511] ibmvnic 30000008: CRQ-init failed, -11
[ 7785.556792] ibmvnic 30000008: CRQ-init failed, -11

[debug.log](https://github.com/user-attachments/files/16144467/debug.log)
[job.log](https://github.com/user-attachments/files/16144468/job.log)

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Pull request merged**
