### PR TITLE
V2

### PR DESCRIPTION
**Pull request by sandeepkarthikeyan**
[job.log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/544083/job.log.txt)

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@sandeepkarthikeyan  Could you please squash the commits into one commit only?

**Comment by PraveenPenguin** [comment]
as well please add good commit message it will help to pass travis check

**Comment by PraveenPenguin** [comment]
as well mentioned the test name in subject with V2

**Comment by sandeepkarthikeyan** [comment]
Raised a new pull request #127

**Pull request closed without merging**
