### PR TITLE
NVMe test fixes

### PR DESCRIPTION
**Pull request by narasimhan-v**
Added verification of written data to nvme read command.
Nvme write test uses the above feature to verify write command.

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@PraveenPenguin I have rebased.

**Comment by PraveenPenguin** [comment]
can you please attach job log in this PR

**Comment by narasimhan-v** [comment]
@PraveenPenguin for some reason, latest nvme-cli fails in `make install`. So, I have commented the make steps to run this. Should be fine for verifying this patch.

[job_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/503447/job_log.txt)

**Comment by narasimhan-v** [comment]
@PraveenPenguin please wait on this PR. I am exploring the tool, to add some more features. And this commands in this PR could be changed as well.

**Comment by PraveenPenguin** [comment]
@narasimhan-v sure

**Comment by narasimhan-v** [comment]
Added more functionalities to the test, and opened PR #77

**Pull request closed without merging**
