### PR TITLE
python3 migration

### PR DESCRIPTION
**Pull request by preetithakur**
fixed tc to resolve str error

Signed

Signed-off-by: Preeti Thakur <preeti.thakur@in.ibm.com>

### CODE REVIEW

**Comment by preetithakur** [comment]
avocado run valgrind.py
JOB ID     : 2d0b100625b5080a23b3ccab4448229c9bd2f813
JOB LOG    : /root/avocado/job-results/job-2019-10-04T01.50-2d0b100/job.log
 (1/1) valgrind.py:Valgrind.test: PASS (1835.43 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1835.73 s

**Comment by PraveenPenguin** [comment]
@preetithakur please include other toolchain test case which is applicable

**Comment by preetithakur** [comment]
no test case with similar issue now

**Comment by preetithakur** [comment]
please merge

**Comment by PraveenPenguin** [comment]
@preetithakur seems  me gcc and systemtap test also has the same issue that also needs to adopt as python3

**Comment by harish-24** [comment]
@preetithakur If you are still pursuing, please reopen with the fixes.

**Pull request closed without merging**
