### PR TITLE
Dlpar enhancements and drmgr

### PR DESCRIPTION
**Pull request by narasimhan-v**

### CODE REVIEW

**Comment by narasimhan-v** [comment]
```
# avocado run dlpar.py -m dlpar.py.data/dlpar.yaml 
JOB ID     : d49b4c94fb0f6bbe97088ea05735a843c0fd5211
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2018-07-03T09.39-d49b4c9/job.log
 (1/2) dlpar.py:DlparPci.test_dlpar;lpar_2-url-ec60: PASS (137.33 s)
 (2/2) dlpar.py:DlparPci.test_drmgr;lpar_2-url-ec60: FAIL (37.83 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 176.00 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2018-07-03T09.39-d49b4c9/results.html
```
```
# avocado run dlpar.py:DlparPci.test_drmgr -m dlpar.py.data/dlpar.yaml JOB ID     : 9fe5b1ee5766a807c34d13b73642e00ceed93207
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2018-07-03T09.44-9fe5b1e/job.log
 (1/1) dlpar.py:DlparPci.test_drmgr;lpar_2-url-ec60: PASS (184.23 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 184.80 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2018-07-03T09.44-9fe5b1e/results.html
```

**Comment by narasimhan-v** [comment]
Relevant snippet from job.log:
```
2018-07-03 09:51:51,697 dlpar            L0146 INFO | Running the command on hmc uname -a
2018-07-03 09:51:51,800 dlpar            L0146 INFO | Running the command on hmc lshwres -r io -m ltczep6 --rsubtype slot --filter lpar_names=ltczep6-lp6-sim -F drc_index,lpar_id,drc_name | grep -i U78D4.001.CSS10EK-P1-C10
2018-07-03 09:51:51,914 dlpar            L0120 INFO | lpar_id : 6, loc_code: U78D4.001.CSS10EK-P1-C10, drc_index: 21010018
2018-07-03 09:51:51,915 process          L0554 INFO | Running 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -r'
2018-07-03 09:52:08,756 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:52:08,756 process          L0642 INFO | Command 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -r' finished with 0 after 16.8388900757s
2018-07-03 09:52:08,757 process          L0386 DEBUG| [stdout] been set to the identify state. Press Enter to continue
2018-07-03 09:52:08,757 process          L0386 DEBUG| [stdout] or enter x to exit.
2018-07-03 09:52:08,757 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:52:08,757 process          L0386 DEBUG| [stdout] been set to the action state. Remove the PCI card
2018-07-03 09:52:08,758 process          L0386 DEBUG| [stdout] from the identified slot and press Enter to continue.
2018-07-03 09:52:08,780 process          L0554 INFO | Running 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -a'
2018-07-03 09:52:28,420 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:52:28,421 process          L0642 INFO | Command 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -a' finished with 0 after 19.6381120682s
2018-07-03 09:52:28,422 process          L0386 DEBUG| [stdout] been set to the identify state. Press Enter to continue
2018-07-03 09:52:28,422 process          L0386 DEBUG| [stdout] or enter x to exit.
2018-07-03 09:52:28,423 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:52:28,423 process          L0386 DEBUG| [stdout] been set to the action state. Insert the PCI card
2018-07-03 09:52:28,423 process          L0386 DEBUG| [stdout] into the identified slot, connect any devices to be
2018-07-03 09:52:28,424 process          L0386 DEBUG| [stdout] configured and press Enter to continue. Enter x to exit.
2018-07-03 09:52:28,458 process          L0554 INFO | Running 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -r'
2018-07-03 09:52:45,438 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:52:45,438 process          L0642 INFO | Command 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -r' finished with 0 after 16.9689378738s
2018-07-03 09:52:45,439 process          L0386 DEBUG| [stdout] been set to the identify state. Press Enter to continue
2018-07-03 09:52:45,439 process          L0386 DEBUG| [stdout] or enter x to exit.
2018-07-03 09:52:45,439 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:52:45,439 process          L0386 DEBUG| [stdout] been set to the action state. Remove the PCI card
2018-07-03 09:52:45,439 process          L0386 DEBUG| [stdout] from the identified slot and press Enter to continue.
2018-07-03 09:52:45,463 process          L0554 INFO | Running 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -a'
2018-07-03 09:53:05,111 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:53:05,112 process          L0642 INFO | Command 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -a' finished with 0 after 19.6454639435s
2018-07-03 09:53:05,112 process          L0386 DEBUG| [stdout] been set to the identify state. Press Enter to continue
2018-07-03 09:53:05,112 process          L0386 DEBUG| [stdout] or enter x to exit.
2018-07-03 09:53:05,113 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:53:05,113 process          L0386 DEBUG| [stdout] been set to the action state. Insert the PCI card
2018-07-03 09:53:05,113 process          L0386 DEBUG| [stdout] into the identified slot, connect any devices to be
2018-07-03 09:53:05,114 process          L0386 DEBUG| [stdout] configured and press Enter to continue. Enter x to exit.
2018-07-03 09:53:05,147 process          L0554 INFO | Running 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -R'
2018-07-03 09:53:41,700 process          L0386 DEBUG| [stderr] Rotating logs...
2018-07-03 09:53:41,701 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:53:41,701 process          L0642 INFO | Command 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -R' finished with 0 after 36.5370998383s
2018-07-03 09:53:41,702 process          L0386 DEBUG| [stdout] been set to the identify state. Press Enter to continue
2018-07-03 09:53:41,703 process          L0386 DEBUG| [stdout] or enter x to exit.
2018-07-03 09:53:41,703 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:53:41,704 process          L0386 DEBUG| [stdout] been set to the action state. Replace the PCI card
2018-07-03 09:53:41,704 process          L0386 DEBUG| [stdout] in the identified slot and press Enter to continue.
2018-07-03 09:53:41,704 process          L0386 DEBUG| [stdout] Enter x to exit. Exiting now leaves the PCI slot
2018-07-03 09:53:41,705 process          L0386 DEBUG| [stdout] in the removed state.
2018-07-03 09:53:41,752 process          L0554 INFO | Running 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -R'
2018-07-03 09:54:18,370 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:54:18,371 process          L0642 INFO | Command 'echo -e "
" | drmgr -c pci -s U78D4.001.CSS10EK-P1-C10 -R' finished with 0 after 36.6040248871s
2018-07-03 09:54:18,371 process          L0386 DEBUG| [stdout] been set to the identify state. Press Enter to continue
2018-07-03 09:54:18,372 process          L0386 DEBUG| [stdout] or enter x to exit.
2018-07-03 09:54:18,372 process          L0386 DEBUG| [stdout] The visual indicator for the specified PCI slot has
2018-07-03 09:54:18,373 process          L0386 DEBUG| [stdout] been set to the action state. Replace the PCI card
2018-07-03 09:54:18,373 process          L0386 DEBUG| [stdout] in the identified slot and press Enter to continue.
2018-07-03 09:54:18,373 process          L0386 DEBUG| [stdout] Enter x to exit. Exiting now leaves the PCI slot
2018-07-03 09:54:18,374 process          L0386 DEBUG| [stdout] in the removed state.
2018-07-03 09:54:18,693 test             L0300 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2018-07-03 09:54:18,694 test             L0300 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2018-07-03 09:54:18,694 test             L0300 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2018-07-03 09:54:18,708 test             L1005 INFO | PASS 1-dlpar.py:DlparPci.test_drmgr;lpar_2-url-ec60
```

**Comment by vrbagalkote** [comment]
commit message is missing, but apart from it looks good to me.

**Comment by narasimhan-v** [comment]
@vrbagalkore not missing, but since there are 2 commits in the PR, github does not automatically show them in the opening post. We will need to manually edit to add the message for the convenience of the reviewers :-)

**Pull request merged**
