### PR TITLE
dlpar for sriov adapter

### PR DESCRIPTION
**Pull request by vaishnavibhat**
dlpar function is enhanced for sriov adapters

Signed-off-by: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by vaishnavibhat** [comment]
#1700 
avocado run dlpar.py:DlparPci.test_dlpar -m dlpar.py.data/dlpar.yaml 
/usr/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/plugins/run.py:287: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast, keep-tmp and ignore-missing-references.
  FutureWarning)
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : 9826e9453f0625143560a4d1999ec1a457a1d207
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-05-07T11.46-9826e94/job.log
 (1/1) dlpar.py:DlparPci.test_dlpar;lpar_2-url-713b: PASS (57.40 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 57.49 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-05-07T11.46-9826e94/results.html

dmesg
[698065.044045] be2net c005:01:00.0: Cannot set rx filter flags 0x1ab8
[698065.044048] be2net c005:01:00.0: Interface is capable of 0x1bb4 flags only
[698067.590959] pci c005:01:00.0: Removing from iommu group 1
[698072.591168] pci_bus c005:01: busn_res: [bus 01] is released
[698072.591229] rpadlpar_io: slot PHB 4357 removed
[698077.404236] PCI host bridge /pci@80000002900c005  ranges:
[698077.404241]  MEM 0x0000040009800000..0x0000040009bfffff -> 0x0006083f85800000 
[698077.406358] PCI host bridge to bus c005:01
[698077.406362] pci_bus c005:01: root bus resource [mem 0x40009800000-0x40009bfffff] (bus address [0x6083f85800000-0x6083f85bfffff])
[698077.406365] pci_bus c005:01: root bus resource [bus 01]
[698077.407008] pci c005:01:00.0: enabling Extended Tags
[698077.407462] pci c005:01:00.0: No hypervisor support for SR-IOV on this device, IOV BARs disabled.
[698077.411964] pci c005:01:00.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown speed x0 link at c005:01:00.0 (capable of 63.008 Gb/s with 8 GT/s x8 link)
[698077.413044] pci c005:01:00.0: Adding to iommu group 1
[698077.413173] be2net c005:01:00.0: be2net version is 12.0.0.0
[698077.413226] be2net c005:01:00.0: enabling device (0000 -> 0002)
[698077.414251] be2net c005:01:00.0: PCIe error reporting enabled
[698078.800252] be2net c005:01:00.0: FW config: function_mode=0x2, function_caps=0x874006
[698078.940251] be2net c005:01:00.0: Max: txqs 4, rxqs 5, rss 4, eqs 4, vfs 0
[698078.940253] be2net c005:01:00.0: Max: uc-macs 1, mc-macs 10, vlans 1
[698079.019962] be2net c005:01:00.0: enabled 4 MSI-x vector(s) for NIC
[698079.820253] be2net c005:01:00.0: created 4 TX queue(s)
[698080.120247] be2net c005:01:00.0: created 5 RX queue(s)
[698080.243286] be2net c005:01:00.0: FW version is 11.4.415.28
[698080.244294] be2net c005:01:00.0: HW Flow control - TX:0 RX:0
[698080.244554] be2net c005:01:00.0: Emulex OneConnect(Lancer): VF  port 1
[698080.244593] rpadlpar_io: slot PHB 4357 added
[698080.246635] be2net c005:01:00.0 eth4: renamed from eth1
[698080.323046] be2net c005:01:00.0 eth4: Link is Up
[698080.335915] be2net c005:01:00.0 eth4: Link is Up


[dlpar_sriov.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4591086/dlpar_sriov.log)

**Comment by vaishnavibhat** [comment]
Hi, 

This patch is successful in doing a dlpar operation for dlpar.py:DlparPci.test_dlpar test. Working on PHB dlpar.
#avocado list dlpar.py
INSTRUMENTED dlpar.py:DlparPci.test_dlpar
INSTRUMENTED dlpar.py:DlparPci.test_drmgr_pci
INSTRUMENTED dlpar.py:DlparPci.test_drmgr_phb

**Comment by narasimhan-v** [comment]
@vaishnavibhat @abdhaleegit Did we decide we want same script for dlpar of virtual devices ?

**Comment by abdhaleegit** [comment]
> @vaishnavibhat @abdhaleegit Did we decide we want same script for dlpar of virtual devices ?

Yes we decided to have separate script for virtual non pci devices.. it is already pushed

so for all pci devices this will be common scrip.. though sriov is virtual device.. it has pci bus id.. so is the reason to use same pci dlpar

**Comment by abdhaleegit** [comment]
@vaishnavibhat please run this once on a some other physical adapter and upload the logs.. make not broken for old code

**Comment by narasimhan-v** [comment]
> @vaishnavibhat please run this once on a some other physical adapter and upload the logs.. make not broken for old code

@vaishnavibhat any update here ?

**Comment by vaishnavibhat** [comment]
> > @vaishnavibhat please run this once on a some other physical adapter and upload the logs.. make not broken for old code
> 
> @vaishnavibhat any update here ?

]# avocado run dlpar.py -m dlpar.yaml 
/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/plugins/run.py:286: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  FutureWarning)
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : 2152c0bb3840637ec98e78d9c0e3f23181ceb3fe
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-05-29T06.05-2152c0b/job.log
 (1/3) dlpar.py:DlparPci.test_dlpar;lpar_2-url-5eb9: PASS (114.15 s)
 (2/3) dlpar.py:DlparPci.test_drmgr_pci;lpar_2-url-5eb9: FAIL: drmgr operation r fails for PCI (39.11 s)
 (3/3) dlpar.py:DlparPci.test_drmgr_phb;lpar_2-url-5eb9: PASS (91.91 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 245.40 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-05-29T06.05-2152c0b/results.html


[dlpar.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4701117/dlpar.log)

**Pull request merged**
