### PR TITLE
[backport] Added the Manual pre-requisite steps for avago9361

### PR DESCRIPTION
**Pull request by manvanthar**
Added the Manual pre-requisite steps for avago9361

Signed-off-by: Manvanthara Puttashankar <manvanth@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@manvanthar Can you point the patch for py2-lts please ?

**Comment by manvanthar** [comment]
@narasimhan-v  PR 1368

**Comment by narasimhan-v** [comment]
#1368

**Comment by narasimhan-v** [comment]
@manvanthar Can you attach job.log here ? We are ready to merge.

**Comment by manvanthar** [comment]
2019-11-09 13:19:06,343 sysinfo          L0408 DEBUG| File /etc/avocado/sysinfo/commands does not exist.
2019-11-09 13:19:06,343 sysinfo          L0419 DEBUG| File /etc/avocado/sysinfo/files does not exist.
2019-11-09 13:19:06,343 sysinfo          L0447 DEBUG| File /etc/avocado/sysinfo/profilers does not exist.
2019-11-09 13:19:06,344 sysinfo          L0505 INFO | System log file not found (looked for ['/var/log/messages', '/var/log/syslog', '/var/log/system.log'])
2019-11-09 13:19:06,572 job              L0379 INFO | Command line: /usr/local/bin/avocado run avago9361_vd.py -m avago9361_vd.py.data/avago9361_vd.yaml
2019-11-09 13:19:06,572 job              L0380 INFO |
2019-11-09 13:19:06,572 job              L0414 INFO | Avocado version: 72.0
2019-11-09 13:19:06,573 job              L0415 INFO |
2019-11-09 13:19:06,573 job              L0419 INFO | Config files read (in order):
2019-11-09 13:19:06,573 job              L0421 INFO | /usr/local/lib/python3.6/site-packages/avocado_framework-72.0-py3.6.egg/avocado/etc/avocado/avocado.conf
2019-11-09 13:19:06,573 job              L0421 INFO | /usr/local/lib/python3.6/site-packages/avocado_framework-72.0-py3.6.egg/avocado/etc/avocado/conf.d/gdb.conf
2019-11-09 13:19:06,573 job              L0421 INFO | /usr/local/lib/python3.6/site-packages/avocado_framework-72.0-py3.6.egg/avocado/etc/avocado/conf.d/glib.conf
2019-11-09 13:19:06,573 job              L0421 INFO | /usr/local/lib/python3.6/site-packages/avocado_framework-72.0-py3.6.egg/avocado/etc/avocado/conf.d/jobscripts.conf
2019-11-09 13:19:06,573 job              L0421 INFO | /usr/local/lib/python3.6/site-packages/avocado_framework-72.0-py3.6.egg/avocado/etc/avocado/conf.d/result_upload.conf
2019-11-09 13:19:06,573 job              L0421 INFO | /usr/local/lib/python3.6/site-packages/avocado_framework-72.0-py3.6.egg/avocado/etc/avocado/conf.d/resultsdb.conf
2019-11-09 13:19:06,573 job              L0421 INFO | /root/.config/avocado/avocado.conf
2019-11-09 13:19:06,573 job              L0422 INFO |
2019-11-09 13:19:06,573 job              L0424 INFO | Avocado config:
2019-11-09 13:19:06,574 job              L0433 INFO | Section.Key                              Value
2019-11-09 13:19:06,574 job              L0433 INFO | datadir.paths.base_dir                   /root/tests
2019-11-09 13:19:06,574 job              L0433 INFO | datadir.paths.test_dir                   /root/tests/tests
2019-11-09 13:19:06,575 job              L0433 INFO | datadir.paths.data_dir                   /root/tests/data
2019-11-09 13:19:06,575 job              L0433 INFO | datadir.paths.logs_dir                   /root/tests/results
2019-11-09 13:19:06,575 job              L0433 INFO | sysinfo.collect.enabled                  True
2019-11-09 13:19:06,575 job              L0433 INFO | sysinfo.collect.commands_timeout         -1
2019-11-09 13:19:06,575 job              L0433 INFO | sysinfo.collect.installed_packages       False
2019-11-09 13:19:06,575 job              L0433 INFO | sysinfo.collect.profiler                 True
2019-11-09 13:19:06,575 job              L0433 INFO | sysinfo.collect.locale                   C
2019-11-09 13:19:06,575 job              L0433 INFO | sysinfo.collect.per_test                 True
2019-11-09 13:19:06,575 job              L0433 INFO | sysinfo.collectibles.commands            /etc/avocado/sysinfo/commands
2019-11-09 13:19:06,575 job              L0433 INFO | sysinfo.collectibles.files               /etc/avocado/sysinfo/files
2019-11-09 13:19:06,575 job              L0433 INFO | sysinfo.collectibles.profilers           /etc/avocado/sysinfo/profilers
2019-11-09 13:19:06,575 job              L0433 INFO | runner.output.colored                    True
2019-11-09 13:19:06,576 job              L0433 INFO | runner.output.utf8
2019-11-09 13:19:06,576 job              L0433 INFO | runner.timeout.after_interrupted         60
2019-11-09 13:19:06,576 job              L0433 INFO | runner.timeout.process_died              10
2019-11-09 13:19:06,576 job              L0433 INFO | runner.timeout.process_alive             60
2019-11-09 13:19:06,576 job              L0433 INFO | remoter.behavior.reject_unknown_hosts    False
2019-11-09 13:19:06,576 job              L0433 INFO | remoter.behavior.disable_known_hosts     False
2019-11-09 13:19:06,576 job              L0433 INFO | job.output.loglevel                      debug
2019-11-09 13:19:06,576 job              L0433 INFO | restclient.connection.hostname           localhost
2019-11-09 13:19:06,576 job              L0433 INFO | restclient.connection.port               9405
2019-11-09 13:19:06,576 job              L0433 INFO | restclient.connection.username
2019-11-09 13:19:06,576 job              L0433 INFO | restclient.connection.password
2019-11-09 13:19:06,576 job              L0433 INFO | plugins.disable                          []
2019-11-09 13:19:06,577 job              L0433 INFO | plugins.skip_broken_plugin_notification  []
2019-11-09 13:19:06,577 job              L0433 INFO | plugins.loaders                          ['file', '@DEFAULT']
2019-11-09 13:19:06,577 job              L0433 INFO | plugins.resolver.order                   ['avocado-instrumented', 'python-unittest', 'glib', 'robot', 'exec-test']
2019-11-09 13:19:06,577 job              L0433 INFO | gdb.paths.gdb                            /usr/bin/gdb
2019-11-09 13:19:06,577 job              L0433 INFO | gdb.paths.gdbserver                      /usr/bin/gdbserver
2019-11-09 13:19:06,577 job              L0433 INFO | plugins.glib.unsafe                      False
2019-11-09 13:19:06,577 job              L0433 INFO | plugins.jobscripts.pre                   /etc/avocado/scripts/job/pre.d/
2019-11-09 13:19:06,577 job              L0433 INFO | plugins.jobscripts.post                  /etc/avocado/scripts/job/post.d/
2019-11-09 13:19:06,577 job              L0433 INFO | plugins.jobscripts.warn_non_existing_dir False
2019-11-09 13:19:06,577 job              L0433 INFO | plugins.jobscripts.warn_non_zero_status  True
2019-11-09 13:19:06,577 job              L0434 INFO |
2019-11-09 13:19:06,577 job              L0437 INFO | Avocado Data Directories:
2019-11-09 13:19:06,578 job              L0438 INFO |
2019-11-09 13:19:06,578 job              L0439 INFO | base     /root/tests
2019-11-09 13:19:06,578 job              L0440 INFO | tests    /root/tests/tests
2019-11-09 13:19:06,578 job              L0441 INFO | data     /root/tests/data
2019-11-09 13:19:06,578 job              L0442 INFO | logs     /root/tests/results/job-2019-11-09T13.19-4297d4d
2019-11-09 13:19:06,578 job              L0443 INFO |
2019-11-09 13:19:06,579 job              L0449 INFO | Multiplex tree representation:
2019-11-09 13:19:06,579 job              L0449 INFO |  \-- run
2019-11-09 13:19:06,579 job              L0449 INFO |       |-- Scenario
2019-11-09 13:19:06,579 job              L0449 INFO |       \-- raid_level
2019-11-09 13:19:06,579 job              L0449 INFO |            #== r0
2019-11-09 13:19:06,579 job              L0449 INFO |            #== r1
2019-11-09 13:19:06,579 job              L0449 INFO |
2019-11-09 13:19:06,579 job              L0449 INFO | Multiplex variants (2):
2019-11-09 13:19:06,580 job              L0449 INFO | Variant Scenario-r0-2af5:    /run/Scenario, /run/raid_level/r0
2019-11-09 13:19:06,580 job              L0449 INFO | Variant Scenario-r1-e663:    /run/Scenario, /run/raid_level/r1
2019-11-09 13:19:06,580 job              L0452 INFO | Temporary dir: /var/tmp/avocado_3iehq5t_/avocado_job_vuk2ti2n
2019-11-09 13:19:06,580 job              L0453 INFO |
2019-11-09 13:19:06,580 job              L0371 INFO | Job ID: 4297d4d9c2e105cff9ae70724d33ff8c5bcd9052
2019-11-09 13:19:06,580 job              L0374 INFO |
2019-11-09 13:19:06,596 sysinfo          L0408 DEBUG| File /etc/avocado/sysinfo/commands does not exist.
2019-11-09 13:19:06,596 sysinfo          L0419 DEBUG| File /etc/avocado/sysinfo/files does not exist.
2019-11-09 13:19:06,596 sysinfo          L0447 DEBUG| File /etc/avocado/sysinfo/profilers does not exist.
2019-11-09 13:19:06,597 sysinfo          L0505 INFO | System log file not found (looked for ['/var/log/messages', '/var/log/syslog', '/var/log/system.log'])
2019-11-09 13:19:06,604 test             L0391 INFO | INIT 01-avago9361_vd.py:Avago9361.test_createall;Scenario-r0-2af5
2019-11-09 13:19:06,605 parameters       L0143 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
2019-11-09 13:19:06,605 test             L0423 DEBUG| Test metadata:
2019-11-09 13:19:06,605 test             L0425 DEBUG|   filename: /root/avogo9361_python3/avocado-misc-tests/io/disk/Avago_storage_adapter/avago9361_vd.py
2019-11-09 13:19:06,605 test             L0431 DEBUG|   teststmpdir: /var/tmp/avocado_55pxvk8o
2019-11-09 13:19:06,605 test             L0432 DEBUG|   workdir: /var/tmp/avocado_3iehq5t_/avocado_job_vuk2ti2n/01-avago9361_vd.py_Avago9361.test_createall_Scenario-r0-2af5
2019-11-09 13:19:06,617 test             L0617 INFO | START 01-avago9361_vd.py:Avago9361.test_createall;Scenario-r0-2af5
2019-11-09 13:19:06,617 test             L0297 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2019-11-09 13:19:06,626 parameters       L0143 DEBUG| PARAMS (key=controller, path=*, default=0) => 0
2019-11-09 13:19:06,626 parameters       L0143 DEBUG| PARAMS (key=tool_location, path=*, default=None) => '/root/storcli64'
2019-11-09 13:19:06,627 parameters       L0143 DEBUG| PARAMS (key=vd_disk, path=*, default=None) => '252:6 252:5'
2019-11-09 13:19:06,627 parameters       L0143 DEBUG| PARAMS (key=raid_level, path=*, default=0) => 'r0'
2019-11-09 13:19:06,627 parameters       L0143 DEBUG| PARAMS (key=size, path=*, default=all) => 10000
2019-11-09 13:19:06,627 parameters       L0143 DEBUG| PARAMS (key=on_off, path=*, default=None) => 'e252/s6'
2019-11-09 13:19:06,627 parameters       L0143 DEBUG| PARAMS (key=hotspare, path=*, default=None) => 'e252/s2'
2019-11-09 13:19:06,628 parameters       L0143 DEBUG| PARAMS (key=add_vd_disk, path=*, default=None) => '252:s7 252:s3'
2019-11-09 13:19:06,628 process          L0605 INFO | Running '/root/storcli64 /c0/vall delete force'
2019-11-09 13:19:07,263 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:19:07,263 process          L0687 INFO | Command '/root/storcli64 /c0/vall delete force' finished with 0 after 0.6340274810791016s
2019-11-09 13:19:07,264 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:19:07,264 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:19:07,264 process          L0437 DEBUG| [stdout] Description = Delete VD succeeded
2019-11-09 13:19:07,264 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,265 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,266 process          L0605 INFO | Running '/root/storcli64 /c0 set jbod=off'
2019-11-09 13:19:07,411 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:19:07,411 process          L0687 INFO | Command '/root/storcli64 /c0 set jbod=off' finished with 0 after 0.14283084869384766s
2019-11-09 13:19:07,411 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:19:07,411 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:19:07,412 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:19:07,412 process          L0437 DEBUG| [stdout] Description = None
2019-11-09 13:19:07,412 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,412 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,412 process          L0437 DEBUG| [stdout] Controller Properties :
2019-11-09 13:19:07,412 process          L0437 DEBUG| [stdout] =====================
2019-11-09 13:19:07,413 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,413 process          L0437 DEBUG| [stdout] ----------------
2019-11-09 13:19:07,413 process          L0437 DEBUG| [stdout] Ctrl_Prop Value
2019-11-09 13:19:07,413 process          L0437 DEBUG| [stdout] ----------------
2019-11-09 13:19:07,413 process          L0437 DEBUG| [stdout] JBOD      OFF
2019-11-09 13:19:07,414 process          L0437 DEBUG| [stdout] ----------------
2019-11-09 13:19:07,414 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,414 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,414 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,416 process          L0605 INFO | Running '/root/storcli64 /c0/eall/sall set good force'
2019-11-09 13:19:07,421 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:19:07,421 process          L0687 INFO | Command '/root/storcli64 /c0/eall/sall set good force' finished with 255 after 0.003440380096435547s
2019-11-09 13:19:07,422 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:19:07,422 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:19:07,422 process          L0437 DEBUG| [stdout] Status = Failure
2019-11-09 13:19:07,422 process          L0437 DEBUG| [stdout] Description = Set Drive Good Failed.
2019-11-09 13:19:07,422 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,423 process          L0437 DEBUG| [stdout] Detailed Status :
2019-11-09 13:19:07,423 process          L0437 DEBUG| [stdout] ===============
2019-11-09 13:19:07,423 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,423 process          L0437 DEBUG| [stdout] -------------------------------------------------
2019-11-09 13:19:07,423 process          L0437 DEBUG| [stdout] Drive       Status  ErrCd ErrMsg
2019-11-09 13:19:07,423 process          L0437 DEBUG| [stdout] -------------------------------------------------
2019-11-09 13:19:07,424 process          L0437 DEBUG| [stdout] /c0/e252/s2 Failure   255 Operation not allowed.
2019-11-09 13:19:07,424 process          L0437 DEBUG| [stdout] /c0/e252/s3 Failure   255 Operation not allowed.
2019-11-09 13:19:07,424 process          L0437 DEBUG| [stdout] /c0/e252/s5 Failure   255 Operation not allowed.
2019-11-09 13:19:07,424 process          L0437 DEBUG| [stdout] /c0/e252/s6 Failure   255 Operation not allowed.
2019-11-09 13:19:07,424 process          L0437 DEBUG| [stdout] /c0/e252/s7 Failure   255 Operation not allowed.
2019-11-09 13:19:07,425 process          L0437 DEBUG| [stdout] -------------------------------------------------
2019-11-09 13:19:07,425 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,425 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,425 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,426 avago9361_vd     L0106 INFO | SETTING UP ENVIRONMENT DONE: Ignore above Error(If any)
2019-11-09 13:19:07,427 process          L0605 INFO | Running '/root/storcli64 /c0 add vd r0 size=10000 drives=252:6,252:5 WT nora direct                    strip=64'
2019-11-09 13:19:07,624 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:19:07,624 process          L0687 INFO | Command '/root/storcli64 /c0 add vd r0 size=10000 drives=252:6,252:5 WT nora direct                    strip=64' finished with 0 after 0.19565224647521973s
2019-11-09 13:19:07,625 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:19:07,625 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:19:07,625 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:19:07,625 process          L0437 DEBUG| [stdout] Description = Add VD Succeeded.
2019-11-09 13:19:07,625 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,626 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:07,627 process          L0605 INFO | Running '/root/storcli64 /c0/vall show'
2019-11-09 13:19:08,545 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:19:08,545 process          L0687 INFO | Command '/root/storcli64 /c0/vall show' finished with 0 after 0.9159579277038574s
2019-11-09 13:19:08,545 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:19:08,546 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:19:08,546 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:19:08,546 process          L0437 DEBUG| [stdout] Description = None
2019-11-09 13:19:08,546 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:08,546 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:08,547 process          L0437 DEBUG| [stdout] Virtual Drives :
2019-11-09 13:19:08,547 process          L0437 DEBUG| [stdout] ==============
2019-11-09 13:19:08,547 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:08,547 process          L0437 DEBUG| [stdout] -------------------------------------------------------------
2019-11-09 13:19:08,547 process          L0437 DEBUG| [stdout] DG/VD TYPE  State Access Consist Cache Cac sCC     Size Name
2019-11-09 13:19:08,547 process          L0437 DEBUG| [stdout] -------------------------------------------------------------
2019-11-09 13:19:08,548 process          L0437 DEBUG| [stdout] 0/0   RAID0 Optl  RW     Yes     NRWTD -   OFF 9.765 GB
2019-11-09 13:19:08,548 process          L0437 DEBUG| [stdout] -------------------------------------------------------------
2019-11-09 13:19:08,548 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:08,548 process          L0437 DEBUG| [stdout] EID=Enclosure Device ID| VD=Virtual Drive| DG=Drive Group|Rec=Recovery
2019-11-09 13:19:08,548 process          L0437 DEBUG| [stdout] Cac=CacheCade|OfLn=OffLine|Pdgd=Partially Degraded|Dgrd=Degraded
2019-11-09 13:19:08,549 process          L0437 DEBUG| [stdout] Optl=Optimal|RO=Read Only|RW=Read Write|HD=Hidden|TRANS=TransportReady|B=Blocked|
2019-11-09 13:19:08,549 process          L0437 DEBUG| [stdout] Consist=Consistent|R=Read Ahead Always|NR=No Read Ahead|WB=WriteBack|
2019-11-09 13:19:08,549 process          L0437 DEBUG| [stdout] AWB=Always WriteBack|WT=WriteThrough|C=Cached IO|D=Direct IO|sCC=Scheduled
2019-11-09 13:19:08,549 process          L0437 DEBUG| [stdout] Check Consistency
2019-11-09 13:19:08,549 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:08,549 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:08,550 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:08,551 process          L0605 INFO | Running '/root/storcli64 /c0/vall delete force'
2019-11-09 13:19:08,567 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:19:08,567 process          L0687 INFO | Command '/root/storcli64 /c0/vall delete force' finished with 0 after 0.014410257339477539s
2019-11-09 13:19:08,567 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:19:08,568 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:19:08,568 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:19:08,568 process          L0437 DEBUG| [stdout] Description = Delete VD succeeded
2019-11-09 13:19:08,568 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:08,568 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:08,570 process          L0605 INFO | Running '/root/storcli64 /c0 add vd r0 size=10000 drives=252:6,252:5 WT nora direct                    strip=128'
2019-11-09 13:19:08,896 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:19:08,896 process          L0687 INFO | Command '/root/storcli64 /c0 add vd r0 size=10000 drives=252:6,252:5 WT nora direct                    strip=128' finished with 0 after 0.3248941898345947s
2019-11-09 13:19:08,897 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:19:08,897 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:19:08,897 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:19:08,897 process          L0437 DEBUG| [stdout] Description = Add VD Succeeded.
2019-11-09 13:19:08,898 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:08,899 process          L0605 INFO | Running '/root/storcli64 /c0/vall show'
2019-11-09 13:19:09,833 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:19:09,834 process          L0687 INFO | Command '/root/storcli64 /c0/vall show' finished with 0 after 0.9322302341461182s
2019-11-09 13:19:09,834 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:19:09,834 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:19:09,834 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:19:09,834 process          L0437 DEBUG| [stdout] Description = None
2019-11-09 13:19:09,835 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:09,835 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:09,835 process          L0437 DEBUG| [stdout] Virtual Drives :
2019-11-09 13:19:09,835 process          L0437 DEBUG| [stdout] ==============
2019-11-09 13:19:09,835 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:09,836 process          L0437 DEBUG| [stdout] -------------------------------------------------------------
2019-11-09 13:19:09,836 process          L0437 DEBUG| [stdout] DG/VD TYPE  State Access Consist Cache Cac sCC     Size Name
2019-11-09 13:19:09,836 process          L0437 DEBUG| [stdout] -------------------------------------------------------------
2019-11-09 13:19:09,836 process          L0437 DEBUG| [stdout] 0/0   RAID0 Optl  RW     Yes     NRWTD -   OFF 9.765 GB
2019-11-09 13:19:09,836 process          L0437 DEBUG| [stdout] -------------------------------------------------------------
2019-11-09 13:19:09,836 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:09,837 process          L0437 DEBUG| [stdout] EID=Enclosure Device ID| VD=Virtual Drive| DG=Drive Group|Rec=Recovery
2019-11-09 13:19:09,837 process          L0437 DEBUG| [stdout] Cac=CacheCade|OfLn=OffLine|Pdgd=Partially Degraded|Dgrd=Degraded
2019-11-09 13:19:09,837 process          L0437 DEBUG| [stdout] Optl=Optimal|RO=Read Only|RW=Read Write|HD=Hidden|TRANS=TransportReady|B=Blocked|
2019-11-09 13:19:09,837 process          L0437 DEBUG| [stdout] Consist=Consistent|R=Read Ahead Always|NR=No Read Ahead|WB=WriteBack|
2019-11-09 13:19:09,837 process          L0437 DEBUG| [stdout] AWB=Always WriteBack|WT=WriteThrough|C=Cached IO|D=Direct IO|sCC=Scheduled
2019-11-09 13:19:09,838 process          L0437 DEBUG| [stdout] Check Consistency
2019-11-09 13:19:09,838 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:09,838 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:09,838 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:09,840 process          L0605 INFO | Running '/root/storcli64 /c0/vall delete force'
2019-11-09 13:19:09,862 process          L0687 INFO | Command '/root/storcli64 /c0/vall delete force' finished with 0 after 0.02062392234802246s
2019-11-09 13:19:09,862 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:19:09,863 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:19:09,863 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:19:09,863 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:19:09,863 process          L0437 DEBUG| [stdout] Description = Delete VD succeeded
2019-11-09 13:19:09,864 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:09,864 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:09,866 process          L0605 INFO | Running '/root/storcli64 /c0 add vd r0 size=10000 drives=252:6,252:5 WT nora direct                    strip=256'
2019-11-09 13:19:10,205 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:19:10,205 process          L0687 INFO | Command '/root/storcli64 /c0 add vd r0 size=10000 drives=252:6,252:5 WT nora direct                    strip=256' finished with 0 after 0.33737921714782715s
2019-11-09 13:19:10,206 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:19:10,206 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:19:10,206 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:19:10,206 process          L0437 DEBUG| [stdout] Description = Add VD Succeeded.
2019-11-09 13:19:10,206 process          L0437 DEBUG| [stdout]
2019-11-09 13:19:10,206 process          L0437 DEBUG| [stdout]
...
2019-11-09 13:20:26,544 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:20:26,544 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:20:26,545 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:20:26,545 process          L0437 DEBUG| [stdout] Description = Add VD Succeeded.
2019-11-09 13:20:26,545 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:26,545 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:26,547 process          L0605 INFO | Running '/root/storcli64 /c0/vall show'
2019-11-09 13:20:27,604 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:20:27,604 process          L0687 INFO | Command '/root/storcli64 /c0/vall show' finished with 0 after 1.055448293685913s
2019-11-09 13:20:27,605 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:20:27,605 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:20:27,605 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:20:27,605 process          L0437 DEBUG| [stdout] Description = None
2019-11-09 13:20:27,605 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:27,605 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:27,606 process          L0437 DEBUG| [stdout] Virtual Drives :
2019-11-09 13:20:27,606 process          L0437 DEBUG| [stdout] ==============
2019-11-09 13:20:27,606 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:27,606 process          L0437 DEBUG| [stdout] -------------------------------------------------------------
2019-11-09 13:20:27,606 process          L0437 DEBUG| [stdout] DG/VD TYPE  State Access Consist Cache Cac sCC     Size Name
2019-11-09 13:20:27,607 process          L0437 DEBUG| [stdout] -------------------------------------------------------------
2019-11-09 13:20:27,607 process          L0437 DEBUG| [stdout] 0/0   RAID0 Optl  RW     Yes     RAWBC -   OFF 9.765 GB
2019-11-09 13:20:27,607 process          L0437 DEBUG| [stdout] -------------------------------------------------------------
2019-11-09 13:20:27,607 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:27,607 process          L0437 DEBUG| [stdout] EID=Enclosure Device ID| VD=Virtual Drive| DG=Drive Group|Rec=Recovery
2019-11-09 13:20:27,607 process          L0437 DEBUG| [stdout] Cac=CacheCade|OfLn=OffLine|Pdgd=Partially Degraded|Dgrd=Degraded
2019-11-09 13:20:27,608 process          L0437 DEBUG| [stdout] Optl=Optimal|RO=Read Only|RW=Read Write|HD=Hidden|TRANS=TransportReady|B=Blocked|
2019-11-09 13:20:27,608 process          L0437 DEBUG| [stdout] Consist=Consistent|R=Read Ahead Always|NR=No Read Ahead|WB=WriteBack|
2019-11-09 13:20:27,608 process          L0437 DEBUG| [stdout] AWB=Always WriteBack|WT=WriteThrough|C=Cached IO|D=Direct IO|sCC=Scheduled
2019-11-09 13:20:27,608 process          L0437 DEBUG| [stdout] Check Consistency
2019-11-09 13:20:27,608 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:27,609 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:27,609 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:27,610 process          L0605 INFO | Running '/root/storcli64 /c0/vall delete force'
2019-11-09 13:20:27,646 process          L0437 DEBUG| [stdout] CLI Version = 007.1108.0000.0000 July 17, 2019
2019-11-09 13:20:27,646 process          L0687 INFO | Command '/root/storcli64 /c0/vall delete force' finished with 0 after 0.03414034843444824s
2019-11-09 13:20:27,647 process          L0437 DEBUG| [stdout] Operating system = Linux 4.18.0-80.11.2.el8.samsung3.ppc64le
2019-11-09 13:20:27,647 process          L0437 DEBUG| [stdout] Controller = 0
2019-11-09 13:20:27,647 process          L0437 DEBUG| [stdout] Status = Success
2019-11-09 13:20:27,647 process          L0437 DEBUG| [stdout] Description = Delete VD succeeded
2019-11-09 13:20:27,647 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:27,648 process          L0437 DEBUG| [stdout]
2019-11-09 13:20:27,650 test             L0297 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2019-11-09 13:20:27,650 test             L0297 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2019-11-09 13:20:27,650 test             L0297 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2019-11-09 13:20:27,675 test             L1034 INFO | PASS 01-avago9361_vd.py:Avago9361.test_createall;Scenario-r0-2af5
2019-11-09 13:20:27,675 test             L1017 INFO |
2019-11-09 13:20:27,689 sysinfo          L0408 DEBUG| File /etc/avocado/sysinfo/commands does not exist.
2019-11-09 13:20:27,689 sysinfo          L0419 DEBUG| File /etc/avocado/sysinfo/files does not exist.
2019-11-09 13:20:27,689 sysinfo          L0447 DEBUG| File /etc/avocado/sysinfo/profilers does not exist.
2019-11-09 13:20:27,690 sysinfo          L0505 INFO | System log file not found (looked for ['/var/log/messages', '/var/log/syslog', '/var/log/system.log'])

**Pull request merged**
