### PR TITLE
Script to add and delete Network Virtualisation interfaces

### PR DESCRIPTION
**Pull request by hathyaga**
This script will add and delete Network virtualized interfaces
using the SRIOV capable IO adapter given as an input by the user
and performs this operation multiple times based on the count
given by the user as well

Signed-off-by: Harsha Thyagaraja <harshkid@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by hathyaga** [comment]
Job log 
[job.log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/1828077/job.log.txt)

**Comment by hathyaga** [comment]
@narasimhan-v I am planning and want to add all the Network virtualized tests under a separate directory under "avocado-misc-tests/io/net/" directory. Let me know your thoughts

**Comment by narasimhan-v** [comment]
@hathyaga `io/net/virt` or `io/net/virt-net` should  be fine.

**Comment by hathyaga** [comment]
@narasimhan-v New PR: https://github.com/avocado-framework-tests/avocado-misc-tests/pull/827

**Pull request closed without merging**
