### PR TITLE
htx_nic_devices.py: get pkg manager of peer

### PR DESCRIPTION
**Pull request by cforno12**
Currently, the test assumes that the peer machine has the same package manager.
This fix retrieves the peer's OS and uses the appropriate package manager.

Signed-off-by: Cristobal Forno <cforno12@linux.ibm.com>

### CODE REVIEW

**Review by smruti77 — APPROVED** [review]

**Comment by smruti77** [comment]
@narasimhan-v we have plan to add this in to utils,what about that.? or else this is fine.

**Comment by narasimhan-v** [comment]
Most of our use cases have been with same distro on peer, so this was not a necessity so far. We need to evaluate the use cases.

Regarding utils part, @smruti77 any pointers ? I could not recollect the discussion.

**Comment by smruti77** [comment]
> Most of our use cases have been with same distro on peer, so this was not a necessity so far. We need to evaluate the use cases.
> 
> Regarding utils part, @smruti77 any pointers ? I could not recollect the discussion.

@narasimhan-v didn't sent any PR for that. my point is like this PR we have also done but later we decided because of this code, don't want to include in script, so we have did for same distro on peer. and if we need package installation for different distro peer decided to include that in utils. my question is can we allow this in script..?

**Comment by narasimhan-v** [comment]
> > Most of our use cases have been with same distro on peer, so this was not a necessity so far. We need to evaluate the use cases.
> > 
> > Regarding utils part, @smruti77 any pointers ? I could not recollect the discussion.
> 
> @narasimhan-v didn't sent any PR for that. my point is like this PR we have also done but later we decided because of this code, don't want to include in script, so we have did for same distro on peer. and if we need package installation for different distro peer decided to include that in utils. my question is can we allow this in script..?

Yes, right. The best place to include this is in utils

**Comment by cforno12** [comment]
Would I have to contribute to this https://github.com/avocado-framework/avocado/blob/master/avocado/utils/distro.py ? Just want to be sure I'm looking in the right place...

I'm a bit unsure on what my action item is, do I want to enable the distro.py to detect the distro of a peer machine?

**Comment by cforno12** [comment]
Started distro detection on peer on avocado utils. https://github.com/avocado-framework/avocado/pull/4783 please let me know if you have any concerns @narasimhan-v @smruti77

**Comment by PraveenPenguin** [comment]
@cforno12 sorry for late  seems me it failing in trvais check , even if you @narasimhan-v perusing this Request please open new request

**Pull request closed without merging**
