### PR TITLE
add utils dmesg to vnic test

### PR DESCRIPTION
**Pull request by smruti77**
check dmesg error if any after test complete.

Signed-off-by: Bismruti Pattjoshi <bismruti@oc7660885027.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
JOB ID     : 114601a96afebd13d32aedbdbc4c40432e0ba387
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2020-11-02T00.46-114601a/job.log
 (1/9) network_virtualization.py:NetworkVirtualization.test_add;run-efa7: PASS (25.40 s)
 (2/9) network_virtualization.py:NetworkVirtualization.test_backingdevadd;run-efa7: PASS (29.05 s)
 (3/9) network_virtualization.py:NetworkVirtualization.test_hmcfailover;run-efa7: ERROR: Failed to ping: Command 'ping -I env6 147.1.1.246 -c 5' failed.\nstdout: b'PING 147.1.1.246 (147.1.1.246) from 147.1.1.247 env6: 56(84) bytes of data.\n\n--- 147.1.1.246 ping statistics ---\n5 packets transmitted, 0 received, 100% packet loss, time 158ms\n... (52.34 s)
 (4/9) network_virtualization.py:NetworkVirtualization.test_clientfailover;run-efa7: ERROR: Failed to ping: Command 'ping -I env6 147.1.1.246 -c 5' failed.\nstdout: b'PING 147.1.1.246 (147.1.1.246) from 147.1.1.247 env6: 56(84) bytes of data.\n\n--- 147.1.1.246 ping statistics ---\n5 packets transmitted, 0 received, 100% packet loss, time 146ms\n... (46.84 s)
 (5/9) network_virtualization.py:NetworkVirtualization.test_vnic_auto_failover;run-efa7: PASS (59.18 s)
 (6/9) network_virtualization.py:NetworkVirtualization.test_rmdev_viosfailover;run-efa7: PASS (66.24 s)
 (7/9) network_virtualization.py:NetworkVirtualization.test_vnic_dlpar;run-efa7: ERROR: Test is failed Found failures in dmesg Please check  dmesg log in debug log. (54.05 s)
 (8/9) network_virtualization.py:NetworkVirtualization.test_backingdevremove;run-efa7: PASS (18.87 s)
 (9/9) network_virtualization.py:NetworkVirtualization.test_remove;run-efa7: FAIL: Network virtualization remove device operation                        failed (9.78 s)
RESULTS    : PASS 5 | ERROR 3 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2020-11-02T00.46-114601a/results.html
JOB TIME   : 363.51 s

**Comment by narasimhan-v** [comment]
@smruti77 Are the FAILs above due to dmesg ? If so, can you please upload job.log files ?

**Comment by smruti77** [comment]
> @smruti77 Are the FAILs above due to dmesg ? If so, can you please upload job.log files ?

yes

**Comment by smruti77** [comment]
[vnic.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5480517/vnic.log)

**Comment by narasimhan-v** [comment]
@smruti77 
Please handle this. It should be fail rather than error.
Also, if test fails based on dmesg, mention that too in `self.fail()`

```
2020-11-02 00:52:32,002 network_virtuali L0815 INFO | Gathering kernel errors if any
2020-11-02 00:52:32,007 dmesg            L0116 DEBUG| dmesg log:
[Mon Nov  2 00:51:46 2020] ibmvnic 30000006 env6: Adapter login failed
[Mon Nov  2 00:51:46 2020] ibmvnic 30000006 env6: Adapter login failed

2020-11-02 00:52:32,007 stacktrace       L0039 ERROR| 
2020-11-02 00:52:32,008 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/core/test.py:793
2020-11-02 00:52:32,008 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-11-02 00:52:32,009 stacktrace       L0045 ERROR|   File "/root/avocado/avocado-misc-tests/io/net/virt-net/network_virtualization.py", line 816, in tearDown
2020-11-02 00:52:32,009 stacktrace       L0045 ERROR|     dmesg.collect_errors_by_level()
2020-11-02 00:52:32,009 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/dmesg.py", line 117, in collect_errors_by_level
2020-11-02 00:52:32,009 stacktrace       L0045 ERROR|     raise DmesgError("Test is failed {}".format(err))
2020-11-02 00:52:32,009 stacktrace       L0045 ERROR| avocado.utils.dmesg.DmesgError: Test is failed Found failures in dmesg Please check  dmesg log in debug log.
2020-11-02 00:52:32,009 stacktrace       L0046 ERROR| 
2020-11-02 00:52:32,010 test             L0206 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2020-11-02 00:52:32,010 test             L0206 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2020-11-02 00:52:32,010 test             L0206 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2020-11-02 00:52:32,255 sysinfo          L0113 DEBUG| Not logging /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor (file does not exist)
2020-11-02 00:52:32,256 sysinfo          L0113 DEBUG| Not logging /proc/pci (file does not exist)
2020-11-02 00:52:32,502 process          L0604 INFO | Running 'kill -19 14343'
2020-11-02 00:52:32,505 process          L0686 INFO | Command 'kill -19 14343' finished with 0 after 0.0008194446563720703s
2020-11-02 00:52:32,538 process          L0604 INFO | Running 'kill -9 14343'
2020-11-02 00:52:32,542 process          L0686 INFO | Command 'kill -9 14343' finished with 0 after 0.0008578300476074219s
2020-11-02 00:52:32,542 process          L0604 INFO | Running 'kill -18 14343'
2020-11-02 00:52:32,546 process          L0686 INFO | Command 'kill -18 14343' finished with 0 after 0.0008411407470703125s
2020-11-02 00:52:32,546 process          L0604 INFO | Running 'kill -19 14348'
2020-11-02 00:52:32,549 process          L0686 INFO | Command 'kill -19 14348' finished with 0 after 0.0007948875427246094s
2020-11-02 00:52:32,577 process          L0604 INFO | Running 'kill -9 14348'
2020-11-02 00:52:32,580 process          L0686 INFO | Command 'kill -9 14348' finished with 0 after 0.0008339881896972656s
2020-11-02 00:52:32,580 process          L0604 INFO | Running 'kill -18 14348'
2020-11-02 00:52:32,584 process          L0686 INFO | Command 'kill -18 14348' finished with 0 after 0.0008363723754882812s
2020-11-02 00:52:32,584 test             L0933 ERROR| ERROR 7-network_virtualization.py:NetworkVirtualization.test_vnic_dlpar;run-efa7 -> TestSetupFail: Test is failed Found failures in dmesg Please check  dmesg log in debug log.
```

**Comment by smruti77** [comment]
@narasimhan-v that error message coming from utils.

**Comment by narasimhan-v** [comment]
@smruti77 that error/exception should be handled in test

**Comment by smruti77** [comment]
JOB ID     : 4c18f6f195e8fb0fd49b23a71c0d651a134be8eb
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-11-11T00.21-4c18f6f/job.log
 (1/9) network_virtualization.py:NetworkVirtualization.test_add;run-9d90: PASS (19.81 s)
 (2/9) network_virtualization.py:NetworkVirtualization.test_backingdevadd;run-9d90: PASS (17.17 s)
 (3/9) network_virtualization.py:NetworkVirtualization.test_hmcfailover;run-9d90: ERROR: Failed to ping: Command 'ping -I env6 147.1.1.246 -c 5' failed.\nstdout: b'PING 147.1.1.246 (147.1.1.246) from 147.1.1.247 env6: 56(84) bytes of data.\n\n--- 147.1.1.246 ping statistics ---\n5 packets transmitted, 0 received, 100% packet loss, time 151ms\n... (36.43 s)
 (4/9) network_virtualization.py:NetworkVirtualization.test_clientfailover;run-9d90: ERROR: Failed to ping: Command 'ping -I env6 147.1.1.246 -c 5' failed.\nstdout: b'PING 147.1.1.246 (147.1.1.246) from 147.1.1.247 env6: 56(84) bytes of data.\n\n--- 147.1.1.246 ping statistics ---\n5 packets transmitted, 0 received, 100% packet loss, time 146ms\n... (46.75 s)
 (5/9) network_virtualization.py:NetworkVirtualization.test_vnic_auto_failover;run-9d90: PASS (30.63 s)
 (6/9) network_virtualization.py:NetworkVirtualization.test_rmdev_viosfailover;run-9d90: PASS (58.50 s)
 (7/9) network_virtualization.py:NetworkVirtualization.test_vnic_dlpar;run-9d90: FAIL: test failed,check dmesg log in debug log (44.30 s)
 (8/9) network_virtualization.py:NetworkVirtualization.test_backingdevremove;run-9d90: PASS (13.01 s)
 (9/9) network_virtualization.py:NetworkVirtualization.test_remove;run-9d90: FAIL: Network virtualization remove device operation                        failed (9.40 s)
RESULTS    : PASS 5 | ERROR 2 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-11-11T00.21-4c18f6f/results.html
JOB TIME   : 277.69 s

**Comment by smruti77** [comment]
[vnic_dmesg.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5522009/vnic_dmesg.log)

**Review by narasimhan-v — APPROVED** [review]

**Review by abdhaleegit — APPROVED** [review]
@smruti77 Please paste here the LPM logs on my setup .. rest all LGTM

**Comment by smruti77** [comment]
> @smruti77 Please paste here the LPM logs on my setup .. rest all LGTM

@abdhaleegit i pasted lmp log in LPM PR.

**Comment by smruti77** [comment]
[vnic_dmesg_.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5566227/vnic_dmesg_.log)

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Review by narasimhan-v — APPROVED** [review]

**Pull request merged**
