### PR TITLE
handle for Exception shouldn't raise if backup file not available

### PR DESCRIPTION
**Pull request by smruti77**
for restore_from_backup(), if backup file is there it will move or
else it shouldn't raise exception.to avoid test fail.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
[multicast.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5089953/multicast.log)

**Review by abdhaleegit — COMMENTED** [review]
@smruti77 need 3 logs here
1. with config file
2. with out config file
3. with ip commands config of interface

**Comment by abdhaleegit** [comment]
the code LGTM, we can merge once we have logs

**Comment by smruti77** [comment]
ip addr show enP34p1s0f0
3: enP34p1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 98:be:94:0c:67:70 brd ff:ff:ff:ff:ff:ff

[root@ltczz401-lp11 network-scripts]# ls
ifcfg-enP34p1s0f1  ifcfg-enP34p1s0f2  ifcfg-enP34p1s0f3  ifcfg-net0

without config file :-

JOB ID     : efe4b4620c8337cc94dd3ae6e27f3e00ed804635
JOB LOG    : /root/vaishnavi/avocado-fvt-wrapper/results/job-2020-09-01T05.08-efe4b46/job.log
 (1/1) multicast.py:ReceiveMulticastTest.test_multicast;run-Parameters-ec3e: PASS (37.06 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/vaishnavi/avocado-fvt-wrapper/results/job-2020-09-01T05.08-efe4b46/results.html
JOB TIME   : 37.15 s


enP34p1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 98:be:94:0c:67:70 brd ff:ff:ff:ff:ff:ff
    inet 147.1.1.221/24 brd 147.1.1.255 scope global noprefixroute enP34p1s0f0
       valid_lft forever preferred_lft forever
    inet6 fe80::9abe:94ff:fe0c:6770/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

ls
ifcfg-enP34p1s0f0  ifcfg-enP34p1s0f1  ifcfg-enP34p1s0f2  ifcfg-enP34p1s0f3  ifcfg-net0

 with config file
JOB ID     : 6883687ba9af2b9362946b88be47ce33db179ebd
JOB LOG    : /root/vaishnavi/avocado-fvt-wrapper/results/job-2020-09-01T05.24-6883687/job.log
 (1/1) multicast.py:ReceiveMulticastTest.test_multicast;run-Parameters-ec3e: PASS (36.63 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/vaishnavi/avocado-fvt-wrapper/results/job-2020-09-01T05.24-6883687/results.html
JOB TIME   : 36.69 s

**Comment by smruti77** [comment]
[multicast_withconfig.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5155296/multicast_withconfig.log)
[multicast_withoutconfig.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5155299/multicast_withoutconfig.log)

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Review by narasimhan-v — APPROVED** [review]
@abdhaleegit Thanks for the review.

**Pull request merged**
