### PR TITLE
cpu/xive.py : fixed 'utf-8' codec error

### PR DESCRIPTION
**Pull request by sneh-3**
The file contains characters that are not valid UTF-8 encoded. This patch will fix the errors while reading the file.

### CODE REVIEW

**Comment by Naresh-ibm** [comment]
@sneh-3 please attatch the error logs and the fixed one too for reference.

**Review by Naresh-ibm — CHANGES_REQUESTED** [review]
run logs please

**Comment by sneh-3** [comment]
before Patch logs as :
[[root@ltciofvtr-bostoness1 job-2024-02-12T16.59-94eb964]# avocado run --max-parallel-tasks=1 /home/rd/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py
JOB ID     : 473dd6fb98674cf99656432e3977e8269112d04f
JOB LOG    : /home/rd/avocado-fvt-wrapper/results/job-2024-02-13T03.09-473dd6f/job.log
 (1/4) /home/rd/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_intr_mode: STARTED
 (1/4) /home/rd/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_intr_mode: ERROR: 'utf-8' codec can't decode byte 0xa7 in position 173095: invalid start byte (0.04 s)
 (2/4) /home/rd/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_storeEOI: STARTED
 (2/4) /home/rd/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_storeEOI: ERROR: 'utf-8' codec can't decode byte 0xa7 in position 173095: invalid start byte (0.04 s)
 (3/4) /home/rd/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_verify_xive_cmdline: STARTED
 (3/4) /home/rd/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_verify_xive_cmdline: ERROR: 'utf-8' codec can't decode byte 0xa7 in position 173095: invalid start byte (0.04 s)
 (4/4) /home/rd/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_verify_xive_config: STARTED
 (4/4) /home/rd/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_verify_xive_config: ERROR: 'utf-8' codec can't decode byte 0xa7 in position 173095: invalid start byte (0.04 s)
RESULTS    : PASS 0 | ERROR 4 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/rd/avocado-fvt-wrapper/results/job-2024-02-13T03.09-473dd6f/results.html

After fixing the issue logs as :
 avocado run --max-parallel-tasks=1 /home/rohan/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py
JOB ID     : dde05d32aed41ae8ecea266746795ef536831520
JOB LOG    : /home/rohan/avocado-fvt-wrapper/results/job-2024-05-21T09.14-dde05d3/job.log
 (1/4) /home/rohan/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_intr_mode: STARTED
 (1/4) /home/rohan/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_intr_mode: PASS (0.04 s)
 (2/4) /home/rohan/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_storeEOI: STARTED
 (2/4) /home/rohan/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_storeEOI: FAIL: storeEOI feature 'S' flag is absent for POWER9 / XIVE (0.10 s)
 (3/4) /home/rohan/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_verify_xive_cmdline: STARTED
 (3/4) /home/rohan/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_verify_xive_cmdline: PASS (0.04 s)
 (4/4) /home/rohan/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_verify_xive_config: STARTED
 (4/4) /home/rohan/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/xive.py:XIVE.test_verify_xive_config: PASS (0.04 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/rohan/avocado-fvt-wrapper/results/job-2024-05-21T09.14-dde05d3/results.html
JOB TIME   : 19.65 s

**Review by Naresh-ibm — APPROVED** [review]
@sneh-3 Thanks for PR
LGTM

**Pull request merged**
