### PR TITLE
sosreport.py: Test the sosreport with different smt levels

### PR DESCRIPTION
**Pull request by shirishaganta1**
This code tests the sosreport with different smt levels ie., 2, 4, 8 and off

Signed-off-by: Shirisha Ganta <SHIRISHA.Ganta1@ibm.com>

### CODE REVIEW

**Comment by shirishaganta1** [comment]
# cat nohup.out 
JOB ID     : dd72dede8b1f2f352711b5dfa253bdb376e3c533
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-25T23.58-dd72ded/job.log
 (1/7) sosreport.py:Sosreport.test_short:  PASS (247.68 s)
 (2/7) sosreport.py:Sosreport.test_user:  PASS (83.38 s)
 (3/7) sosreport.py:Sosreport.test_plugins:  PASS (237.26 s)
 (4/7) sosreport.py:Sosreport.test_others:  PASS (395.41 s)
 (5/7) sosreport.py:Sosreport.test_archive:  PASS (233.74 s)
 (6/7) sosreport.py:Sosreport.test_PPC:  PASS (52.45 s)
 (7/7) sosreport.py:Sosreport.test_smtchanges:  PASS (343.48 s)
RESULTS    : PASS 7 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-25T23.58-dd72ded/results.html
JOB TIME   : 1594.29 s
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/9869003/job.log)

**Review by PraveenPenguin — APPROVED** [review]

**Comment by sacsant** [comment]
Why do we need to add this scenario into the test? SMT changes shouldn't affect sos report. Is there a particular use case driving this change?

**Comment by PraveenPenguin** [comment]
@sacsant @abdhaleegit if looks good can we merge this PR

**Comment by sacsant** [comment]
> @sacsant @abdhaleegit if looks good can we merge this PR

Yes, the changes seems reasonable and will cover issues seen with this tool after a SMT change. It will also be good to consider suggestion from Abdul on driving such scenarios via a config file instead of code.

**Comment by PraveenPenguin** [comment]
> > @sacsant @abdhaleegit if looks good can we merge this PR
> 
> Yes, the changes seems reasonable and will cover issues seen with this tool after a SMT change. It will also be good to consider suggestion from Abdul on driving such scenarios via a config file instead of code.

@sacsant as smt test does all smt operation so calling smt test as one of scenario seems not fit here ,

**Pull request merged**
