### PR TITLE
perf/perftool: Separate perf test and perftool_test

### PR DESCRIPTION
**Pull request by sacsant**
perftool test contains 2 subtests
     - perf test
     - perftool_testsuite
    
Separate these 2 into an independent tests for ease of use and maintenance.
[1/3] perf/perftool: Remove perftool test
[2/3] perf/perftool: Introduce perf test
[3/3] perf/perftool: Introduce perftool_testsuite

Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>

### CODE REVIEW

**Comment by sacsant** [comment]
Before the fix against 6.2.0-rc7-next-20230208 using perf tool shipped with distro:

 (1/2) perf/perftool.py:Perftool.test_perf_test: STARTED
 (1/2) perf/perftool.py:Perftool.test_perf_test: FAIL: 5 Test failed (151.35 s)
 (2/2) perf/perftool.py:Perftool.test_perf_testsuite: STARTED
 (2/2) perf/perftool.py:Perftool.test_perf_testsuite: FAIL: 17 Test failed (282.55 s)

After the fix against 6.2.0-rc7-next-20230208 using upstream version of perf:
$ perf --version
perf version 6.2.0-rc8
$

The number of perf_test failures have reduced to 2 (from 5)
 (1/2) perf/perftool.py:Perftool.test_perf_test;run-run_type-upstream-41dd: STARTED
 (1/2) perf/perftool.py:Perftool.test_perf_test;run-run_type-upstream-41dd: FAIL: 2 Test failed (153.75 s)
 (2/2) perf/perftool.py:Perftool.test_perf_testsuite;run-run_type-upstream-41dd: STARTED
 (2/2) perf/perftool.py:Perftool.test_perf_testsuite;run-run_type-upstream-41dd: FAIL: 12 Test failed (223.10 s)

**Comment by disgoel** [comment]
@sacsant can you also add pre-requisite packages to run perf test otherwise few test skips.
clang, perf-debuginfo, kernel-debuginfo

one more request from dev was to run perf test after compiling llvm

**Comment by sacsant** [comment]
> @sacsant can you also add pre-requisite packages to run perf test otherwise few test skips. clang, perf-debuginfo, kernel-debuginfo
>

Is this for both distro as well as upstream as a target? I guess debug info packages are meant for distro only.
 
> one more request from dev was to run perf test after compiling llvm

same question, distro and/or upstream ??

**Comment by sacsant** [comment]
On second thought let me revisit this. The two test scenarios are separate and not testing same functionality. It will be better to split this into 2 separate tests -- one for perf test and another for perf-testsuite.

Will work on this and push new code shortly. Moving to draft stage.

**Comment by sacsant** [comment]
$ avocado run perf/perf_test.py 
...
 (1/1) perf/perf_test.py:Perftest.test_perf_test: STARTED
 (1/1) perf/perf_test.py:Perftest.test_perf_test: FAIL: 3 Test failed (51.76 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
$
$ avocado run perf/perftool_test.py 
....
 (1/1) perf/perftool_test.py:Perftool.test_perf_testsuite: STARTED
 (1/1) perf/perftool_test.py:Perftool.test_perf_testsuite: FAIL: 13 Test failed (272.65 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
$

**Comment by sacsant** [comment]
I will submit a separate PR to add upstream as a target support for perf_test.py

**Comment by sacsant** [comment]
> > I will submit a separate PR to add upstream as a target support for perf_test.py
> 
> @sacsant are you going to add pre-requisite packages in a separate PR ? If yes, this patch looks good.

Yes will address the pre-reqs along with upstream support in a separate PR.

**Pull request merged**
