### PR TITLE
bond cfg file for bond interfaces [Waiting for Utils]

### PR DESCRIPTION
**Pull request by vaishnavibhat**
create bond cfg file for bond interface that is tested

Signed-off-by: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by vaishnavibhat** [comment]
avocado run bonding.py -m bonding.py.data/bonding_single.yaml 
JOB ID     : 9675ba5113cd86aaa2991f6aeb77fe06f6e9c56e
JOB LOG    : /root/HNV/avocado-fvt-wrapper/results/job-2021-07-21T12.31-9675ba5/job.log
 (1/3) bonding.py:Bonding.test_setup;run-15c2: PASS (19.59 s)
 (2/3) bonding.py:Bonding.test_run;run-15c2: PASS (242.04 s)
 (3/3) bonding.py:Bonding.test_cleanup;run-15c2: PASS (6.87 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/HNV/avocado-fvt-wrapper/results/job-2021-07-21T12.31-9675ba5/results.html
JOB TIME   : 269.33 s

[bonding.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6857461/bonding.log)

**Comment by vaishnavibhat** [comment]
Depends on https://github.com/avocado-framework/avocado/pull/4795

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Comment by Naresh-ibm** [comment]
@abdhaleegit @PraveenPenguin can you please Merge this since the util on which this was depending got merged already
 avocado-framework/avocado#4795.
 @vaishnavibhat do you have any changes here?

**Comment by PraveenPenguin** [comment]
@vaishnavibhat can you please rebase PR with latest code

**Comment by PraveenPenguin** [comment]
@vaishnavibhat are you still persuing this , if yes please raise another PR has rebased version

**Pull request closed without merging**
