### PR TITLE
Added Rmaptest in Avocado

### PR DESCRIPTION
**Pull request by PraveenPenguin**
Rmaptest create random VMAs mapped tasks

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
job log : https://paste.fedoraproject.org/433546/74644010/

**Comment by apahim** [comment]
When will the test be considered as failed?

**Comment by PraveenPenguin** [comment]
@apahim this test is a stress test for system so i don't think there is any fail senario after test run system should alive

**Comment by PraveenPenguin** [comment]
@apahim  can we check return code of the command please suggest ?

Regards
Praveen

**Comment by apahim** [comment]
Well, you know better. If there isn't a fail condition, no need to check the test result.

**Comment by apahim** [comment]
lgtm. thanks.

**Pull request merged**
