### PR TITLE
Updating nmap and iperf source version releases

### PR DESCRIPTION
**Pull request by PavamanSubramaniyam**
iperf and nmap tar files used for testing is updated to the latest released levels

### CODE REVIEW

**Comment by PavamanSubramaniyam** [comment]
I have pasted the execution results for the iperf and uperf tests with the updating of nmap and iperf source tar files to the latest releases.

# avocado run --max-parallel-tasks=1 iperf_test.py -m iperf_test.py.data/iperf_test.yaml
JOB ID     : f259a2d0845ed9a4f5075391930f7b640e0ece1b
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-03-24T00.18-f259a2d/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/9) iperf_test.py:Iperf.test;run-mtu-1500-d8bd: STARTED
 (1/9) iperf_test.py:Iperf.test;run-mtu-1500-d8bd: PASS (74.85 s)
 (2/9) iperf_test.py:Iperf.test;run-mtu-2000-0453: STARTED
 (2/9) iperf_test.py:Iperf.test;run-mtu-2000-0453: PASS (54.78 s)
 (3/9) iperf_test.py:Iperf.test;run-mtu-3000-bc02: STARTED
 (3/9) iperf_test.py:Iperf.test;run-mtu-3000-bc02: PASS (54.96 s)
 (4/9) iperf_test.py:Iperf.test;run-mtu-4000-ef51: STARTED
 (4/9) iperf_test.py:Iperf.test;run-mtu-4000-ef51: PASS (54.83 s)
 (5/9) iperf_test.py:Iperf.test;run-mtu-5000-5f6b: STARTED
 (5/9) iperf_test.py:Iperf.test;run-mtu-5000-5f6b: PASS (55.23 s)
 (6/9) iperf_test.py:Iperf.test;run-mtu-6000-45cc: STARTED
 (6/9) iperf_test.py:Iperf.test;run-mtu-6000-45cc: PASS (54.78 s)
 (7/9) iperf_test.py:Iperf.test;run-mtu-7000-4e8e: STARTED
 (7/9) iperf_test.py:Iperf.test;run-mtu-7000-4e8e: PASS (54.90 s)
 (8/9) iperf_test.py:Iperf.test;run-mtu-8000-6b45: STARTED
 (8/9) iperf_test.py:Iperf.test;run-mtu-8000-6b45: PASS (55.09 s)
 (9/9) iperf_test.py:Iperf.test;run-mtu-9000-1f8f: STARTED
 (9/9) iperf_test.py:Iperf.test;run-mtu-9000-1f8f: PASS (54.87 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-03-24T00.18-f259a2d/results.html
JOB TIME   : 537.03 s


# avocado run --max-parallel-tasks=1 uperf_test.py -m uperf_test.py.data/uperf_test.yaml --execution-order tests-per-variant
Fetching asset from uperf_test.py:Uperf.test
JOB ID     : f3cf4d751b6c29b8c377d15c9dd703139a2118c6
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-03-24T00.37-f3cf4d7/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/9) uperf_test.py:Uperf.test;run-mtu-1500-cea6: STARTED
 (1/9) uperf_test.py:Uperf.test;run-mtu-1500-cea6: PASS (93.05 s)
 (2/9) uperf_test.py:Uperf.test;run-mtu-2000-e984: STARTED
 (2/9) uperf_test.py:Uperf.test;run-mtu-2000-e984: PASS (84.88 s)
 (3/9) uperf_test.py:Uperf.test;run-mtu-3000-eaae: STARTED
 (3/9) uperf_test.py:Uperf.test;run-mtu-3000-eaae: PASS (84.41 s)
 (4/9) uperf_test.py:Uperf.test;run-mtu-4000-ec3d: STARTED
 (4/9) uperf_test.py:Uperf.test;run-mtu-4000-ec3d: PASS (84.62 s)
 (5/9) uperf_test.py:Uperf.test;run-mtu-5000-d2b9: STARTED
 (5/9) uperf_test.py:Uperf.test;run-mtu-5000-d2b9: PASS (85.53 s)
 (6/9) uperf_test.py:Uperf.test;run-mtu-6000-9bc8: STARTED
 (6/9) uperf_test.py:Uperf.test;run-mtu-6000-9bc8: PASS (85.02 s)
 (7/9) uperf_test.py:Uperf.test;run-mtu-7000-93af: STARTED
 (7/9) uperf_test.py:Uperf.test;run-mtu-7000-93af: PASS (84.21 s)
 (8/9) uperf_test.py:Uperf.test;run-mtu-8000-8c88: STARTED
 (8/9) uperf_test.py:Uperf.test;run-mtu-8000-8c88: PASS (83.68 s)
 (9/9) uperf_test.py:Uperf.test;run-mtu-9000-69e5: STARTED
 (9/9) uperf_test.py:Uperf.test;run-mtu-9000-69e5: PASS (85.30 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-03-24T00.37-f3cf4d7/results.html
JOB TIME   : 793.52 s

**Review by abdhaleegit — COMMENTED** [review]
Please run once with all 3 in cfg

**Comment by abdhaleegit** [comment]
> Please run once with all 3 in cfg

Thanks for the logs

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Pull request merged**
