### PR TITLE
nettle-tests.py: add distribution specific test cases

### PR DESCRIPTION
**Pull request by nasastry**
Add distribution specific test cases.
With the support of yaml, can run distribution and upstream test cases.

Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>

### CODE REVIEW

**Comment by nasastry** [comment]
```
SLES:
JOB ID     : e8a75e42190663966edeb4593f3e30b860f81b9c
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-07T14.02-e8a75e4/job.log
 (1/2) nettle-tests.py:Nettle.test;run-run_type-upstream-040c: PASS (27.35 s)
 (2/2) nettle-tests.py:Nettle.test;run-run_type-distro-f6a8: PASS (25.84 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-07T14.02-e8a75e4/results.html
JOB TIME   : 75.38 s


RHEL:
JOB ID     : dab0658feabfa4527a246e1aabdb12aba02b3e9a
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-07T03.34-dab0658/job.log
 (1/2) nettle-tests.py:Nettle.test;run-run_type-upstream-040c: PASS (36.43 s)
 (2/2) nettle-tests.py:Nettle.test;run-run_type-distro-f6a8: ERROR: nettle source install failed. (5.12 s)
RESULTS    : PASS 1 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-07T03.34-dab0658/results.html
JOB TIME   : 54.17 s
```

**Review by Naresh-ibm — CHANGES_REQUESTED** [review]

**Review by abdhaleegit — APPROVED** [review]
explain about what is the test does ?  rest all LGTM

**Comment by nasastry** [comment]
README.txt added

```
RHEL:
JOB ID     : 9c38a03fa6c02f64303ebe6a4aefe8a76fae8dfd
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-19T01.16-9c38a03/job.log
 (1/2) nettle-tests.py:Nettle.test;run-run_type-upstream-040c: PASS (38.14 s)
 (2/2) nettle-tests.py:Nettle.test;run-run_type-distro-f6a8: ERROR: nettle source install failed. (6.38 s)
RESULTS    : PASS 1 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-19T01.16-9c38a03/results.html
JOB TIME   : 56.68 s


SLES:
JOB ID     : 7d594bb7e39231dd37aebd7bc9db6717720c19eb
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-19T11.44-7d594bb/job.log
 (1/2) nettle-tests.py:Nettle.test;run-run_type-upstream-040c: PASS (27.31 s)
 (2/2) nettle-tests.py:Nettle.test;run-run_type-distro-f6a8: PASS (25.25 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-19T11.44-7d594bb/results.html
JOB TIME   : 73.86 s
```

**Review by Naresh-ibm — APPROVED** [review]
LGTM

**Pull request merged**
