### PR TITLE
added mtu reset back for peer machine through public ip

### PR DESCRIPTION
**Pull request by smruti77**
when its fail through private interface it will reset back through
public ip.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@smruti77 please upload job.log file

**Comment by smruti77** [comment]
> @smruti77 please upload job.log file

@narasimhan-v don't have,i didn't got failure case,i tried with different mtu size in host and peer still its pinging.

**Comment by narasimhan-v** [comment]
Sure, working job.log in any case would be fine.

**Comment by smruti77** [comment]
JOB ID     : 96f0ed11f508239cd5bdbd60201fcfd425a527bf
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-04-08T23.53-96f0ed1/job.log
 (01/99) network_test.py:NetworkTest.test_gro;1500-130f: PASS (113.22 s)
 (02/99) network_test.py:NetworkTest.test_gro;2000-323d: PASS (112.20 s)
 (03/99) network_test.py:NetworkTest.test_gro;3000-5a66: PASS (110.19 s)
 (04/99) network_test.py:NetworkTest.test_gro;4000-79f6: PASS (111.59 s)
 (05/99) network_test.py:NetworkTest.test_gro;5000-b059: PASS (107.34 s)
 (06/99) network_test.py:NetworkTest.test_gro;6000-0a53: PASS (112.28 s)


JOB ID     : bfdbc335c63438f235b24a36e1b3b4d17569798a
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-04-09T00.06-bfdbc33/job.log
 (1/8) iperf_test.py:Iperf.test;2000-730e: PASS (92.85 s)
 (2/8) iperf_test.py:Iperf.test;3000-22d8: PASS (86.47 s)
 (3/8) iperf_test.py:Iperf.test;4000-ffaf: PASS (85.88 s)

JOB ID     : 37b33e0c94bee47b45dfec486cc95377506c52a4
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-04-09T00.24-37b33e0/job.log
 (01/18) multiport_stress.py:MultiportStress.test_multiport_ping;1500-f537: PASS (135.65 s)
 (02/18) multiport_stress.py:MultiportStress.test_multiport_ping;2000-03e2: PASS (136.49 s)

JOB ID     : 19c1d33a1e64eb214d944f776a665f013ce66968
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-04-09T00.31-19c1d33/job.log
 (01/21) bonding.py:Bonding.test_setup;round-robin-1313: PASS (81.81 s)
 (02/21) bonding.py:Bonding.test_run;round-robin-1313: PASS (119.19 s)
 (03/21) bonding.py:Bonding.test_cleanup;round-robin-1313: PASS (72.52 s)
 (04/21) bonding.py:Bonding.test_setup;active-backup-34c6: PASS (81.63 s)

JOB ID     : 1445a302d600f9262d96f2fa29b26838e98ef8e1
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-04-09T00.40-1445a30/job.log
 (01/63) tcpdump.py:TcpdumpTest.test;1500-nping_count-generic-f5e9: PASS (132.11 s)
 (02/63) tcpdump.py:TcpdumpTest.test;2000-nping_count-generic-b42b: PASS (106.93 s)
 (03/63) tcpdump.py:TcpdumpTest.test;3000-nping_count-generic-184b: PASS (111.03 s)

**Comment by narasimhan-v** [comment]
@smruti77 Please upload the log file also

**Comment by smruti77** [comment]
[bonding.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4454443/bonding.log)
[iperf.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4454444/iperf.log)
[multiport_stress.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4454446/multiport_stress.log)
[network_test.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4454451/network_test.log)
[tcpdump.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4454455/tcpdump.log)

**Comment by narasimhan-v** [comment]
@abdhaleegit @vaishnavibhat review please

**Pull request closed without merging**
