### PR TITLE
Fixing the directory creation issue in ltp_fs.py V2

### PR DESCRIPTION
**Pull request by Naresh-ibm**
There was an issue while creating a directory ltp_di_bin when script
goes for second iteration. The issue is, created dir are not getting
cleaned properly so it fails for rest of iteration. So this is fixed
and handled properly and script is now working fine.

Signed-off-by: Naresh Bannoth <nbannoth@in.ibm.com>

### CODE REVIEW

**Comment by Naresh-ibm** [comment]
[ltpfs_dir_issue_logs.tar.gz](https://github.com/avocado-framework-tests/avocado-misc-tests/files/1035645/ltpfs_dir_issue_logs.tar.gz)

**Comment by narasimhan-v** [comment]
@Naresh-ibm Do you get this issue even after https://github.com/avocado-framework-tests/avocado-misc-tests/pull/509 and  https://github.com/avocado-framework-tests/avocado-misc-tests/pull/514

**Comment by Naresh-ibm** [comment]
@narasimhan-v  #514 failed for me. I am seeing the same directory related issue.
the current PR is working fine.
@PraveenPenguin I will close #511 current PR is V2 of #511

**Comment by PraveenPenguin** [comment]
@Naresh-ibm thanks for helping(validation of PR) , @narasimhan-v can you please help us here ?

**Comment by narasimhan-v** [comment]
@PraveenPenguin @Naresh-ibm on it

**Comment by narasimhan-v** [comment]
@PraveenPenguin Just checked on the system provided by @Naresh-ibm and found that `make` fails there due to insufficient space. #514 is supposed to work, and as provided in the logs there, it works in a system that I tested.

**Comment by Naresh-ibm** [comment]
closing it in favour of #514

**Pull request closed without merging**
