### PR TITLE
Adding 24 hours yamls for HTX tests

### PR DESCRIPTION
**Pull request by narasimhan-v**
Adding 24 hours yamls for HTX tests.

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@PraveenPenguin These are just yaml changes. I hope they can be merged ?

**Comment by narasimhan-v** [comment]
> @narasimhan-v I feel YAML file can be maintained via user in upstream we can have only sample copy

@PraveenPenguin I do not understand. Can you please explain a bit more.

**Comment by PraveenPenguin** [comment]
> > @narasimhan-v I feel YAML file can be maintained via user in upstream we can have only sample copy
> 
> @PraveenPenguin I do not understand. Can you please explain a bit more.

what i meant as we can have sample YMAL file or if test case has nature to pass to have another YAML  that time also we have sample YAML, if  user want to his custom YAML he/she need to have it saved in local as i don't feel it should be part of the upstream repo  as in this case we have two YAML 
1-htx_nic_devices_24_hours.yaml (from the block device  we can have commented part what need to be there )
2- htx_all_devices.yaml

**Comment by narasimhan-v** [comment]
@PraveenPenguin Are we discussing 2 things here ?
1. multiple yamls
2. upstream vs local

**Comment by narasimhan-v** [comment]
@PraveenPenguin I just realised I don't need the duplicate yamls. Will send an update by changing the default timing on them. Thanks

**Pull request closed without merging**
