### PR TITLE
kernel-hardening-tests.py: Add kernel hardening config check test

### PR DESCRIPTION
**Pull request by nasastry**
Add kernel hardening configuration check tests.

Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>

### CODE REVIEW

**Comment by nasastry** [comment]
```
RHEL:
JOB ID     : c10c01b17143baca30a3d0a032d06bedae35ee9c
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T03.53-c10c01b/job.log
 (1/1) kernel-hardening-tests.py:KerelHardConfig.test: PASS (0.46 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T03.53-c10c01b/results.html
JOB TIME   : 11.65 s


SLES:
JOB ID     : c884aa5814faa50c4574359af960249eadf7a1d4
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T14.21-c884aa5/job.log
 (1/1) kernel-hardening-tests.py:KerelHardConfig.test: PASS (0.60 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T14.21-c884aa5/results.html
JOB TIME   : 19.51 s
```

**Comment by nasastry** [comment]
```
RHEL:
JOB ID     : a3bde0283c90b46c321a073a829ca6f2f51fe1ed
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T04.48-a3bde02/job.log
 (1/1) kernel-hardening-tests.py:KerelHardConfig.test: PASS (0.56 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T04.48-a3bde02/results.html
JOB TIME   : 11.86 s

SLES:
JOB ID     : 7c6ee536466e842e290ceb6c4aa3c7653c9d4c63
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T15.15-7c6ee53/job.log
 (1/1) kernel-hardening-tests.py:KerelHardConfig.test: PASS (0.66 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T15.15-7c6ee53/results.html
JOB TIME   : 19.68 s
```

**Review by abdhaleegit — APPROVED** [review]
Is the test specific to ppc? 

Rest all LGTM

**Comment by abdhaleegit** [comment]
If config option is not in the config files  is taken care?

**Comment by nasastry** [comment]
> If config option is not in the config files is taken care?

@abdhaleegit yes, taken care.
```
self.no_config set to null list.

 if ret == linux_modules.ModuleConfig.NOT_SET:
             self.no_config.append(config_option)
 when the config not set, that config will be appended to no_config list.
 
 if no_config list is not empty then the test case will fail.
```
Thanks!!

**Pull request merged**
