### PR TITLE
Correcting the changed library function name in disk_info test 

### PR DESCRIPTION
**Pull request by Naresh-ibm**
Name of a multipath library function that used in disk_info.py
has changed. corrected it with new changed function name

Signed-off-by: Naresh Bannoth <nbannoth@in.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@Naresh-ibm has this util change merged ?

**Comment by Naresh-ibm** [comment]
> @Naresh-ibm has this util change merged ?
> 
> If not, add the link to utils PR, and also add `[Waiting for utils]` in the PR heading

it is approved and waiting for merge @narasimhan-v 
I will `[Waiting for utils]` in the PR heading.

**Comment by Naresh-ibm** [comment]
@narasimhan-v  the new function have got merged. so please merge this PR.

**Comment by narasimhan-v** [comment]
@Naresh-ibm please update the related issue also and close it

**Pull request merged**
