### PR TITLE
Test to run filesystem tests on a user specified disk

### PR DESCRIPTION
**Pull request by hathyaga**
This test uses LTP to run fs tests

Signed-off-by: Harsha Thyagaraja <harshkid@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@hathyaga job.log please

**Comment by apahim** [comment]
Could this be merged with https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/generic/ltp.py ?

**Comment by PraveenPenguin** [comment]
@apahim same line we discussed in earlier PR https://github.com/avocado-framework-tests/avocado-misc-tests/pull/218 of this test , this test require some extra setup so we think we can kept it separate and this test case can be base of test which requires same setup like file system creation , what you say ?

**Comment by hathyaga** [comment]
[job.log.tar.gz](https://github.com/avocado-framework-tests/avocado-misc-tests/files/707740/job.log.tar.gz)

**Comment by narasimhan-v** [comment]
Looks good to me.

**Comment by PraveenPenguin** [comment]
@hathyaga @narasimhan-v thanks

**Pull request merged**
