### PR TITLE
producer-consumer.py: Parse results, store in json

### PR DESCRIPTION
**Pull request by harish-24**
Patch adds result parsing and stores it to json file

Signed-off-by: Harish <harish@linux.ibm.com>

### CODE REVIEW

**Comment by harish-24** [comment]
```
# cat /home/harish/avocado-fvt-wrapper/results/job-2021-04-15T20.20-18916c9/test-results/1-cpu_producer_consumer.py_Producer_Consumer.test_run-consumer-stats-default-consumer-duration-load-perf-precompute-producer-random-statistics-30bf/time_log.json 
{"iterations": "50856", "iter_time": "43357", "access_time": "42"}
```

**Review by PraveenPenguin — COMMENTED** [review]
@harish-24 looks good to this patch , one suggestion can we  use this Json out put to verify some performance matrix as example  it can be user defined input which we can match with json fields

**Comment by harish-24** [comment]
> @harish-24 looks good to this patch , one suggestion can we use this Json out put to verify some performance matrix as example it can be user defined input which we can match with json fields

Sorry, dint get the point. can you elaborate?

**Comment by harish-24** [comment]
> @harish-24 looks good to this patch , one suggestion can we use this Json out put to verify some performance matrix as example it can be user defined input which we can match with json fields

I kind of get your point. The whole purpose of storing as a human/machine readable format is to make use of that in  various follow up scripts. It is hard for a user to find a user-defined baseline metric considering the dynamic change in environment. Rather this can be run across different environments and compared against each other. And that again cannot be part of this standalone test.

**Comment by PraveenPenguin** [comment]
> > @harish-24 looks good to this patch , one suggestion can we use this Json out put to verify some performance matrix as example it can be user defined input which we can match with json fields
> 
> I kind of get your point. The whole purpose of storing as a human/machine readable format is to make use of that in various follow up scripts. It is hard for a user to find a user-defined baseline metric considering the dynamic change in environment. Rather this can be run across different environments and compared against each other. And that again cannot be part of this standalone test.

@harish-24 thanks for info , yes make sense we can make this in

**Review by PraveenPenguin — APPROVED** [review]

**Pull request merged**
