### PR TITLE
changes for multiple vnic with different adapter id

### PR DESCRIPTION
**Pull request by smruti77**
script will create mutiple vnic with adapter id and different port.
because we can't create bond interfcae with same slot num vnic
interfaces.

Signed-off-by: Bismruti Pattjoshi <bismruti@oc7660885027.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
[vnic.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5371010/vnic.log)

**Review by abdhaleegit — CHANGES_REQUESTED** [review]
Please push the sample yaml for these changes to be used and also add the definitions in Readme

1. yaml for single vnic device (no backing device)
2. yaml for single vnic with single backing device
3. yaml for multiple vnic device with out backing device
4. yaml for multiple vnic with multiple backing device

also add which of the option do not work for now in README.

TODO list

**Comment by abdhaleegit** [comment]
@smruti77  also a regression run with other variation to make sure nothing breaks.. paste the logs for all the working scenario

**Comment by smruti77** [comment]
@abdhaleegit  for now test is not support for multiple vnic with multiple backing device.

**Comment by smruti77** [comment]
#1948

**Pull request closed without merging**
