### PR TITLE
Added mq related parameter to ibmvfc driver_parameter test yaml file

### PR DESCRIPTION
**Pull request by Naresh-ibm**
we got new parameters added to ibmvfc driver. so added them to yaml for
regular testing.
distro_tools.py is now part of common directory. And we had only readme.txt
file left in pci directory where distro_tools.py was there earlier.
So moved this to io/common/distro_tools.data dir from pci to common

Signed-off-by: Naresh Bannoth <nbannoth@in.ibm.com>

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@Naresh-ibm can you please attach snippet of job log

**Comment by Naresh-ibm** [comment]
@PraveenPenguin 


localhost:~/avocado-fvt-wrapper/tests/avocado-misc-tests/io/driver # avocado run --test-runner runner driver_parameter_block_device.py -m driver_parameter_block_device.py.data/driver_parameter_block_device_ibmvfc.yaml
JOB ID     : 166f96adee450f378d63ac3591dabfc124b98616
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2022-01-11T07.39-166f96a/job.log
 (01/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-mq-value-mq_0-749b: PASS (215.43 s)
 (02/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-mq-value-mq_1-e328: PASS (227.11 s)
 (03/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-mq-value-mq_10-03bd: PASS (197.14 s)
 (04/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-scsi_host_queues-value-scsi_host_queues_4-d250: PASS (256.22 s)
 (05/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-scsi_host_queues-value-scsi_host_queues_8-0113: PASS (218.19 s)
 (06/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-scsi_host_queues-value-scsi_host_queues_12-e3be: PASS (226.04 s)
 (07/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-scsi_host_queues-value-scsi_host_queues_16-c7e1: PASS (229.63 s)
 (08/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-scsi_host_queues-value-scsi_host_queues_20-710a: PASS (230.38 s)
 (09/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-scsi_hw_channels-value-scsi_hw_channels_4-8e97: PASS (226.60 s)
 (10/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-scsi_hw_channels-value-scsi_hw_channels_8-d410: PASS (136.26 s)
 (11/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-scsi_hw_channels-value-scsi_hw_channels_12-6b4d: PASS (154.40 s)
 (12/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-scsi_hw_channels-value-scsi_hw_channels_16-5729: PASS (277.93 s)
 (13/13) driver_parameter_block_device.py:Moduleparameter.test;run-Test-scsi_hw_channels-value-scsi_hw_channels_20-7b27: PASS (228.86 s)
RESULTS    : PASS 13 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2022-01-11T07.39-166f96a/results.html
JOB TIME   : 2856.35 s
localhost:~/avocado-fvt-wrapper/tests/avocado-misc-tests/io/driver #

**Review by PraveenPenguin — APPROVED** [review]

**Comment by Naresh-ibm** [comment]
[driver_parameter_ibmvfc_mq_job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7853062/driver_parameter_ibmvfc_mq_job.log)

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Pull request merged**
