### PR TITLE
ima-modsig-tests.py: Cancel the test for RHEL8 series

### PR DESCRIPTION
**Pull request by nasastry**
Cancel the test for RHEL8 series. This feature is there in RHEL9 and SLES15 series of releases.

### CODE REVIEW

**Comment by nasastry** [comment]
```
RHEL9.3:
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-09-26T01.48-d041545/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: STARTED
 (1/1) ima-modsig-tests.py:IMAmodsig.test: PASS (0.38 s)

RHEL8.9:
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-09-26T01.33-9413ef6/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: STARTED
 (1/1) ima-modsig-tests.py:IMAmodsig.test: CANCEL: This test not applicable to RHEL8 series (0.01 s)

SLES15SP5:
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-09-26T12.16-192d397/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: STARTED
 (1/1) ima-modsig-tests.py:IMAmodsig.test: PASS (0.03 s)


```

**Review by PraveenPenguin — APPROVED** [review]

**Comment by PraveenPenguin** [comment]
@nasastry please address Travis CI  failure and we are good to go

**Comment by Naresh-ibm** [comment]
@nasastry please re-send this PR and make sure to clear Travis issues

**Comment by nasastry** [comment]
@PraveenPenguin @Naresh-ibm Sorry somehow missed this notification. Fixed it now. Thank You.

**Comment by nasastry** [comment]
```
# avocado run --max-parallel-tasks=1 ima-modsig-tests.py
JOB ID     : 3344fc4bd228c1ab8c401ed82340cc81efd36cdc
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-10-30T00.12-3344fc4/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: STARTED
 (1/1) ima-modsig-tests.py:IMAmodsig.test: CANCEL: This test not applicable to RHEL8 series (0.01 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2023-10-30T00.12-3344fc4/results.html
JOB TIME   : 2.54 s
```

**Pull request merged**
