### PR TITLE
fixed distro_tools for other interface type.

### PR DESCRIPTION
**Pull request by smruti77**
firxed distro_tools for all type interface.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
network
------------
JOB ID     : 60e433eb2e988d3d9d0fe3bebf13f4c7a0b312a7
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-04-06T00.53-60e433e/job.log
 (01/26) distro_tools.py:DisrtoTool.test;lsslot_pci-194a: PASS (1.12 s)
 (02/26) distro_tools.py:DisrtoTool.test;lsslot_pci_-a-01ba: PASS (0.57 s)
 (03/26) distro_tools.py:DisrtoTool.test;lsslot_phb-8a37: PASS (0.59 s)
 (04/26) distro_tools.py:DisrtoTool.test;lsslot_pci_-o-dbce: PASS (0.57 s)
 (05/26) distro_tools.py:DisrtoTool.test;lsslot_slot-df7a: PASS (0.72 s)
 (06/26) distro_tools.py:DisrtoTool.test;netstat_a-f9a4: PASS (6.43 s)
 (07/26) distro_tools.py:DisrtoTool.test;netstat_l-9dc3: PASS (0.58 s)
 (08/26) distro_tools.py:DisrtoTool.test;netstat_s-2a34: PASS (0.59 s)
 (09/26) distro_tools.py:DisrtoTool.test;netstat_r-7db8: PASS (0.58 s)
 (10/26) distro_tools.py:DisrtoTool.test;netstat_i-ccf8: PASS (0.57 s)
 (11/26) distro_tools.py:DisrtoTool.test;lsprop_R-06fe: PASS (0.66 s)
 (12/26) distro_tools.py:DisrtoTool.test;lsprop_r-c0fd: PASS (0.60 s)
 (13/26) distro_tools.py:DisrtoTool.test;lsvio_s-6fc5: PASS (1.53 s)
 (14/26) distro_tools.py:DisrtoTool.test;lsvio_e-e9ce: PASS (0.57 s)
 (15/26) distro_tools.py:DisrtoTool.test;lsvio_D-cebe: PASS (0.92 s)
 (16/26) distro_tools.py:DisrtoTool.test;lsvio_d-2491: PASS (0.60 s)
 (17/26) distro_tools.py:DisrtoTool.test;test_opt-c569: PASS (1.63 s)
 (18/26) distro_tools.py:DisrtoTool.test;lsdevinfo_R-13cc: PASS (1.52 s)
 (19/26) distro_tools.py:DisrtoTool.test;lsdevinfo_c-17fd: PASS (1.31 s)
 (20/26) distro_tools.py:DisrtoTool.test;usysident_identify_l-4d4d: PASS (1.90 s)
 (21/26) distro_tools.py:DisrtoTool.test;usysident_identify_d-b969: PASS (0.54 s)
 (22/26) distro_tools.py:DisrtoTool.test;usysident_normal_l-30e2: PASS (2.13 s)
 (23/26) distro_tools.py:DisrtoTool.test;usysident_normal_d-22e0: PASS (0.53 s)
 (24/26) distro_tools.py:DisrtoTool.test;usysattn_normal_l-7f55: PASS (0.69 s)
 (25/26) distro_tools.py:DisrtoTool.test;ofpathname_l-d362: FAIL: ofpathname failed (0.55 s)
 (26/26) distro_tools.py:DisrtoTool.test;ofpathname_a-5632: FAIL: ofpathname failed (0.69 s)
RESULTS    : PASS 24 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 29.64 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-04-06T00.53-60e433e/results.html

**Comment by smruti77** [comment]
fc
----
JOB ID     : 8ff9dfc97583d346411cb9ec1f9501ef9224c623
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-04-06T10.26-8ff9dfc/job.log
 (01/26) distro_tools.py:DisrtoTool.test;lsslot_pci-cad7: PASS (5.95 s)
 (02/26) distro_tools.py:DisrtoTool.test;lsslot_pci_-a-dc10: FAIL: Failed to display hot plug slots (6.01 s)
 (03/26) distro_tools.py:DisrtoTool.test;lsslot_phb-ad91: PASS (6.02 s)
 (04/26) distro_tools.py:DisrtoTool.test;lsslot_pci_-o-38a0: PASS (5.93 s)
 (05/26) distro_tools.py:DisrtoTool.test;lsslot_slot-b912: PASS (6.05 s)
 (06/26) distro_tools.py:DisrtoTool.test;netstat_a-d434: PASS (3.18 s)
 (07/26) distro_tools.py:DisrtoTool.test;netstat_l-694c: PASS (3.14 s)
 (08/26) distro_tools.py:DisrtoTool.test;netstat_s-3239: PASS (3.14 s)
 (09/26) distro_tools.py:DisrtoTool.test;netstat_r-2447: PASS (3.10 s)
 (10/26) distro_tools.py:DisrtoTool.test;netstat_i-e653: PASS (3.10 s)
 (11/26) distro_tools.py:DisrtoTool.test;lsprop_R-72f1: PASS (4.02 s)
 (12/26) distro_tools.py:DisrtoTool.test;lsprop_r-c4a6: PASS (4.04 s)
 (13/26) distro_tools.py:DisrtoTool.test;lsvio_s-c578: PASS (3.12 s)
 (14/26) distro_tools.py:DisrtoTool.test;lsvio_e-79ad: PASS (3.10 s)
 (15/26) distro_tools.py:DisrtoTool.test;lsvio_D-4389: PASS (4.68 s)
 (16/26) distro_tools.py:DisrtoTool.test;lsvio_d-0643: PASS (3.12 s)
 (17/26) distro_tools.py:DisrtoTool.test;test_opt-4fb6: PASS (3.33 s)
 (18/26) distro_tools.py:DisrtoTool.test;lsdevinfo_R-6365: PASS (3.33 s)
 (19/26) distro_tools.py:DisrtoTool.test;lsdevinfo_c-31c0: PASS (3.33 s)
 (20/26) distro_tools.py:DisrtoTool.test;usysident_identify_l-4efc: WARN: Test passed but there were warnings during execution. Check the log for details. (3.13 s)
 (21/26) distro_tools.py:DisrtoTool.test;usysident_identify_d-43cf: PASS (5.77 s)
 (22/26) distro_tools.py:DisrtoTool.test;usysident_normal_l-9726: WARN: Test passed but there were warnings during execution. Check the log for details. (3.13 s)
 (23/26) distro_tools.py:DisrtoTool.test;usysident_normal_d-44db: PASS (6.05 s)
 (24/26) distro_tools.py:DisrtoTool.test;usysattn_normal_l-3151: WARN: Test passed but there were warnings during execution. Check the log for details. (3.10 s)
 (25/26) distro_tools.py:DisrtoTool.test;ofpathname_l-cdae: FAIL: ofpathname failed (3.19 s)
 (26/26) distro_tools.py:DisrtoTool.test;ofpathname_a-941a: FAIL: ofpathname failed (3.20 s)
RESULTS    : PASS 20 | ERROR 0 | FAIL 3 | SKIP 0 | WARN 3 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 106.07 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-04-06T10.26-8ff9dfc/results.html

**Comment by narasimhan-v** [comment]
@harihare @Naresh-ibm review please

**Comment by smruti77** [comment]
@narasimhan-v can i add README.txt for this test. so they can provide "adapter_type" for different interface.

**Comment by narasimhan-v** [comment]
@smruti77 Sure

**Pull request closed without merging**
