### PR TITLE
Perf stressng test fixes

### PR DESCRIPTION
**Pull request by kjain101**
Made changes in perf/perf_stress_ng.py test to fix vmstat calculation and change percentage calculation part.
Also add code to find system CPU frequency for calculations.

This pull request changes are rebased on top of latest master branch and also had changes suggested by Naresh.

Thanks!

### CODE REVIEW

**Comment by kjain101** [comment]
@PraveenPenguin Can you accept this pull request.

Thanks!

**Review by Naresh-ibm — APPROVED** [review]
LGTM

**Review by disgoel — APPROVED** [review]
Looks good to me.

[root@ ]# avocado run perf_stress_ng.py -m perf_stress_ng.py.data/perf_stress_ng.yaml --max-parallel-tasks=1
Fetching asset from perf_stress_ng.py:Stressng.test
JOB ID     : 5c8efeb4925238c505125ae08ecdabe2ad1f577c
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-08-25T12.11-5c8efeb/job.log
 (1/1) perf_stress_ng.py:Stressng.test;run-coverage-run_type-df37: STARTED
 (1/1) perf_stress_ng.py:Stressng.test;run-coverage-run_type-df37: WARN: Test passed but there were warnings during execution. Check the log for details. (199.49 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 1 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2023-08-25T12.11-5c8efeb/results.html
JOB TIME   : 202.41 s

**Comment by manvanthar** [comment]
Looks fine.

**Review by manvanthar — APPROVED** [review]

**Pull request merged**
