### PR TITLE
Included the ethtool -l and ethtool -L options

### PR DESCRIPTION
**Pull request by TasmiyaNalatwad**
ethtool -l
ethtool -L ethx tx [N] rx [N]

Signed-off-by: Tasmiya Nalatwad <tasmiya@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by TasmiyaNalatwad** [comment]
@abdhaleegit @PraveenPenguin  As are_packets_lost function is merged by beraldo i utils we can add the ethtool.py changes which where reverted before.
PR of util function : https://github.com/avocado-framework/avocado/pull/5361

Please find the results below

[root@ltcrain41-lp4 net]# avocado run --test-runner runner ethtool_test.py -m ethtool_test.py.data/ethtool_test.yaml
Error running method "pre_tests" of plugin "fetchasset": 'Subscript' object has no attribute 'id'
JOB ID     : c7f4ff8ba94a3dd2eb436250b82c03be590e913a
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2022-05-26T02.48-c7f4ff8/job.log
 (01/18) ethtool_test.py:Ethtool.test_ethtool;run-args-PrivateFlag-hbond-c13a: CANCEL: Device Doesn't support Private flags (5.44 s)
 (02/18) ethtool_test.py:Ethtool.test_ethtool;run-args-Driver-hbond-342a: PASS (12.31 s)
 (03/18) ethtool_test.py:Ethtool.test_ethtool;run-args-Autonegotiation-hbond-5b06: FAIL: -r failed (9.70 s)
 (04/18) ethtool_test.py:Ethtool.test_ethtool;run-args-PauseParameter-hbond-243d: PASS (12.48 s)
 (05/18) ethtool_test.py:Ethtool.test_ethtool;run-args-Coalescing-hbond-f168: PASS (11.42 s)
 (06/18) ethtool_test.py:Ethtool.test_ethtool;run-args-RegisterDump-hbond-ebe4: PASS (11.34 s)
 (07/18) ethtool_test.py:Ethtool.test_ethtool;run-args-EEPROMDump-hbond-b337: PASS (96.41 s)
 (08/18) ethtool_test.py:Ethtool.test_ethtool;run-args-RingParameter-hbond-0952: PASS (11.35 s)
 (09/18) ethtool_test.py:Ethtool.test_ethtool;run-args-ShowOffloadProtocolFeature-hbond-ea8c: PASS (12.46 s)
 (10/18) ethtool_test.py:Ethtool.test_ethtool;run-args-AdapterInitiate-hbond-d0b2: PASS (16.36 s)
 (11/18) ethtool_test.py:Ethtool.test_ethtool;run-args-Statistics-hbond-f719: PASS (12.29 s)
 (12/18) ethtool_test.py:Ethtool.test_ethtool;run-args-SelfTest-hbond-13ef: FAIL: -t failed (11.59 s)
 (13/18) ethtool_test.py:Ethtool.test_ethtool;run-args-Show-permaddr-hbond-fb74: PASS (12.30 s)
 (14/18) ethtool_test.py:Ethtool.test_ethtool;run-args-Get-dump-hbond-2d2f: WARN: Test passed but there were warnings during execution. Check the log for details. (11.53 s)
 (15/18) ethtool_test.py:Ethtool.test_ethtool;run-args-Show-time-stamping-hbond-e812: PASS (12.46 s)
 (16/18) ethtool_test.py:Ethtool.test_ethtool;run-args-Get-phy-tunable-hbond-8a6f: WARN: Test passed but there were warnings during execution. Check the log for details. (12.23 s)
 (17/18) ethtool_test.py:Ethtool.test_ethtool;run-args-Show-channels-hbond-bfd5: PASS (12.34 s)
 (18/18) ethtool_test.py:Ethtool.test_ethtool;run-args-Set-channels-combined_channel-other_channel-hbond-e32e: PASS (106.61 s)
RESULTS    : PASS 13 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 2 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2022-05-26T02.48-c7f4ff8/results.html
JOB TIME   : 391.90 s

[job.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/8777373/job.zip)

**Review by PraveenPenguin — APPROVED** [review]

**Review by Naresh-ibm — APPROVED** [review]

**Review by vaishnavibhat — APPROVED** [review]
LGTM

**Comment by abdhaleegit** [comment]
@TasmiyaNalatwad run logs please

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Comment by abdhaleegit** [comment]
Thanks for your your patch and patience

**Pull request merged**
