### PR TITLE
added mtu set for host and peer in bonding.py

### PR DESCRIPTION
**Pull request by smruti77**
added mtu set and differnt yaml files are also added to the list to
address different scenario based testing for mode 0,1, and 4

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>
Author: Vaishnavi Bhat vaishnavi@linux.vnet.ibm.com

### CODE REVIEW

**Comment by smruti77** [comment]
[bonding_mtu.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4287582/bonding_mtu.log)

**Comment by narasimhan-v** [comment]
@manvanthar @abdhaleegit review please

**Comment by narasimhan-v** [comment]
@smruti77 Can you please resolve conflict / rebase

**Comment by smruti77** [comment]
> @smruti77 Can you please resolve conflict / rebase

@narasimhan-v ok

**Comment by smruti77** [comment]
handle this in #1606

**Pull request closed without merging**
