### PR TITLE
Fixed dapl tests script and parameters v2

### PR DESCRIPTION
**Pull request by manvanthar**
optimised dapl script code and added additional scenarios to dapl tests

Signed-off-by: Manvanthara Puttashankar <manvanth@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by manvanthar** [comment]
JOB ID : 3c31913468a334ca07b371a8842f2e672b29c324
JOB LOG : /root/avocado-fvt-wrapper/results/job-2019-07-16T08.39-3c31913/job.log
(1/5) dapl.sh;first-73b9: PASS (11.46 s)
(2/5) dapl.sh;second-3467: PASS (12.49 s)
(3/5) dapl.sh;third-0e32: PASS (22.26 s)
(4/5) dapl.sh;fourth-c93b: PASS (11.48 s)
(5/5) dapl.sh;fifth-bd3f: PASS (3.14 s)
RESULTS : PASS 5 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME : 61.67 s
JOB HTML : /root/avocado-fvt-wrapper/results/job-2019-07-16T08.39-3c31913/results.html

**Comment by narasimhan-v** [comment]
@manvanthar There are no additional scenarios here. Can it be mentioned as corrected the way these are run ?

**Comment by manvanthar** [comment]
@narasimhan-v   Eventhough the total count seems 5.   in the second and third iterationswith respect to yaml.  Scenarios have been extended.

**Comment by narasimhan-v** [comment]
@manvanthar ok, overlooked that.

**Pull request merged**
