### PR TITLE
Adding raw and name event tests

### PR DESCRIPTION
**Pull request by nasastry**
Adding Power9, Power8 raw and name event test cases.
From the list of raw or name events perf stat command runs.

Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by nasastry** [comment]
Power9 results with ‘fail’:
```
 JOB ID     : 91dc0a9a2e9e8e62472f74d9552cc8eec224679e
JOB LOG    : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-03-28T20.12-91dc0a9/job.log
 (1/2) perf_rawevents.py:perfRawevents.test_raw_events:  FAIL: perf_raw_events: some of the events failed, refer to log (1278.68 s)
(2/2) perf_rawevents.py:perfRawevents.test_name_events:  CANCEL: Tests are not supported on power9 (0.74 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB TIME   : 1280.05 s
```

Power9 results:
```
JOB ID     : 5e715784d6f48d2649298ce9b22ef5d9664157da
JOB LOG    : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-03-29T07.20-5e71578/job.log
 (1/2) perf_rawevents.py:perfRawevents.test_raw_events:  PASS (1277.84 s)
 (2/2) perf_rawevents.py:perfRawevents.test_name_events:  CANCEL: Tests are not supported on power9 (0.74 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB TIME   : 1279.05 s
```

Power8 results:
```
JOB ID     : 38137d28c6b0250b3292a7e5540aeaf45c9ef03b
JOB LOG    : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-03-29T07.20-38137d2/job.log
 (1/2) perf_rawevents.py:perfRawevents.test_raw_events:  PASS (3250.10 s)
 (2/2) perf_rawevents.py:perfRawevents.test_name_events:  PASS (1115.17 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 4365.78 s
JOB HTML   : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-03-29T07.20-38137d2/results.html
```

**Comment by nasastry** [comment]
@harish-24 Implemented the changes requested. Please review.

Test results with the modified code:
Power9 results:
```
JOB ID     : 24db2ed19e291d12df4d4cd6f6c15e650c4da4b0
JOB LOG    : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-04-02T11.26-24db2ed/job.log
 (1/3) perf_rawevents.py:perfRawevents.test_raw_events_power8:  SKIP: Supported only on Power8
 (2/3) perf_rawevents.py:perfRawevents.test_name_events_power8:  SKIP: Supported only on Power8
 (3/3) perf_rawevents.py:perfRawevents.test_raw_events_power9:  PASS (1277.69 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 2 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1278.43 s
JOB HTML   : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-04-02T11.26-24db2ed/results.html
```

Power8 results:
```
JOB ID     : 4981fe8d129a273541d8e77812aeef8ade372cf3
JOB LOG    : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-04-02T02.00-4981fe8/job.log
 (1/3) perf_rawevents.py:perfRawevents.test_raw_events_power8:  PASS (1720.91 s)
 (2/3) perf_rawevents.py:perfRawevents.test_name_events_power8:  PASS (877.88 s)
 (3/3) perf_rawevents.py:perfRawevents.test_raw_events_power9:  SKIP: Supported only on Power9
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 1 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 2599.34 s
JOB HTML   : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-04-02T02.00-4981fe8/results.html
```

**Comment by harish-24** [comment]
@PraveenPenguin @narasimhan-v  Is it okay to dump raw_codes in this repository? Other than that this looks good to me.

**Comment by PraveenPenguin** [comment]
@harish-24 seems me fine

**Comment by PraveenPenguin** [comment]
@harish-24 thanks for ACK

**Pull request merged**
