### PR TITLE
module parameter generic yaml for dirvers

### PR DESCRIPTION
**Pull request by abdhaleegit**
Created a new yaml which is generic for driver param testing

Signed-off-by: Abdul Haleem <abdhalee@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@abdhaleegit Can you explain the use cases a bit more please ?

**Comment by abdhaleegit** [comment]
> @abdhaleegit Can you explain the use cases a bit more please ?
As we cannot use the yaml for different adapter, so wanted to have a template to create yaml for different adapter.. but looks like we need yaml for each driver separately so here is the new one https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1698

**Comment by abdhaleegit** [comment]
can we close this one

**Comment by abdhaleegit** [comment]
@narasimhan-v @vaishnavibhat @smruti77 cant we have single yaml for all drivers

because it will be diffcult for me to handle in cfg bucket... I need to have separate bucket for each driver

**Comment by narasimhan-v** [comment]
@abdhaleegit this is a valid point, we can discuss and decide this locally. Please open an internal issue.

**Comment by abdhaleegit** [comment]
https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1716

**Pull request closed without merging**
