### PR TITLE
Added pjdfstest

### PR DESCRIPTION
**Pull request by PraveenPenguin**
Added pjdfstest : test suite that  POSIX system calls

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
job log:

```[root@f200-lp4 ~]# avocado run pjdfstest.py 
Failed to load plugin from module "avocado_vt.plugins.vt_list": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
Failed to load plugin from module "avocado_vt.plugins.vt": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
JOB ID     : 17ea072107432e180491a251e1a699ef9e09538f
JOB LOG    : /home/nasastry/avocado-fvt-wrapper/results/job-2018-07-06T03.19-17ea072/job.log
 (1/1) pjdfstest.py:Pjdfstest.test: FAIL (417.85 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 430.49 s
JOB HTML   : /home/nasastry/avocado-fvt-wrapper/results/job-2018-07-06T03.19-17ea072/results.html
[root@f200-lp4 ~]# 
```

**Comment by PraveenPenguin** [comment]
@narasimhan-v for travis  it pass any specific  issue you are pointing  ?

**Comment by narasimhan-v** [comment]
@PraveenPenguin lines 63 and 65

**Comment by PraveenPenguin** [comment]
@narasimhan-v ah sure , pushed changes please check

**Pull request merged**
