### PR TITLE
Adding tests to nvme-cli test

### PR DESCRIPTION
**Pull request by narasimhan-v**
Added the following tests to nvme-cli test.
*) compare
*) flush
*) writezeroes
*) writeuncorrectable
*) dsm
*) reset
*) subsystemreset

Also made sure installation of nvme-cli is skipped,
if latest nvme is installed already.

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
[job_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/524309/job_log.txt)

**Comment by PraveenPenguin** [comment]
can you please use  fetch_asset as well it will help to avoid clone repo multiple times 

link can be https://github.com/linux-nvme/nvme-cli/archive/master.zip

code can be 
```
        locations = ["https://github.com/linux-nvme/nvme-cli/archive/"
                     "master.zip"]
        tarball = self.fetch_asset("nvme-cli.zip", locations=locations,
                                   expire='10d') 
        self.srcdir = os.path.join(self.srcdir, 'nvme-cli-master')
```

you can redefine self.srcdir because  as test ruin require nvme-cli-master and after run it got removed

**Comment by narasimhan-v** [comment]
@PraveenPenguin sure, will do that.

**Comment by narasimhan-v** [comment]
@PraveenPenguin Created new PR #116

**Pull request closed without merging**
