### PR TITLE
Add daxctl list test for devdax namespaces and minor fix

### PR DESCRIPTION
**Pull request by harish-24**
* Add daxctl list test for devdax namespaces
Patch adds daxctl test for devdax namespaces which is provided as part of ndctl package

* Fix ndctl with proper modes 
Test had wrong set of modes, patch fixes it

Signed-off-by: Harish <harish@linux.ibm.com>

### CODE REVIEW

**Comment by harish-24** [comment]
*   Add test for writing daxdev devices
Patch adds test for writing daxdev devices with daxio binary

*    Add test for fsdax with fio workload
Patch adds test for fsdax mode with basic fio workload job

**Comment by harish-24** [comment]
* ndctl.py: changes to make ndctl list method generic
Patch changes the way get_json method works as it now provides a
common option to get any data with ndctl list. Patch also takes
care of the selecting the largest region instead of the first
available region.

**Comment by harish-24** [comment]
``` 
 (01/15) memory/ndctl.py:NdctlTest.test_bus_ids: PASS (0.09 s)
 (02/15) memory/ndctl.py:NdctlTest.test_dimms: PASS (0.07 s)
 (03/15) memory/ndctl.py:NdctlTest.test_regions: PASS (0.11 s)
 (04/15) memory/ndctl.py:NdctlTest.test_namespace: PASS (7.01 s)
 (05/15) memory/ndctl.py:NdctlTest.test_namespace_modes: FAIL: Namespace for ['raw'] mode failed! (7.27 s)
 (06/15) memory/ndctl.py:NdctlTest.test_multiple_namespaces_region: PASS (1.76 s) 
 (07/15) memory/ndctl.py:NdctlTest.test_multiple_ns_modes_region: PASS (0.96 s)
 (08/15) memory/ndctl.py:NdctlTest.test_multiple_ns_multiple_region: PASS (2.90 s)
 (09/15) memory/ndctl.py:NdctlTest.test_namespace_reconfigure: FAIL: New namespace unexpected change(s): [{'align': 16777216}] (5.43 s)
 (10/15) memory/ndctl.py:NdctlTest.test_check_namespace: FAIL: Failed to check namespace metadata (0.94 s)
 (11/15) memory/ndctl.py:NdctlTest.test_check_numa: PASS (0.13 s)
 (12/15) memory/ndctl.py:NdctlTest.test_label_read_write: PASS (5.23 s)
 (13/15) memory/ndctl.py:NdctlTest.test_daxctl_list: PASS (2.72 s)
 (14/15) memory/ndctl.py:NdctlTest.test_fsdax_write: PASS (145.53 s)
 (15/15) memory/ndctl.py:NdctlTest.test_devdax_write: PASS (697.41 s)
RESULTS    : PASS 12 | ERROR 0 | FAIL 3 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Comment by narasimhan-v** [comment]
Merging based on @PraveenPenguin ACK

**Pull request merged**
