### PR TITLE
Resolving cleanup issue and enahncing yaml in ltp_fs.py

### PR DESCRIPTION
**Pull request by Naresh-ibm**
enhancing yaml and the code to handle the proper cleanup after
each test varient runs.

Signed-off-by: Naresh Bannoth <nbannoth@in.ibm.com>

### CODE REVIEW

**Comment by Naresh-ibm** [comment]
[cleanup_run_logs.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/9009913/cleanup_run_logs.txt)

**Comment by Naresh-ibm** [comment]
[cleanup-issue-debug-log.tar.gz](https://github.com/avocado-framework-tests/avocado-misc-tests/files/9009933/cleanup-issue-debug-log.tar.gz)

**Comment by Naresh-ibm** [comment]
[complete-fc-bucket-run-logs.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/9015657/complete-fc-bucket-run-logs.txt)

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Review by PraveenPenguin — APPROVED** [review]

**Pull request merged**
