### PR TITLE
Scsi add remove 4

### PR DESCRIPTION
**Pull request by Naresh-ibm**

### CODE REVIEW

**Comment by Naresh-ibm** [comment]
[scsi_add_remove_job_log_v4.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3434616/scsi_add_remove_job_log_v4.txt)

**Comment by PraveenPenguin** [comment]
@Naresh-ibm please wrap all commit in single commit

**Comment by Naresh-ibm** [comment]
@PraveenPenguin I have closed the older PRs. don't know how why they are showing  again.

**Comment by PraveenPenguin** [comment]
@Naresh-ibm may be you need to rest your working branch  just before `c239c79f893ff1d9fb6ff985dc4912ee70a20e29`  commit and do update with master (upsteam) than add your change , force push your working branch

**Comment by Naresh-ibm** [comment]
closing this in favour of #1233

**Pull request closed without merging**
