### PR TITLE
Enhancing avago9361_vd.py script

### PR DESCRIPTION
**Pull request by vrbagalkote**
Adding PR test case

Signed-off-by: Venkat R B <vrbagal1@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by vrbagalkote** [comment]
Attached is the job.log file
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/680454/job.txt)

**Comment by PraveenPenguin** [comment]
@vrbagalkote can you please explain what this PR test does in commit message ?

**Comment by vrbagalkote** [comment]
Patrol Read(PR), is one of the background operation, which can be run on Raid arrays. It pro-actively, searches for Physical media error.

**Comment by PraveenPenguin** [comment]
@vrbagalkote thanks will add this info while merge as merge commit message

**Pull request merged**
