### PR TITLE
NVMe test fixes

### PR DESCRIPTION
**Pull request by narasimhan-v**
Added verification of written data to nvme read command.
nvme write test uses the above feature to verify write command.

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by apahim** [comment]
please rebase

**Comment by narasimhan-v** [comment]
@PraveenPenguin @apahim The error is from some other previous commit message

**Comment by narasimhan-v** [comment]
@apahim 

I sync'ed my fork before creating this branch, and nothing was merged meanwhile.
Do not understand why the rebase is needed.

**Comment by apahim** [comment]
@narasimhan-v, that's not accurate. According to the history in your branch (https://github.com/narasimhan-v/avocado-misc-tests-1/commits/nvme_cli_test_fix) your commit is on top of the commit `Fixed nvme write command in nvmetest`. That `Fixed nvme write command in nvmetest` is a commit from 22 days ago. Since that point, we had a lot of commits merged. 26 to be exact. You can see master history here: https://github.com/avocado-framework-tests/avocado-misc-tests/commits/master.

**Comment by PraveenPenguin** [comment]
@narasimhan-v  please update your master branch with upstream git and than create new branch and raise pull request it will fix the issue

**Comment by narasimhan-v** [comment]
@apahim @PraveenPenguin Sure, will do.

**Comment by narasimhan-v** [comment]
@apahim Thanks, failed to notice that.

**Pull request closed without merging**
