### PR TITLE
network_stress: support hw addr as input name

### PR DESCRIPTION
**Pull request by abdhaleegit**
Add support for mac addr as input, in case if the
device names are not persistent across os install
the test should still run via unique mac addr in
end to end automated environment

### CODE REVIEW

**Comment by abdhaleegit** [comment]
```
avocado run --max-parallel-tasks=1 network_test.py -m network_test.py.data/network_test_virt_net.yaml 
JOB ID     : db7821c19c18d586c04d03f17ce452bd3796fadc
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2024-01-08T11.13-db7821c/job.log
 (01/24) network_test.py:NetworkTest.test_gro;run-mtu-1500-570c: STARTED
 (01/24) network_test.py:NetworkTest.test_gro;run-mtu-1500-570c: PASS (5.19 s)
 (02/24) network_test.py:NetworkTest.test_gro;run-mtu-9000-b845: STARTED
 (02/24) network_test.py:NetworkTest.test_gro;run-mtu-9000-b845: PASS (10.78 s)
 (03/24) network_test.py:NetworkTest.test_gso;run-mtu-1500-570c: STARTED
 (03/24) network_test.py:NetworkTest.test_gso;run-mtu-1500-570c: PASS (5.14 s)
 (04/24) network_test.py:NetworkTest.test_gso;run-mtu-9000-b845: STARTED
 (04/24) network_test.py:NetworkTest.test_gso;run-mtu-9000-b845: PASS (10.80 s)
 (05/24) network_test.py:NetworkTest.test_lro;run-mtu-1500-570c: STARTED
 (05/24) network_test.py:NetworkTest.test_lro;run-mtu-1500-570c: CANCEL: Unsupported on vNIC (5.08 s)
 (06/24) network_test.py:NetworkTest.test_lro;run-mtu-9000-b845: STARTED
 (06/24) network_test.py:NetworkTest.test_lro;run-mtu-9000-b845: CANCEL: Unsupported on vNIC (10.66 s)
 (07/24) network_test.py:NetworkTest.test_tso;run-mtu-1500-570c: STARTED
 (07/24) network_test.py:NetworkTest.test_tso;run-mtu-1500-570c: PASS (5.22 s)
 (08/24) network_test.py:NetworkTest.test_tso;run-mtu-9000-b845: STARTED
 (08/24) network_test.py:NetworkTest.test_tso;run-mtu-9000-b845: PASS (10.66 s)
 (09/24) network_test.py:NetworkTest.test_ping;run-mtu-1500-570c: STARTED
 (09/24) network_test.py:NetworkTest.test_ping;run-mtu-1500-570c: PASS (14.52 s)
 (10/24) network_test.py:NetworkTest.test_ping;run-mtu-9000-b845: STARTED
 (10/24) network_test.py:NetworkTest.test_ping;run-mtu-9000-b845: PASS (19.98 s)
 (11/24) network_test.py:NetworkTest.test_floodping;run-mtu-1500-570c: STARTED
 (11/24) network_test.py:NetworkTest.test_floodping;run-mtu-1500-570c: PASS (5.13 s)
 (12/24) network_test.py:NetworkTest.test_floodping;run-mtu-9000-b845: STARTED
 (12/24) network_test.py:NetworkTest.test_floodping;run-mtu-9000-b845: PASS (10.73 s)
 (13/24) network_test.py:NetworkTest.test_ipv6_ping;run-mtu-1500-570c: STARTED
 (13/24) network_test.py:NetworkTest.test_ipv6_ping;run-mtu-1500-570c: PASS (14.41 s)
 (14/24) network_test.py:NetworkTest.test_ipv6_ping;run-mtu-9000-b845: STARTED
 (14/24) network_test.py:NetworkTest.test_ipv6_ping;run-mtu-9000-b845: PASS (20.06 s)
 (15/24) network_test.py:NetworkTest.test_ssh;run-mtu-1500-570c: STARTED
 (15/24) network_test.py:NetworkTest.test_ssh;run-mtu-1500-570c: PASS (5.19 s)
 (16/24) network_test.py:NetworkTest.test_ssh;run-mtu-9000-b845: STARTED
 (16/24) network_test.py:NetworkTest.test_ssh;run-mtu-9000-b845: PASS (10.80 s)
 (17/24) network_test.py:NetworkTest.test_scp;run-mtu-1500-570c: STARTED
 (17/24) network_test.py:NetworkTest.test_scp;run-mtu-1500-570c: PASS (16.12 s)
 (18/24) network_test.py:NetworkTest.test_scp;run-mtu-9000-b845: STARTED
 (18/24) network_test.py:NetworkTest.test_scp;run-mtu-9000-b845: PASS (22.18 s)
 (19/24) network_test.py:NetworkTest.test_jumbo_frame;run-mtu-1500-570c: STARTED
 (19/24) network_test.py:NetworkTest.test_jumbo_frame;run-mtu-1500-570c: PASS (8.34 s)
 (20/24) network_test.py:NetworkTest.test_jumbo_frame;run-mtu-9000-b845: STARTED
 (20/24) network_test.py:NetworkTest.test_jumbo_frame;run-mtu-9000-b845: PASS (13.74 s)
 (21/24) network_test.py:NetworkTest.test_statistics;run-mtu-1500-570c: STARTED
 (21/24) network_test.py:NetworkTest.test_statistics;run-mtu-1500-570c: FAIL: Statistics not incremented properly (5.17 s)
 (22/24) network_test.py:NetworkTest.test_statistics;run-mtu-9000-b845: STARTED
 (22/24) network_test.py:NetworkTest.test_statistics;run-mtu-9000-b845: FAIL: Statistics not incremented properly (10.89 s)
 (23/24) network_test.py:NetworkTest.test_promisc;run-mtu-1500-570c: STARTED
 (23/24) network_test.py:NetworkTest.test_promisc;run-mtu-1500-570c: PASS (9.28 s)
 (24/24) network_test.py:NetworkTest.test_promisc;run-mtu-9000-b845: STARTED
 (24/24) network_test.py:NetworkTest.test_promisc;run-mtu-9000-b845: PASS (15.84 s)
RESULTS    : PASS 20 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 2
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2024-01-08T11.13-db7821c/results.html
JOB TIME   : 345.22 s

Test summary:
```

**Comment by abdhaleegit** [comment]
vnic
```
 avocado run --max-parallel-tasks=1 numactl.py -m numactl.py.data/numa_network.yaml 
Fetching asset from numactl.py:Numactl.test_basic
Fetching asset from numactl.py:Numactl.test_interleave
Fetching asset from numactl.py:Numactl.test_localalloc
Fetching asset from numactl.py:Numactl.test_preferred_node
Fetching asset from numactl.py:Numactl.test_cpunode_with_membind
Fetching asset from numactl.py:Numactl.test_physical_cpu_bind
Fetching asset from numactl.py:Numactl.test_numa_pci_bind
JOB ID     : c89d4bf954b12b7ef7908299bc4696f76f6ebce9
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2024-01-08T11.47-c89d4bf/job.log
 (1/7) numactl.py:Numactl.test_basic;run-pci_device-dbe5: STARTED
 (1/7) numactl.py:Numactl.test_basic;run-pci_device-dbe5: WARN: Test passed but there were warnings during execution. Check the log for details. (13.54 s)
 (2/7) numactl.py:Numactl.test_interleave;run-pci_device-dbe5: STARTED
 (2/7) numactl.py:Numactl.test_interleave;run-pci_device-dbe5: PASS (21.86 s)
 (3/7) numactl.py:Numactl.test_localalloc;run-pci_device-dbe5: STARTED
 (3/7) numactl.py:Numactl.test_localalloc;run-pci_device-dbe5: PASS (21.66 s)
 (4/7) numactl.py:Numactl.test_preferred_node;run-pci_device-dbe5: STARTED
 (4/7) numactl.py:Numactl.test_preferred_node;run-pci_device-dbe5: CANCEL: Device input missing, skipping the test (11.40 s)
 (5/7) numactl.py:Numactl.test_cpunode_with_membind;run-pci_device-dbe5: STARTED
 (5/7) numactl.py:Numactl.test_cpunode_with_membind;run-pci_device-dbe5: CANCEL: Device input missing, skipping the test (11.26 s)
 (6/7) numactl.py:Numactl.test_physical_cpu_bind;run-pci_device-dbe5: STARTED
 (6/7) numactl.py:Numactl.test_physical_cpu_bind;run-pci_device-dbe5: CANCEL: Device input missing, skipping the test (11.23 s)
 (7/7) numactl.py:Numactl.test_numa_pci_bind;run-pci_device-dbe5: STARTED
 (7/7) numactl.py:Numactl.test_numa_pci_bind;run-pci_device-dbe5: CANCEL: Device input missing, skipping the test (11.39 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 1 | INTERRUPT 0 | CANCEL 4
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2024-01-08T11.47-c89d4bf/results.html
JOB TIME   : 189.39 s
```

**Comment by abdhaleegit** [comment]
irqbalance  macid
```
avocado run --max-parallel-tasks=1 irqbalance.py -m irqbalance.py.data/irqbalance_network.yaml 
JOB ID     : e5c4dd98e48a58dbd906173ba3dbdf51fe3ba240
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2024-01-08T12.30-e5c4dd9/job.log
 (1/4) irqbalance.py:irq_balance.test_irq_balance;run-5b0d: STARTED
 (1/4) irqbalance.py:irq_balance.test_irq_balance;run-5b0d: ERROR: list index out of range (4.28 s)
 (2/4) irqbalance.py:irq_balance.test_cpu_serial_off_on;run-5b0d: STARTED
 (2/4) irqbalance.py:irq_balance.test_cpu_serial_off_on;run-5b0d: PASS (8.46 s)
 (3/4) irqbalance.py:irq_balance.test_smt_toggle;run-5b0d: STARTED
 (3/4) irqbalance.py:irq_balance.test_smt_toggle;run-5b0d: PASS (9.00 s)
 (4/4) irqbalance.py:irq_balance.test_taskset;run-5b0d: STARTED
 (4/4) irqbalance.py:irq_balance.test_taskset;run-5b0d: PASS (5.10 s)
RESULTS    : PASS 3 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2024-01-08T12.30-e5c4dd9/results.html
JOB TIME   : 62.70 s
```

**Comment by Naresh-ibm** [comment]
@abdhaleegit can you please also add the run logs for disk as the test cases are for both disk and network.
just to rule out we don't have any breakage for disk runs

**Comment by PraveenPenguin** [comment]
@abdhaleegit i feel this is the next version  PR to the old PR,  it always good to tag old PR/discussion to help reviewer

**Comment by abdhaleegit** [comment]
```
avocado run --max-parallel-tasks=1 numactl.py -m numactl.py.data/numa_fc.yaml 
Fetching asset from numactl.py:Numactl.test_basic
Fetching asset from numactl.py:Numactl.test_interleave
Fetching asset from numactl.py:Numactl.test_localalloc
Fetching asset from numactl.py:Numactl.test_preferred_node
Fetching asset from numactl.py:Numactl.test_cpunode_with_membind
Fetching asset from numactl.py:Numactl.test_physical_cpu_bind
Fetching asset from numactl.py:Numactl.test_numa_pci_bind
JOB ID     : 6ae1345f280e71f719f644bf5f94c20d6a360361
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2024-02-19T20.11-6ae1345/job.log
 (1/7) numactl.py:Numactl.test_basic;run-bytes-count-input_file-seek-64bc: STARTED
 (1/7) numactl.py:Numactl.test_basic;run-bytes-count-input_file-seek-64bc: WARN: Test passed but there were warnings during execution. Check the log for details. (16.14 s)
 (2/7) numactl.py:Numactl.test_interleave;run-bytes-count-input_file-seek-64bc: STARTED
 (2/7) numactl.py:Numactl.test_interleave;run-bytes-count-input_file-seek-64bc: PASS (14.11 s)
 (3/7) numactl.py:Numactl.test_localalloc;run-bytes-count-input_file-seek-64bc: STARTED
 (3/7) numactl.py:Numactl.test_localalloc;run-bytes-count-input_file-seek-64bc: PASS (14.27 s)
 (4/7) numactl.py:Numactl.test_preferred_node;run-bytes-count-input_file-seek-64bc: STARTED
 (4/7) numactl.py:Numactl.test_preferred_node;run-bytes-count-input_file-seek-64bc: CANCEL: Required atleast two NUMA nodes with CPU assigned for this test case! (11.55 s)
 (5/7) numactl.py:Numactl.test_cpunode_with_membind;run-bytes-count-input_file-seek-64bc: STARTED
 (5/7) numactl.py:Numactl.test_cpunode_with_membind;run-bytes-count-input_file-seek-64bc: CANCEL: Required atleast two NUMA nodes with CPU assigned for this test case! (11.62 s)
 (6/7) numactl.py:Numactl.test_physical_cpu_bind;run-bytes-count-input_file-seek-64bc: STARTED
 (6/7) numactl.py:Numactl.test_physical_cpu_bind;run-bytes-count-input_file-seek-64bc: CANCEL: Required atleast two NUMA nodes with CPU assigned for this test case! (11.42 s)
 (7/7) numactl.py:Numactl.test_numa_pci_bind;run-bytes-count-input_file-seek-64bc: STARTED
 (7/7) numactl.py:Numactl.test_numa_pci_bind;run-bytes-count-input_file-seek-64bc: CANCEL: Required atleast two NUMA nodes with CPU assigned for this test case! (11.43 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 1 | INTERRUPT 0 | CANCEL 4
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2024-02-19T20.11-6ae1345/results.html
JOB TIME   : 116.84 s
```
cat numactl.py.data/numa_fc.yaml
disk: "/dev/mapper/mpathj"
seek:
count:
bytes:
input_file:
pci_device: "0000:01:00.0"
```
 avocado run --max-parallel-tasks=1 numactl.py -m numactl.py.data/numa_network.yaml 
Fetching asset from numactl.py:Numactl.test_basic
Fetching asset from numactl.py:Numactl.test_interleave
Fetching asset from numactl.py:Numactl.test_localalloc
Fetching asset from numactl.py:Numactl.test_preferred_node
Fetching asset from numactl.py:Numactl.test_cpunode_with_membind
Fetching asset from numactl.py:Numactl.test_physical_cpu_bind
Fetching asset from numactl.py:Numactl.test_numa_pci_bind
JOB ID     : 5d4dde2d76c1038f3d26e976a08a75a8e3245afd
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2024-02-19T20.27-5d4dde2/job.log
 (1/7) numactl.py:Numactl.test_basic;run-b8bc: STARTED
 (1/7) numactl.py:Numactl.test_basic;run-b8bc: WARN: Test passed but there were warnings during execution. Check the log for details. (20.48 s)
 (2/7) numactl.py:Numactl.test_interleave;run-b8bc: STARTED
 (2/7) numactl.py:Numactl.test_interleave;run-b8bc: PASS (15.85 s)
 (3/7) numactl.py:Numactl.test_localalloc;run-b8bc: STARTED
 (3/7) numactl.py:Numactl.test_localalloc;run-b8bc: PASS (15.76 s)
 (4/7) numactl.py:Numactl.test_preferred_node;run-b8bc: STARTED
 (4/7) numactl.py:Numactl.test_preferred_node;run-b8bc: CANCEL: Required atleast two NUMA nodes with CPU assigned for this test case! (15.64 s)
 (5/7) numactl.py:Numactl.test_cpunode_with_membind;run-b8bc: STARTED
 (5/7) numactl.py:Numactl.test_cpunode_with_membind;run-b8bc: CANCEL: Required atleast two NUMA nodes with CPU assigned for this test case! (15.73 s)
 (6/7) numactl.py:Numactl.test_physical_cpu_bind;run-b8bc: STARTED
 (6/7) numactl.py:Numactl.test_physical_cpu_bind;run-b8bc: CANCEL: Required atleast two NUMA nodes with CPU assigned for this test case! (15.65 s)
 (7/7) numactl.py:Numactl.test_numa_pci_bind;run-b8bc: STARTED
 (7/7) numactl.py:Numactl.test_numa_pci_bind;run-b8bc: CANCEL: Required atleast two NUMA nodes with CPU assigned for this test case! (15.71 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 1 | INTERRUPT 0 | CANCEL 4
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2024-02-19T20.27-5d4dde2/results.html
JOB TIME   : 160.73 s
```
cat numactl.py.data/numa_network.yaml
interface: enP16392p1s0
host_ip: 147.1.194.23   
netmask: 255.255.255.0
peer_ip: 147.1.194.252
pci_device: "4008:01:00.0"
ping_count: 500


cat irqbalance.py.data/irqbalance_disk.yaml
disk: "/dev/nvme1n1"
```
 avocado run --max-parallel-tasks=1 irqbalance.py -m irqbalance.py.data/irqbalance_disk.yaml 
JOB ID     : 8c915b50b0ea539b6a32db5a870c2ed31000cf28
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2024-02-20T00.23-8c915b5/job.log
 (1/4) irqbalance.py:irq_balance.test_irq_balance;run-dc11: STARTED
 (1/4) irqbalance.py:irq_balance.test_irq_balance;run-dc11: FAIL: Assigning CPU to IRQ failed, Please check logs (0.08 s)
 (2/4) irqbalance.py:irq_balance.test_cpu_serial_off_on;run-dc11: STARTED
 (2/4) irqbalance.py:irq_balance.test_cpu_serial_off_on;run-dc11: PASS (38.69 s)
 (3/4) irqbalance.py:irq_balance.test_smt_toggle;run-dc11: STARTED
 (3/4) irqbalance.py:irq_balance.test_smt_toggle;run-dc11: PASS (50.03 s)
 (4/4) irqbalance.py:irq_balance.test_taskset;run-dc11: STARTED
 (4/4) irqbalance.py:irq_balance.test_taskset;run-dc11: PASS (179.78 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2024-02-20T00.23-8c915b5/results.html
JOB TIME   : 310.69 s

Test summary:
1-irqbalance.py:irq_balance.test_irq_balance;run-dc11: FAIL
```
```
 avocado run --max-parallel-tasks=1 irqbalance.py -m irqbalance.py.data/irqbalance_network.yaml 
JOB ID     : 410e0de1ead476d660c1bbc2c4da33cfc3a2d3ad
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2024-02-20T00.29-410e0de/job.log
 (1/4) irqbalance.py:irq_balance.test_irq_balance;run-4191: STARTED
 (1/4) irqbalance.py:irq_balance.test_irq_balance;run-4191: ERROR: list index out of range (4.41 s)
 (2/4) irqbalance.py:irq_balance.test_cpu_serial_off_on;run-4191: STARTED
 (2/4) irqbalance.py:irq_balance.test_cpu_serial_off_on;run-4191: PASS (37.46 s)
 (3/4) irqbalance.py:irq_balance.test_smt_toggle;run-4191: STARTED
 (3/4) irqbalance.py:irq_balance.test_smt_toggle;run-4191: PASS (44.70 s)
 (4/4) irqbalance.py:irq_balance.test_taskset;run-4191: STARTED
 (4/4) irqbalance.py:irq_balance.test_taskset;run-4191: FAIL: taskset command failed check logs (4.53 s)
RESULTS    : PASS 2 | ERROR 1 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2024-02-20T00.29-410e0de/results.html
JOB TIME   : 118.83 s

Test summary:
1-irqbalance.py:irq_balance.test_irq_balance;run-4191: ERROR
4-irqbalance.py:irq_balance.test_taskset;run-4191: FAIL
```

**Comment by abdhaleegit** [comment]
@Naresh-ibm please review, CR test are failing due to this PR

**Comment by Naresh-ibm** [comment]
@abdhaleegit I have some queries on n/w part. will discuss offline and merge this.

**Comment by Naresh-ibm** [comment]
Got clarified from @abdhaleegit .

**Review by Naresh-ibm — APPROVED** [review]
@abdhaleegit Thanks for the PR
LGTM

**Pull request merged**
