### PR TITLE
changed scp with passwordless scp to avoid ssh-keygen

### PR DESCRIPTION
**Pull request by smruti77**
chnaged passwordless scp in iperf, netperf and uperf

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
JOB ID     : 78f01f1221214d30743db907a9c1ed3e88a34de3
JOB LOG    : /root/avocado/job-results/job-2020-07-02T00.23-78f01f1/job.log
 (1/1) iperf_test.py:Iperf.test;1500-07a4: PASS (97.23 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-07-02T00.23-78f01f1/results.html
JOB TIME   : 97.29 s

JOB ID     : 35271a73b9510828d36fdd0d82f9869b6479ef50
JOB LOG    : /root/avocado/job-results/job-2020-07-02T00.25-35271a7/job.log
 (1/1) uperf_test.py:Uperf.test;1500-5504: PASS (124.19 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-07-02T00.25-35271a7/results.html
JOB TIME   : 124.26 s


JOB ID     : fcf0c2743d31b7c690d695c22f1e6b12d9903961
JOB LOG    : /root/avocado/job-results/job-2020-07-02T00.30-fcf0c27/job.log
 (1/1) netperf_test.py:Netperf.test;1500-generic-71a7: WARN: Test passed but there were warnings during execution. Check the log for details. (692.95 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 1 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-07-02T00.30-fcf0c27/results.html
JOB TIME   : 693.02 s

**Comment by smruti77** [comment]
@narasimhan-v in network_test, ssh_test also need handle, i thought to talk about this.

**Comment by narasimhan-v** [comment]
> @narasimhan-v in network_test, ssh_test also need handle, i thought to talk about this.

Sure, handle for both

**Comment by smruti77** [comment]
JOB ID     : 8b4e4bc3e51fb71d1b40ed18767725bd3c68a772
JOB LOG    : /root/avocado/job-results/job-2020-07-02T03.53-8b4e4bc/job.log
 (01/10) network_test.py:NetworkTest.test_gro;1500-ce1b: PASS (143.11 s)
 (02/10) network_test.py:NetworkTest.test_gso;1500-ce1b: PASS (143.81 s)
 (03/10) network_test.py:NetworkTest.test_lro;1500-ce1b: CANCEL: Unsupported on vNIC (67.45 s)
 (04/10) network_test.py:NetworkTest.test_tso;1500-ce1b: PASS (142.95 s)
 (05/10) network_test.py:NetworkTest.test_ping;1500-ce1b: PASS (76.77 s)
 (06/10) network_test.py:NetworkTest.test_floodping;1500-ce1b: PASS (105.16 s)
 (07/10) network_test.py:NetworkTest.test_ssh;1500-ce1b: PASS (67.46 s)
 (08/10) network_test.py:NetworkTest.test_scp;1500-ce1b: PASS (83.47 s)
 (09/10) network_test.py:NetworkTest.test_jumbo_frame;1500-ce1b: PASS (70.63 s)
 (10/10) network_test.py:NetworkTest.test_promisc;1500-ce1b: PASS (78.22 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /root/avocado/job-results/job-2020-07-02T03.53-8b4e4bc/results.html
JOB TIME   : 979.39 s

**Comment by abdhaleegit** [comment]
@smruti77 just handle it for ./io/nvmf/nvmftest.py  too ,  rest all LGTM

**Comment by narasimhan-v** [comment]
@abdhaleegit Since we are not having nvmf environment, and we run it not so frequently, I have created an issue to handle it later.

https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1800

**Pull request merged**
