### PR TITLE
Adding test to nvme-cli test

### PR DESCRIPTION
**Pull request by narasimhan-v**
Added the following tests to nvme-cli test.
*) compare
*) flush
*) writezeroes
*) writeuncorrectable
*) dsm
*) reset
*) subsystemreset

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
[job_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/505918/job_log.txt)

**Comment by narasimhan-v** [comment]
@PraveenPenguin Agreed, and I have done the same for create namespace, format namespace, etc.
But, the person who is running the test needs to know what all tests are run.

Can you suggest a better way to do that, please ?

**Comment by PraveenPenguin** [comment]
@narasimhan-v yes i saw that , can we pass a string in self.log.info("test run <test>") used in  pass as well in fail case ? 
couple of   request 
1-can  can you move `testread` and `testwrite` also  in helper function  and use it from test function  
2- use expire  flag 
for that we need to use fetch_asset and link can be 
`https://github.com/linux-nvme/nvme-cli/archive/master.zip `

code snippet can be :

```
        locations = ["https://github.com/linux-nvme/nvme-cli/archive/"
                     "master.zip"]
        tarball = self.fetch_asset("nvme-cli.zip", locations=locations,
                                   expire='10d') 
        self.srcdir = os.path.join(self.srcdir, 'nvme-cli-master')
```

**Comment by PraveenPenguin** [comment]
suggesting  using fetch asset  as It can be cached and downloads only the snapshot, not the whole history...

**Comment by narasimhan-v** [comment]
@PraveenPenguin Created new PR #115

**Pull request closed without merging**
