### PR TITLE
Adding Multipath test [v2]

### PR DESCRIPTION
**Pull request by narasimhan-v**
Tests Flushing, Blacklisting, patch_checker policy.

Signed-off-by: Narasimhan V sim@linux.vnet.ibm.com

### CODE REVIEW

**Comment by narasimhan-v** [comment]
[job_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/544375/job_log.txt)

**Comment by narasimhan-v** [comment]
Depends on https://github.com/avocado-framework/avocado/pull/1559

**Comment by PraveenPenguin** [comment]
looks good will wait  for avocado-framework/avocado#1559

**Comment by narasimhan-v** [comment]
@PraveenPenguin with https://github.com/avocado-framework/avocado/pull/1650 merged, I think you can review/merge this test.

**Comment by narasimhan-v** [comment]
@PraveenPenguin thanks

**Pull request merged**
