### PR TITLE
Nvdimm test update

### PR DESCRIPTION
**Pull request by kvaneesh**

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@harish-24 review Please

**Comment by harish-24** [comment]
Included all these as part of https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1522. @kvaneesh Do you want to pursue this or should I pull back those commits?

**Comment by kvaneesh** [comment]
> Included all these as part of #1522. @kvaneesh Do you want to pursue this or should I pull back those commits?

I did end up updating the legacy namespace test. So this pull request contains the latest test. I would suggest we pull this request and can you update 1522 on top of this?

**Comment by harish-24** [comment]
Makes sense.

**Comment by PraveenPenguin** [comment]
@kvaneesh thanks for Patch

**Pull request merged**
