### PR TITLE
htx_block_devices.py added LV and Software raid

### PR DESCRIPTION
**Pull request by smruti77**
Test creates LV,software raid and runs htx test on them, as an option.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by smruti77** [comment]
JOB ID     : 5daf62a641e253af64684fc8f37911b4d16afe44
JOB LOG    : /root/avocado/job-results/job-2020-07-30T06.26-5daf62a/job.log
 (01/12) htx_block_devices.py:HtxTest.test_start;run-lv-lv-raid-raid-e8c8: FAIL: Block devices failed to activate (158.45 s)
 (02/12) htx_block_devices.py:HtxTest.test_check;run-lv-lv-raid-raid-e8c8: PASS (60.05 s)
 (03/12) htx_block_devices.py:HtxTest.test_stop;run-lv-lv-raid-raid-e8c8: PASS (6.38 s)
 (04/12) htx_block_devices.py:HtxTest.test_start;run-lv-lv-raid-no_raid-834f: FAIL: Block devices failed to activate (157.52 s)
 (05/12) htx_block_devices.py:HtxTest.test_check;run-lv-lv-raid-no_raid-834f: PASS (60.03 s)
 (06/12) htx_block_devices.py:HtxTest.test_stop;run-lv-lv-raid-no_raid-834f: PASS (6.26 s)
 (07/12) htx_block_devices.py:HtxTest.test_start;run-lv-no_lv-raid-raid-e81a: FAIL: Block devices failed to activate (151.63 s)
 (08/12) htx_block_devices.py:HtxTest.test_check;run-lv-no_lv-raid-raid-e81a: PASS (60.05 s)
 (09/12) htx_block_devices.py:HtxTest.test_stop;run-lv-no_lv-raid-raid-e81a: PASS (5.35 s)
 (10/12) htx_block_devices.py:HtxTest.test_start;run-lv-no_lv-raid-no_raid-57a9: FAIL: Block devices failed to activate (151.35 s)
 (11/12) htx_block_devices.py:HtxTest.test_check;run-lv-no_lv-raid-no_raid-57a9: PASS (60.08 s)
 (12/12) htx_block_devices.py:HtxTest.test_stop;run-lv-no_lv-raid-no_raid-57a9: PASS (5.16 s)
RESULTS    : PASS 8 | ERROR 0 | FAIL 4 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-07-30T06.26-5daf62a/results.html
JOB TIME   : 882.55 s

**Comment by smruti77** [comment]
JOB ID     : b942622b5712e55e75ead1979eace37757ac9cc8
JOB LOG    : /root/sim/tests/results/job-2020-08-17T07.32-b942622/job.log
 (01/12) htx_block_devices.py:HtxTest.test_start;run-lv-lv-raid-raid-48fe: PASS (173.44 s)
 (02/12) htx_block_devices.py:HtxTest.test_check;run-lv-lv-raid-raid-48fe: PASS (60.94 s)
 (03/12) htx_block_devices.py:HtxTest.test_stop;run-lv-lv-raid-raid-48fe: PASS (15.93 s)
 (04/12) htx_block_devices.py:HtxTest.test_start;run-lv-lv-raid-no_raid-6847: PASS (173.31 s)
 (05/12) htx_block_devices.py:HtxTest.test_check;run-lv-lv-raid-no_raid-6847: PASS (60.92 s)
 (06/12) htx_block_devices.py:HtxTest.test_stop;run-lv-lv-raid-no_raid-6847: PASS (15.87 s)
 (07/12) htx_block_devices.py:HtxTest.test_start;run-lv-no_lv-raid-raid-474d: PASS (173.39 s)
 (08/12) htx_block_devices.py:HtxTest.test_check;run-lv-no_lv-raid-raid-474d: PASS (60.94 s)
 (09/12) htx_block_devices.py:HtxTest.test_stop;run-lv-no_lv-raid-raid-474d: PASS (15.89 s)
 (10/12) htx_block_devices.py:HtxTest.test_start;run-lv-no_lv-raid-no_raid-e58d: PASS (173.34 s)
 (11/12) htx_block_devices.py:HtxTest.test_check;run-lv-no_lv-raid-no_raid-e58d: PASS (60.94 s)
 (12/12) htx_block_devices.py:HtxTest.test_stop;run-lv-no_lv-raid-no_raid-e58d: PASS (15.85 s)
RESULTS    : PASS 12 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/sim/tests/results/job-2020-08-17T07.32-b942622/results.html
JOB TIME   : 1001.87 s

**Comment by smruti77** [comment]
[htx_block.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5084057/htx_block.log)

**Comment by narasimhan-v** [comment]
@smruti77 I do not find any mdadm or lvcreate command in the log, which means they are not created at all. Can you please check that ?

**Comment by smruti77** [comment]
> @smruti77 I do not find any mdadm or lvcreate command in the log, which means they are not created at all. Can you please check that ?

ok, i will check

**Comment by smruti77** [comment]
getting same error,
JOB ID     : f63a93bfc9856ded4047e5b1fcd87dbb296aba36
JOB LOG    : /root/sim/tests/results/job-2020-08-18T00.29-f63a93b/job.log
 (01/12) htx_block_devices.py:HtxTest.test_start;run-lv-lv-raid-raid-48fe: FAIL: Block devices failed to activate (330.28 s)
 (02/12) htx_block_devices.py:HtxTest.test_check;run-lv-lv-raid-raid-48fe: PASS (60.75 s)
 (03/12) htx_block_devices.py:HtxTest.test_stop;run-lv-lv-raid-raid-48fe: PASS (7.11 s)
 (04/12) htx_block_devices.py:HtxTest.test_start;run-lv-lv-raid-no_raid-6847: FAIL: Block devices failed to activate (328.61 s)
 (05/12) htx_block_devices.py:HtxTest.test_check;run-lv-lv-raid-no_raid-6847: PASS (60.78 s)
 (06/12) htx_block_devices.py:HtxTest.test_stop;run-lv-lv-raid-no_raid-6847: PASS (6.98 s)
 (07/12) htx_block_devices.py:HtxTest.test_start;run-lv-no_lv-raid-raid-474d: FAIL: Block devices failed to activate (323.58 s)
 (08/12) htx_block_devices.py:HtxTest.test_check;run-lv-no_lv-raid-raid-474d: PASS (60.84 s)
 (09/12) htx_block_devices.py:HtxTest.test_stop;run-lv-no_lv-raid-raid-474d: PASS (6.11 s)
 (10/12) htx_block_devices.py:HtxTest.test_start;run-lv-no_lv-raid-no_raid-e58d: FAIL: Block devices failed to activate (322.09 s)
 (11/12) htx_block_devices.py:HtxTest.test_check;run-lv-no_lv-raid-no_raid-e58d: PASS (60.84 s)
 (12/12) htx_block_devices.py:HtxTest.test_stop;run-lv-no_lv-raid-no_raid-e58d: PASS (5.92 s)
RESULTS    : PASS 8 | ERROR 0 | FAIL 4 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/sim/tests/results/job-2020-08-18T00.29-f63a93b/results.html
JOB TIME   : 1575.01 s

**Comment by PraveenPenguin** [comment]
@narasimhan-v can you please help here , are we still perusing  this PR

**Comment by narasimhan-v** [comment]
> @narasimhan-v can you please help here , are we still perusing  this PR 

This still needs changes to work for HTX. So  ot actively pursuing this

**Comment by PraveenPenguin** [comment]
@abdhaleegit @Naresh-ibm closing this as PR as not moving and  it has  merge conflict, may we can plan as a fresh one

**Pull request closed without merging**
