### PR TITLE
Patch to enhance multiport stress by adding flood ping

### PR DESCRIPTION
**Pull request by hathyaga**
This patch has a new flood ping function added that will
run the flood ping command for the test interfaces

Signed-off-by: Harsha Thyagaraja <harshkid@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@hathyaga please reabse with having one more blank line after this 
`https://github.com/hathyaga/avocado-misc-tests-1/blob/347dbb4c8cba8866bf436e054783a95c1b3ae521/io/net/multiport_stress.py#L104`

**Comment by PraveenPenguin** [comment]
@hathyaga any update ?

**Comment by narasimhan-v** [comment]
```
The command "inspekt indent" exited with 0.

3.19s$ inspekt style

PEP8 disabled: E501,E265,W601,E402

/home/travis/build/avocado-framework-tests/avocado-misc-tests/io/net/multiport_stress.py:105:1: E305 expected 2 blank lines after class or function definition, found 1

Style check fail: /home/travis/build/avocado-framework-tests/avocado-misc-tests/io/net/multiport_stress.py

PEP8 compliance FAIL

The command "inspekt style" exited with 1.
```

**Comment by hathyaga** [comment]
New PR: https://github.com/avocado-framework-tests/avocado-misc-tests/pull/599

Closing this

**Pull request closed without merging**
