### PR TITLE
ltp-net.yaml : Adding Network related testcases from LTP.

### PR DESCRIPTION
**Pull request by naveen538**
Signed-off-by: Naveen kumar T <naveet89@in.ibm.com>

### CODE REVIEW

**Comment by naveen538** [comment]
Job log:
---------
nohup python avocado-setup.py --run-suite host_distro_stress &
JOB ID     : 4e52c60ef74506cfb4d4a3ce38c82553bd77eea5
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-07-03T05.59-4e52c60/job.log
/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/plugins/run.py:285: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  FutureWarning)
 (01/10) ltp.py:LTP.test;net.features-ea4d:  FAIL: LTP tests failed: ['mpls03'] (283.31 s)
 (02/10) ltp.py:LTP.test;net.ipv6-a9c4:  FAIL: LTP tests failed: ['tracepath601', 'dnsmasq6'] (183.69 s)
 (03/10) ltp.py:LTP.test;net.ipv6_lib-249a:  FAIL: LTP tests failed: ['getaddrinfo_01'] (176.57 s)
 (04/10) ltp.py:LTP.test;net.nfs-e728:  PASS (195.62 s)
 (05/10) ltp.py:LTP.test;net.tcp_cmds-72a1:  FAIL: LTP tests failed: ['ftp', 'rcp', 'rsh', 'dnsmasq'] (181.82 s)
 (06/10) ltp.py:LTP.test;net.sctp-e880:  FAIL: LTP tests failed: ['test_1_to_1_accept_close', 'test_1_to_1_addrs', 'test_1_to_1_connect', 'test_1_to_1_connectx', 'test_1_to_1_events', 'test_1_to_1_nonblock', 'test_1_to_1_recvfrom', 'test_1_to_1_recvmsg', 'test_1_to_1_rtoinfo', 'test_1_to_1_send', 'tes... (173.58 s)
 (07/10) ltp.py:LTP.test;net.multicast-afa1:  FAIL: LTP tests failed: ['mc_commo'] (875.46 s)
 (08/10) ltp.py:LTP.test;net.rpc-2d41:  FAIL: LTP tests failed: ['rpc01', 'rpcinfo', 'rup', 'rusers'] (158.49 s)
 (09/10) ltp.py:LTP.test;net.rpc_tests-34d3:  FAIL: LTP tests failed: ['rpc_pmap_set', 'rpc_pmap_unset', 'rpc_pmap_getport', 'rpc_pmap_getmaps', 'rpc_pmap_rmtcall', 'rpc_get_myaddress', 'rpc_authnone_create', 'rpc_authunix_create', 'rpc_authunix_create_default', 'rpc_auth_destroy', 'rpc_clnt_broadcast', 'r... (177.56 s)
 (10/10) ltp.py:LTP.test;net.tirpc_tests-1cfb:  FAIL: LTP tests failed: ['tirpc_rpcb_getaddr', 'tirpc_rpcb_getmaps', 'tirpc_authnone_create', 'tirpc_authsys_create', 'tirpc_authsys_create_default', 'tirpc_clnt_dg_create', 'tirpc_svc_dg_create', 'tirpc_clnt_vc_create', 'tirpc_svc_vc_create', 'tirpc_bottomleve... (161.77 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 9 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-07-03T05.59-4e52c60/results.html
JOB TIME   : 2571.82 s

**Comment by naveen538** [comment]
As of now adding testcases and rcp related failure's are still need to be debugged.

**Comment by harish-24** [comment]
@naveen538 Can you paste the variants json dump of the updated yaml or result with the run of complete yaml?

**Comment by naveen538** [comment]
@harish-24 Modified the PR created separate ltp-net.yaml for network related tests.

**Comment by naveen538** [comment]
avocado run ltp.py -m ltp.py.data/ltp-net.yaml
JOB ID     : ce80a71f3dfc5d34f3bed80492d3cbd646302b88
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-07-07T11.37-ce80a71/job.log
/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/plugins/run.py:285: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  FutureWarning)
 (01/10) ltp.py:LTP.test;net.features-ea4d:  FAIL: LTP tests failed: ['mpls03'] (292.10 s)
 (02/10) ltp.py:LTP.test;net.ipv6-a9c4:  FAIL: LTP tests failed: ['tracepath601', 'dnsmasq6'] (192.86 s)
 (03/10) ltp.py:LTP.test;net.ipv6_lib-249a:  FAIL: LTP tests failed: ['getaddrinfo_01'] (182.33 s)
 (04/10) ltp.py:LTP.test;net.nfs-e728:  PASS (199.32 s)
 (05/10) ltp.py:LTP.test;net.tcp_cmds-72a1:  FAIL: LTP tests failed: ['ftp', 'rcp', 'rsh', 'dnsmasq'] (195.40 s)
 (06/10) ltp.py:LTP.test;net.sctp-e880:  FAIL: LTP tests failed: ['test_1_to_1_accept_close', 'test_1_to_1_addrs', 'test_1_to_1_connect', 'test_1_to_1_connectx', 'test_1_to_1_events', 'test_1_to_1_nonblock', 'test_1_to_1_recvfrom', 'test_1_to_1_recvmsg', 'test_1_to_1_rtoinfo', 'test_1_to_1_send', 'tes... (180.11 s)
 (07/10) ltp.py:LTP.test;net.multicast-afa1:  FAIL: LTP tests failed: ['mc_commo'] (877.75 s)
 (08/10) ltp.py:LTP.test;net.rpc-2d41:  PASS (182.73 s)
 (09/10) ltp.py:LTP.test;net.rpc_tests-34d3:  PASS (195.06 s)
 (10/10) ltp.py:LTP.test;net.tirpc_tests-1cfb:  PASS (194.13 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 6 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-07-07T11.37-ce80a71/results.html
JOB TIME   : 2695.78 s

**Pull request merged**
