### PR TITLE
memhotplug.py:Added new URL

### PR DESCRIPTION
**Pull request by shirishaganta**
Previous URL is not working
 https://people.seas.harvard.edu/~apw/stress/stress-1.0.4.tar.gz

Signed-off-by: Shirisha Ganta <shiganta@in.ibm.com>

### CODE REVIEW

**Comment by shirishaganta** [comment]
Before Patch On SLES12SP5beta2

JOB ID     : 4d16c0b7b846cdc9d96d4faeea6bd70f93825c71
JOB LOG    : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-07-30T13.12-4d16c0b/job.log
 (1/4) avocado-misc-tests/memory/memhotplug.py:MemStress.test_hotplug_loop:  ERROR: Failed to fetch stress-1.0.4.tar.gz. (1.33 s)
 (2/4) avocado-misc-tests/memory/memhotplug.py:MemStress.test_hotplug_toggle:  ERROR: Failed to fetch stress-1.0.4.tar.gz. (1.01 s)
 (3/4) avocado-misc-tests/memory/memhotplug.py:MemStress.test_dlpar_mem_hotplug:  ERROR: Failed to fetch stress-1.0.4.tar.gz. (1.00 s)
 (4/4) avocado-misc-tests/memory/memhotplug.py:MemStress.test_hotplug_per_numa_node:  ERROR: Failed to fetch stress-1.0.4.tar.gz. (0.95 s)
RESULTS    : PASS 0 | ERROR 4 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

AFTER Patch 

JOB ID     : 57bacebdd4db73979c405327eed8a635aefebab8
JOB LOG    : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-07-30T13.39-57baceb/job.log
 (1/4) memhotplug.py:MemStress.test_hotplug_loop: PASS (833.87 s)
 (2/4) memhotplug.py:MemStress.test_hotplug_toggle: PASS (413.69 s)
 (3/4) memhotplug.py:MemStress.test_dlpar_mem_hotplug: PASS (23.40 s)
 (4/4) memhotplug.py:MemStress.test_hotplug_per_numa_node: PASS (353.97 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1662.03 s
JOB HTML   : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-07-30T13.39-57baceb/results.html

**Comment by harish-24** [comment]
We can wait for some more time (1 day or so ) and check if old URL has stayed removed. Otherwise patch is good.

**Comment by shirishaganta** [comment]
okay

**Comment by PraveenPenguin** [comment]
@shirishaganta please send this PR against py2-lts branch  as well

**Comment by PraveenPenguin** [comment]
@harish-24 thanks for ACK , merging

**Pull request merged**
