### PR TITLE
network_stress: re-arange mtu settings serially

### PR DESCRIPTION
**Pull request by abdhaleegit**
for every test the script is setting mtu to 1500 for peer and host
interface at start of the test and also resetting mtu for peer and host
this patch make sure the mtu reset happens serially i.e

test start : set mtu in host and set mtu in peer
test end   : reset mtu in of peer first and than set back host

Signed-off-by: Abdul Haleem <abdhalee@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@manvanthar @vaishnavibhat @smruti77 reviews please

**Comment by narasimhan-v** [comment]
@abdhaleegit can you please rebase / resolve conflict

**Comment by abdhaleegit** [comment]
rebase done

**Comment by PraveenPenguin** [comment]
@abdhaleegit please resolve travis  issue

**Comment by smruti77** [comment]
@abdhaleegit same thing their in new code changes.

**Comment by abdhaleegit** [comment]
@smruti77 got it .. I need to update the module.. will do that and push

**Comment by abdhaleegit** [comment]
I think wi this PR https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1588 the same code is coverd. I am closing this

**Pull request closed without merging**
