### PR TITLE
Adding Test for Module unload/load

### PR DESCRIPTION
**Pull request by hathyaga**
This Program loads and unloads the kernel driver modules listed in lspci along with the dependant modules for a total of 100 counts as a stress test.

### CODE REVIEW

**Comment by hathyaga** [comment]
@idoktor new PR for module unload/load test

**Comment by PraveenPenguin** [comment]
@hathyaga  need one help facing some issue while running this TEST 
```

[stderr] rmmod: ERROR: Module ohci_pci is builtin.
[stderr] rmmod: ERROR: Module virtio_pci is builtin.
Exit status: 1
Duration: 2.87228107452

Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado-38.0-py2.7.egg/avocado/core/test.py:448
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/avocado-38.0-py2.7.egg/avocado/core/test.py", line 700, in test
    self.execute_cmd()
  File "/usr/local/lib/python2.7/dist-packages/avocado-38.0-py2.7.egg/avocado/core/test.py", line 694, in execute_cmd
    raise exceptions.TestFail(details)
TestFail: Command '/root/module_unload_load.sh' failed (rc=1)

FAIL 1-module_unload_load.sh -> TestFail: Command '/root/module_unload_load.sh' failed (rc=1)

Test results available in /root/avocado/job-results/job-2016-08-30T02.52-45a81b6
root@ubuntu:~# 
```
I am running this  test in Ubuntu16.10 KVM guest , suggestion like  can check if  module is built in don't perform hot plug of that module , in Adocado API we have a   `avocado.utils.linux_modules` this is in  python you can inspire from this API

**Comment by hathyaga** [comment]
Still working on this PR.

**Comment by hathyaga** [comment]
@PraveenPenguin  Closing this PR. Will be sending a new PR which handles the check for built-in modules.

**Pull request closed without merging**
