### PR TITLE
nvme_cli_selftests.py remove depricated skip

### PR DESCRIPTION
**Pull request by nasastry**
This patch replaces depricated self.skip with self.cancel
With out this patch test will error "skip there is no attribute"

Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by nasastry** [comment]
With out patch
 (1/1) io/disk/ssd/nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests: ERROR (0.01 s)
ERROR| AttributeError: 'NVMeCliSelfTest' object has no attribute 'skip'

With patch
(1/1) io/disk/ssd/nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests: CANCEL (0.01 s)
ERROR| CANCEL 1-io/disk/ssd/nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests -> TestCancel: /dev/nvme0 does not exist

**Comment by narasimhan-v** [comment]
@nasastry This is already addressed by #892

**Comment by PraveenPenguin** [comment]
@narasimhan-v can you please rebase this PR

**Comment by narasimhan-v** [comment]
@PraveenPenguin Is this still needed ?

**Comment by PraveenPenguin** [comment]
@narasimhan-v ah sure i don't think it is needed closing , @narasimhan-v @nasastry thanks

**Pull request closed without merging**
