### PR TITLE
ras.py: Verify lsmcode output by grep FW

### PR DESCRIPTION
**Pull request by shirishaganta1**
Verifying the lsmcode output by checking for FW, added a condition check

Signed-off-by: Shirisha Ganta <SHIRISHA.Ganta1@ibm.com>

### CODE REVIEW

**Comment by shirishaganta1** [comment]
JOB ID     : b2d61fa385c10334f3a24c5fabca87843df45eb4
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T03.36-b2d61fa/job.log
 (01/12) ras.py:RASTools.test1_set_poweron_time:  PASS (1.32 s)
 (02/12) ras.py:RASTools.test2_sys_ident_tool:  PASS (1.13 s)
 (03/12) ras.py:RASTools.test3_lsmcode:  PASS (1.50 s)
 (04/12) ras.py:RASTools.test4_drmgr:  PASS (9.24 s)
 (05/12) ras.py:RASTools.test5_lsprop:  PASS (1.51 s)
 (06/12) ras.py:RASTools.test6_lsslot:  PASS (1.47 s)
 (07/12) ras.py:RASTools.test7_lsvio:  PASS (1.41 s)
 (08/12) ras.py:RASTools.test8_nvram:  PASS (1.22 s)
 (09/12) ras.py:RASTools.test9_ofpathname:  PASS (1.21 s)
 (10/12) ras.py:RASTools.test11_rtas_ibm_get_vpd:  PASS (1.32 s)
 (11/12) ras.py:RASTools.test12_rtas_errd_and_rtas_dump:  PASS (1.83 s)
 (12/12) ras.py:RASTools.test13_rtas_event_decode:  PASS (1.27 s)
RESULTS    : PASS 12 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T03.36-b2d61fa/results.html
JOB TIME   : 42.92 s
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/9663377/job.log)

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Comment by abdhaleegit** [comment]
Any reason check is only for one case  .. What about all other options?

**Comment by shirishaganta1** [comment]
> Any reason check is only for one case .. What about all other options?

checking it in the first case itself, whether the lsmcode output is giving the correct output or not. If it is not giving the expected output am failing it without proceeding it for other steps. As if it is failing in the initial stage then it is going to be fail in other cases also..

**Pull request merged**
