### PR TITLE
Test Interface Bonding(V3)

### PR DESCRIPTION
**Pull request by prudmirya**
Test Interface Bonding(V3)

check all seven interface bonding modes

Signed-off-by: prudhvi <mprudhvi@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by prudmirya** [comment]
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/602848/job.txt)
job log added

**Comment by narasimhan-v** [comment]
@prudmirya I still see https://github.com/avocado-framework-tests/avocado-misc-tests/pull/164#pullrequestreview-8405135 not yet taken care as I expected it to. So, we will discuss tomorrow and will provide my review then.

**Comment by PraveenPenguin** [comment]
@prudmirya any update here ?

**Comment by prudmirya** [comment]
modified script for any number of interfaces and closing current PR and opened new PR #203

**Pull request closed without merging**
