### PR TITLE
Rectified existing flow on processing dmesg in stress-ng test 

### PR DESCRIPTION
**Pull request by PraveenPenguin**
Rectified existing flow on processing dmesg

1-In Test There is no operation perform on collected dmesg
so removed duplicated logic to perform dmesg operation
and used already collected dmesg

2- Removed global variable to hold dmesg output as it waste
of heap memory

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@PraveenPenguin can you please change commit heading and message to be concise ?

**Comment by PraveenPenguin** [comment]
@narasimhan-v rectified it can you please check now

**Comment by narasimhan-v** [comment]
@PraveenPenguin job.log please

**Comment by PraveenPenguin** [comment]
Job Log :
```
[root@system ~]# avocado run stress-ng.py -m stress-ng.py.data/stress-ng.yaml 
JOB ID     : add0397194b508250fb2c972e6c067f36657e9de
JOB LOG    : /var/lib/libvirt/images/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-07-09T00.35-add0397/job.log
 (1/1) stress-ng.py:Stressng.test;exclude-stressors-workers-7a32: PASS (982.50 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 982.97 s
JOB HTML   :  /var/lib/libvirt/images/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-07-09T00.35-add0397/results.html
[root@system ~]
```

**Pull request merged**
