### PR TITLE
Fix for the Bug_241

### PR DESCRIPTION
**Pull request by vrbagalkote**
Added proper check to skip the test varients that are not applicable,
Also chenaged the variable name in yaml file, now its consistant accross
the script

Signed-off-by: Venkat R B <vrbagal1@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by vrbagalkote** [comment]
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/723259/job.txt)
Attached is the job.log file.

**Comment by PraveenPenguin** [comment]
please rebase as pylint or pep8 compliant

**Comment by vrbagalkote** [comment]
@PraveenPenguin , Yes doing the same

**Comment by narasimhan-v** [comment]
@vrbagalkote Can you please change the commit heading to a more meaningful one ?
Think of this: I just clone and see git log. I won't understand what the bug 241 is

**Comment by balamuruhans** [comment]
Also please fix the typos in commit message,
varients - variants
chenaged - changed
accross - across

**Comment by PraveenPenguin** [comment]
@narasimhan-v @balamuruhans thanks

**Pull request merged**
