### PR TITLE
Fixing the issue with hostname entries being added

### PR DESCRIPTION
**Pull request by PavamanSubramaniyam**
Properly adding the hostname entries to the /etc/hosts file in host lpar and copying the same to peer lpar

### CODE REVIEW

**Comment by abdhaleegit** [comment]
@PavamanSubramaniyam what was the problem with older code ? just wanted to understand the issue this PR is fixing

**Comment by abdhaleegit** [comment]
@FarooqAbdulla01 Please review

**Review by abdhaleegit — CHANGES_REQUESTED** [review]
job logs please

**Comment by PavamanSubramaniyam** [comment]
# avocado run --max-parallel-tasks=1 htx_nic_devices.py -m htx_nic_devices.py.data/htx_nic_devices.yaml
JOB ID     : 43230d5a222319e7347566697d362c25e63b34f4
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-04-25T05.02-43230d5/job.log
 (1/3) htx_nic_devices.py:HtxNicTest.test_start;run-a978: STARTED
 (1/3) htx_nic_devices.py:HtxNicTest.test_start;run-a978: PASS (461.79 s)
 (2/3) htx_nic_devices.py:HtxNicTest.test_check;run-a978: STARTED
 (2/3) htx_nic_devices.py:HtxNicTest.test_check;run-a978: PASS (122.13 s)
 (3/3) htx_nic_devices.py:HtxNicTest.test_stop;run-a978: STARTED
 (3/3) htx_nic_devices.py:HtxNicTest.test_stop;run-a978: PASS (11.52 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-04-25T05.02-43230d5/results.html
JOB TIME   : 617.52 s

**Comment by abdhaleegit** [comment]
@PavamanSubramaniyam on confirmation if these changes works on SLES OS ?

**Comment by PavamanSubramaniyam** [comment]
Below are the results for execution on SLES 15 SP5 OS which is pasted here.

# avocado run --max-parallel-tasks=1 htx_nic_devices.py -m htx_nic_devices.py.data/htx_nic_devices.yaml
JOB ID     : b9aa3a0e6f9c5388dbe76944618058d97e1fc16f
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-04-25T05.55-b9aa3a0/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/3) htx_nic_devices.py:HtxNicTest.test_start;run-1725: STARTED
 (1/3) htx_nic_devices.py:HtxNicTest.test_start;run-1725: PASS (304.15 s)
 (2/3) htx_nic_devices.py:HtxNicTest.test_check;run-1725: STARTED
 (2/3) htx_nic_devices.py:HtxNicTest.test_check;run-1725: FAIL: Their are errors while htx run in host (0.14 s)
 (3/3) htx_nic_devices.py:HtxNicTest.test_stop;run-1725: STARTED
 (3/3) htx_nic_devices.py:HtxNicTest.test_stop;run-1725: PASS (5.23 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-04-25T05.55-b9aa3a0/results.html
JOB TIME   : 323.79 s

Test summary:
htx_nic_devices.py:HtxNicTest.test_check;run-1725: FAIL

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Pull request merged**
